"""Proposed ledger rows of study N (nose v2) with the exact 23-column header of docs/evidence.csv.

Id ranges (docs/revJ_plan.md section 4): AMF-135...154, ACT-100...104, OPT-50...54, PAT-40...44.  Every source row below
was opened by this study on 2026-09-28 (full text, datasheet, patent page or abstract, as stated in access_level).
Handwriting-kinematics and visual-feedback sources carry AMF and OPT ids only because those are this study's ranges;
the lead may renumber them into CON or HAP.  Rows marked "this study" are derived results (CALC or SIM).
Rivers, Moyer & Durand 2012 is already HAP-18; it was re-read and an amendment is proposed in docs/nose_v2.md.
"""
from __future__ import annotations

import csv
import os
from typing import Dict, List

HEADER = ["id", "topic", "citation", "year", "doi_or_url", "source_type", "evidence_class", "access_level", "task_or_setup",
          "participants_or_bench", "comparator", "key_quantitative_findings", "units_and_conditions", "locator", "limitations",
          "relevance_to_design", "transferability", "transferability_reason", "design_implication", "retrieved", "search_query",
          "stream", "lead_verification"]
RET = "2026-09-28"


def _r(**kw) -> Dict[str, str]:
    row = {k: "" for k in HEADER}
    row.update({k: str(v) for k, v in kw.items()})
    row.setdefault("retrieved", RET)
    if not row["retrieved"]:
        row["retrieved"] = RET
    return row


SHARED_WITH_OTHER_STUDIES = {"HAP-62", "HAP-90", "HAP-91", "HAP-92"}


def rows(results: Dict = None) -> List[Dict[str, str]]:
    R = results or {}
    out = [
        # ------------------------------------------------------------------ actuators, mechanisms, materials (AMF)
        _r(id="AMF-135", topic="Large-range XY flexure stage: size and dynamics of a 10 x 10 mm parallel-kinematic flexure bearing",
           citation="Awtar S, Parmar G. Design of a large range XY nanopositioning system. ASME J Mechanisms Robotics 2013;5(2):021008 (author PDF).",
           year="2013", doi_or_url="https://doi.org/10.1115/1.4023874 ; https://psdl.engin.umich.edu/pdf/J16.pdf", source_type="journal",
           evidence_class="physical bench experiment", access_level="full text",
           task_or_setup="Double-parallelogram flexure modules (DPFM), wire-EDM from 25 mm Al6061-T651; BEI Kimco LA24-20-000A voice coils; 5 kHz control",
           participants_or_bench="bench", comparator="AMF-06 (same laboratory, moving-magnet trade-offs)",
           key_quantitative_findings="10 mm x 10 mm range; beam length 47.5 mm, in-plane thickness 0.63 mm, height 25 mm; flexure bearing 255 x 255 mm, frame 385 x 385 mm; cross-axis coupling < 60 um, parasitic rotation < 100 urad; first natural frequency ~18 Hz; a mode at 1315 Hz falls to ~150 Hz at large displacement; voice coils 11.12 N/A, 111.2 N peak",
           units_and_conditions="mm, Hz, N/A", locator="Sections 3-6, Fig. 5-6", limitations="Nanopositioning scale and priorities; aluminium flexures",
           relevance_to_design="Candidate 4 (planar parallel flexure stage) for a +-5-8 mm pen tip",
           transferability="medium", transferability_reason="Scaling of flexure length with travel is general; the pen needs far less precision",
           design_implication="A planar double-parallelogram stage with +-5 mm travel needs ~50 mm beams: it cannot fit a 24 mm pen; only wire (NiTi) or gimbal flexures are compact enough",
           search_query="WebSearch: Awtar Parmar Design of a large range XY nanopositioning system 10 mm flexure", stream="AMF"),
        _r(id="AMF-136", topic="Two-axis voice-coil tilt actuator: Optotune MR-15-30 fast steering mirror",
           citation="Optotune Switzerland AG. Datasheet MR-15-30 Rev. 3, fast steering mirror, 24.09.2025.", year="2025",
           doi_or_url="https://static1.squarespace.com/static/5d9dde8d550f0a5f20b60b6a/t/68e8eed61d9f4e2676d94e9e/1760095958810/Optotune+MR-15-30.pdf",
           source_type="datasheet", evidence_class="manufacturer statement", access_level="full text",
           task_or_setup="Dual-axis voice-coil mirror with optical position feedback, MR-E-2/MR-E-3 drivers", participants_or_bench="bench (manufacturer)",
           comparator="AMF-137",
           key_quantitative_findings="Mechanical tilt +-25 deg per axis; mirror 15 mm; housing 30 mm diameter x 14.5 mm; 29.3 g; centre of rotation 1.3 mm behind the mirror surface; static motor constant 3 rad/A; resonance 11-13 Hz (x), 15-18 Hz (y); full-scale bandwidth 20 Hz (+-25 deg); small-signal bandwidth 300/400 Hz (+-0.1 deg); coil 11 ohm, 6 mH; 0.37 A RMS single axis (0.26 A both); 2 A peak for 10 ms; 1.5 W max mean power; repeatability 40 urad RMS",
           units_and_conditions="Datasheet, room temperature", locator="Pages 1-2 tables", limitations="Optical product; no force constant in N; flexure/bearing details not given",
           relevance_to_design="A compact commercial 2-axis tilt actuator (a gimbal plus voice coils) at pen-like scale",
           transferability="medium", transferability_reason="Same physics (2-axis moving-magnet tilt with a soft suspension); larger diameter than a pen bore",
           design_implication="+-25 deg with 20 Hz at full scale fits in 30 mm: a +-8-10 deg pen gimbal in a 20 mm bore with 80 Hz on small signals is plausible",
           search_query="WebSearch: Optotune MR-E-2 fast steering mirror datasheet mechanical tilt angle bandwidth", stream="AMF"),
        _r(id="AMF-137", topic="Galvanometer (limited-angle moving-magnet) scanners: Cambridge Technology 62xxH series",
           citation="Cambridge Technology. 62xxH Series galvanometer scanners datasheet DS00003 R1 v4.", year="n.d.",
           doi_or_url="https://camtechfiles.s3-us-west-2.amazonaws.com/s3fs-public/Datasheet%20-%20Galvos-62xxH%20Series-DS00003_R1_v4_1_1.pdf",
           source_type="datasheet", evidence_class="manufacturer statement", access_level="full text",
           task_or_setup="Closed-loop single-axis galvanometers", participants_or_bench="bench (manufacturer)", comparator="AMF-136",
           key_quantitative_findings="6200H / 6210H: rotor inertia 0.013 / 0.018 g cm2; torque constant 1.20e4 / 2.79e4 dyne cm/A; coil 2.14 / 3.7 ohm; 52 / 109 uH; RMS current 2.3 / 2.4 A; peak 6 / 8 A; small-step response 130 / 100 us; weight 13.3 / 18 g; max scan angle 40 deg; 6200H housing about 12.7 mm diameter (drawing)",
           units_and_conditions="Datasheet tables, +-10 %", locator="Page 2 table; 6200H drawing", limitations="Optical scanners; torque rather than force; mirror loads",
           relevance_to_design="Candidate 4: a galvanometer-style rotary voice coil per axis",
           transferability="high", transferability_reason="Motor constants are physics",
           design_implication="Km of a 6210H = 2.79e-3 N m/A / sqrt(3.7 ohm) = 1.45e-3 N m/sqrt(W); at a 45 mm lever that is 0.032 N/sqrt(W) at the tip, about 3-10x below a flat-coil gimbal, for 36 g for two axes: rejected (CALC)",
           search_query="WebSearch: galvanometer scanner datasheet torque constant rotor inertia coil resistance 6210H", stream="AMF"),
        _r(id="AMF-138", topic="Ultrasonic piezo linear motors (PI PILine P-661, U-164, U-264): speed, force, drive power",
           citation="Physik Instrumente (PI). Small ultrasonic motors and actuators catalogue pages (P-661, U-164, U-264, M-272).", year="n.d.",
           doi_or_url="https://www.piezo-motor.net/pdf/Ultrasonic_Motor_Actuators_Small_Linear.pdf", source_type="datasheet",
           evidence_class="manufacturer statement", access_level="full text", task_or_setup="Catalogue specifications", participants_or_bench="bench (manufacturer)",
           comparator="AMF-15 (New Scale SQUIGGLE)",
           key_quantitative_findings="P-661: 14 x 35 x 6 mm, 10 g, max velocity 500 mm/s, push/pull 2 N, holding 1.5 N powered down, 210 kHz, motor 120 V peak-peak, driver electronics 12 V and 5 W. U-164: 500 mm/s, 5 g acceleration, self-locking, push/pull to 4 N, 60 V RMS, driver up to 10 W. U-264: 250 mm/s, 7-15 N, 200 Vpp, 80-100 g",
           units_and_conditions="Catalogue", locator="P-661, U-164 and U-264 tables", limitations="Driver power quoted for PI's drive boards, not an optimised pen driver",
           relevance_to_design="Candidate 4: piezo/ultrasonic tip drives", transferability="high", transferability_reason="Drive voltage and power are inherent to the principle",
           design_implication="Fast enough (500 mm/s), but 120 Vpp and 5-10 W of driver power per axis against a 0.08 W pen, and a self-locking friction drive cannot yield to the writer: rejected for the tip",
           search_query="WebSearch: PILine ultrasonic piezo motor datasheet velocity holding force U-164", stream="AMF"),
        _r(id="AMF-139", topic="NdFeB N52 grade: remanence, coercivity, density, temperature coefficients",
           citation="Arnold Magnetic Technologies. N52 sintered neodymium-iron-boron magnets, datasheet (2015-10-21).", year="2015",
           doi_or_url="https://www.arnoldmagnetics.com/wp-content/uploads/2017/11/N52-151021.pdf", source_type="datasheet",
           evidence_class="manufacturer statement", access_level="full text", task_or_setup="Grade datasheet", participants_or_bench="not applicable",
           comparator="AMF-28 (K&J grade table)",
           key_quantitative_findings="Br 1.42-1.48 T (nominal 1.45); HcB 836-1122 kA/m; HcJ >= 875 kA/m; (BH)max 390-422 kJ/m3; density 7.6 g/cm3; alpha(Br) -0.12 %/degC; alpha(HcJ) -0.62 %/degC; Curie 310 degC",
           units_and_conditions="20 degC; coefficients 20-60 degC", locator="Page 1 tables", limitations="Grade values; no demagnetisation check in the pen geometry here",
           relevance_to_design="Magnet remanence used by the gap-flux calculation (B_r 1.42 T low end)", transferability="high",
           transferability_reason="Material data", design_implication="Use B_r 1.42 T for N52 (80 degC class) and the SH grades (~1.38 T, 150 degC) where the coil is warm",
           search_query="WebSearch: NdFeB grade N52 datasheet Br Hcj maximum operating temperature", stream="AMF"),
        _r(id="AMF-140", topic="Soft magnetic cobalt-iron for thin flux returns: Hiperco 50A saturation",
           citation="Carpenter Electrification. Hiperco 50A datasheet landing page.", year="n.d.",
           doi_or_url="https://www.carpenterelectrification.com/hiperco-50a-datasheet", source_type="manufacturer",
           evidence_class="manufacturer statement", access_level="product page (full datasheet behind a form)",
           task_or_setup="Material page", participants_or_bench="not applicable", comparator="1010 steel (handbook, ASSUMPTION)",
           key_quantitative_findings="Saturation induction 24 kilogauss (2.4 T); FeCoV alloy (UL Prospector and search summaries: Co 48.5 %, V 2 %)",
           units_and_conditions="Datasheet summary", locator="Landing page text", limitations="Permeability, coercivity and density not read (form-gated)",
           relevance_to_design="Back-iron option in the optimiser (thinner return ring for the same flux)", transferability="high",
           transferability_reason="Material property", design_implication="A Hiperco return ring can be ~30 % thinner than a 1010 one at the same flux; cost and machining to check",
           search_query="WebSearch: Hiperco 50A datasheet saturation induction 2.4 T", stream="AMF"),
        _r(id="AMF-141", topic="Superelastic nitinol: recoverable strain and strength (large-deflection flexure material)",
           citation="Fort Wayne Metals. Superelastic Nitinol (materials page).", year="n.d.",
           doi_or_url="https://fwmetals.com/what-we-do/materials/nitinol/superelastic-nitinol", source_type="manufacturer",
           evidence_class="manufacturer statement", access_level="full text (web page)", task_or_setup="Material page", participants_or_bench="not applicable",
           comparator="AMF-20 (301 / 17-7PH), AMF-142 (fatigue)",
           key_quantitative_findings="Up to 8 % tensile strain without significant permanent deformation after heat treatment; permanent set < 0.5 % after 8 %; UTS 1103-1378 MPa (straight annealed), 1379-1655 MPa (cold worked); upper plateau 448-758 MPa; lower plateau 48-483 MPa; active Af -10 to 22 degC",
           units_and_conditions="Room temperature, tension", locator="Page text", limitations="No elastic modulus or fatigue data on the page",
           relevance_to_design="Flexure option for a +-8-10 deg gimbal and for the XY wire stage", transferability="medium",
           transferability_reason="Wire and strip forms exist; bending fatigue governs (AMF-142)",
           design_implication="Static stroke is not the limit for a NiTi gimbal; the cyclic strain amplitude is (AMF-142)",
           search_query="WebSearch: superelastic nitinol wire datasheet recoverable strain 8% plateau stress fatigue", stream="AMF"),
        _r(id="AMF-142", topic="Nitinol fatigue: strain-amplitude limit at 10^7 cycles",
           citation="Pelton AR, Schroeder V, Mitchell MR, Gong XY, Barney M, Robertson SW. Fatigue and durability of Nitinol stents. J Mech Behav Biomed Mater 2008;1(2):153-164.",
           year="2008", doi_or_url="https://doi.org/10.1016/j.jmbbm.2007.08.001 ; https://confluentmedical.com/wp-content/uploads/references/144_Pelton_Schroeder_Mitchell_Gong_Barney_Robertson_2008.pdf",
           source_type="journal", evidence_class="physical bench experiment", access_level="full text",
           task_or_setup="Diamond-shaped stent sub-components, mean strains -4 to +4 %, alternating 0.07-3 %, up to 1e7 cycles", participants_or_bench="bench",
           comparator="conventional engineering alloys",
           key_quantitative_findings="10^7-cycle fatigue strain-amplitude limit +-0.4 %; mean strain above about 1.5 % does not shorten life (increases it); the strain amplitude, not the mean, governs",
           units_and_conditions="37 degC, cyclic", locator="Abstract; Fig. 7", limitations="Stent geometry and surface; bending of strips may differ",
           relevance_to_design="Fatigue allowable for NiTi flexures (0.4 % amplitude, safety factor 1.5 applied)", transferability="medium",
           transferability_reason="Same alloy class; different geometry", design_implication="Design NiTi gimbal strips to <= 0.27 % alternating strain at the usable travel",
           search_query="WebSearch: Pelton 2008 Fatigue and durability of Nitinol stents strain amplitude 0.4%", stream="AMF"),
        _r(id="AMF-143", topic="2-DOF Lorentz-force actuator (moving coil): force constants and force variation over a +-5 mm stroke",
           citation="Yang F, Zhao Y, Mu X, Zhang W, Jiang L, Yue H, Liu R. A novel 2-DOF Lorentz force actuator for the modular magnetic suspension platform. Sensors 2020;20(16):4365.",
           year="2020", doi_or_url="https://doi.org/10.3390/s20164365 ; https://pmc.ncbi.nlm.nih.gov/articles/PMC7472190/", source_type="journal",
           evidence_class="physical bench experiment", access_level="full text (PMC)", task_or_setup="Prototype 117 x 106 x 118 mm, 2.59 kg; FEM and measurement",
           participants_or_bench="bench", comparator="FEM of the same actuator",
           key_quantitative_findings="Force coefficients 5.11 N/A (vertical) and 4.08 N/A (horizontal) measured (FEM 5.55 / 4.47, 9-10 % high); force varies 30.9 % (vertical) and 21.6 % (horizontal) over the full +-5 mm / +-10 deg motion; mean gap flux 0.33 T in 19-25 mm gaps; PID positioning 15 um",
           units_and_conditions="1 A test current", locator="Sections 3-5", limitations="Large, moving-coil; different scale",
           relevance_to_design="Force-constant variation over a large 2-D stroke: the model's constant-Km assumption", transferability="medium",
           transferability_reason="Same physics at a larger scale", design_implication="Expect 20-30 % Km variation over the stroke: the servo must linearise (Hall map) and the bench must map Km (EXP-N02)",
           search_query="WebSearch: two degree of freedom moving magnet Lorentz force tilt actuator axial air gap flat coils", stream="AMF"),
        _r(id="AMF-144", topic="Constant-force springs: stock sizes, loads and rated cycle life",
           citation="Lee Spring. Constant Force Spring Series (catalogue pages 315-316).", year="2021",
           doi_or_url="https://www.leespring.com/sites/default/files/2021-02/constant-force-lee-spring-us.pdf", source_type="datasheet",
           evidence_class="manufacturer statement", access_level="full text", task_or_setup="Catalogue", participants_or_bench="not applicable",
           comparator="Rev H refill spring (ASSUMPTION 0.15 N)",
           key_quantitative_findings="Type 301 stainless strip; four life ranges 2500, 4000, 13000 and 25000 cycles; smallest stock part LCF 025 04 025S: 0.10 mm x 6.35 mm strip, ID 7.54 mm, 0.30 kg (2.9 N) load; rated load reached after an initial deflection of 1.25 x the diameter; one and a half wraps must remain on the drum",
           units_and_conditions="Catalogue", locator="Tables and mounting guide", limitations="Stock loads are 20x the pen's 0.15 N; custom springs needed",
           relevance_to_design="The refill spring of architecture B slides 13.5 mm (Rev H) to 24-27 mm (+-6 mm travel)", transferability="high",
           transferability_reason="Strip-spring fatigue is inherent: each strip section flexes fully as it passes the drum",
           design_implication="Rated lives of 2.5-25 thousand cycles are far below the tremor-rate sliding of the refill (about 36 000 cycles per hour at 10 Hz): a constant-force strip spring is a fatigue risk; replace or test (EXP-N05)",
           search_query="WebSearch: constant force spring design data stainless small force catalogue life cycles", stream="AMF"),
        _r(id="AMF-145", topic="Latching (self-holding) solenoid: zero-power hold",
           citation="Takano. Latching solenoids product page (TSB series).", year="n.d.", doi_or_url="https://takano-usa.com/latching-soloenoid/",
           source_type="manufacturer", evidence_class="manufacturer statement", access_level="product page", task_or_setup="Catalogue list",
           participants_or_bench="not applicable", comparator="PAT-41 (plotter pen lift)",
           key_quantitative_findings="Smallest listed TSB-0705: 16 x 16 x 35.7 mm, 5 mm stroke, holding force >= 3 N de-energised; switched by electrical pulses",
           units_and_conditions="Catalogue", locator="Series table", limitations="Too large for a pen; pulse energy not given",
           relevance_to_design="Principle for the refill lift: a magnetic latch holds pen-up/pen-down with no power", transferability="medium",
           transferability_reason="Principle transfers; the part does not", design_implication="Use a bistable magnetic latch (pulse to switch) for the refill lift; size a custom 0.5 mm version",
           search_query="WebSearch: miniature bistable latching linear actuator moving magnet datasheet stroke holding force zero power", stream="AMF"),
        _r(id="AMF-146", topic="Handwriting kinematics: which stroke features are invariant (size vs duration)",
           citation="Teulings HL, Schomaker LRB. Invariant properties between stroke features in handwriting. Acta Psychol (Amst) 1993;82(1-3):69-88.",
           year="1993", doi_or_url="https://doi.org/10.1016/0001-6918(93)90005-c", source_type="journal", evidence_class="physical human study",
           access_level="abstract only", task_or_setup="Repeated handwriting patterns, stroke segmentation", participants_or_bench="healthy writers (abstract)",
           comparator="between-condition and between-stroke correlations",
           key_quantitative_findings="Vertical stroke size has higher signal-to-noise ratios and between-condition correlations than stroke duration or peak force; downstrokes more invariant than upstrokes; horizontal stroke size is not invariant; stroke durations show no between-stroke correlations",
           units_and_conditions="Abstract (no numbers quoted)", locator="Abstract", limitations="Abstract only",
           relevance_to_design="Autowrite plans letters in time freely: the writer's vertical size is the feature to keep", transferability="medium",
           transferability_reason="Healthy adult writing", design_implication="The planner may retime strokes (durations are not invariant) but must keep letter heights; horizontal spacing can flex",
           search_query="WebSearch: Teulings Schomaker 1993 Invariant properties between stroke features in handwriting; PubMed efetch 8475777",
           stream="AMF (handwriting kinematics; CON would fit)"),
        _r(id="AMF-147", topic="Handwriting kinematics: the speed-curvature (two-thirds) power law and its variability",
           citation="Zago M, Matic A, Flash T, Gomez-Marin A, Lacquaniti F. The speed-curvature power law of movements: a reappraisal. Exp Brain Res 2018;236:69-82 (on Lacquaniti, Terzuolo, Viviani 1983).",
           year="2018", doi_or_url="https://doi.org/10.1007/s00221-017-5108-z", source_type="journal", evidence_class="review",
           access_level="full text", task_or_setup="Reappraisal with drawing data and Drosophila larvae", participants_or_bench="mixed",
           comparator="Marken and Shaffer 2017 (artefact claim)",
           key_quantitative_findings="Angular speed proportional to curvature^(2/3) in planar drawing (Lacquaniti et al. 1983); the exponent varies with shape and environment (about 2/3 in air, 3/4 in water in one cited study); the law is not a statistical artefact",
           units_and_conditions="Dimensionless exponents", locator="Introduction; Results", limitations="Law describes human timing; not a constraint on a machine",
           relevance_to_design="Speed profile of autowritten strokes (a human-like time law may read as more natural)", transferability="medium",
           transferability_reason="Human drawing", design_implication="The planner's constant-speed-limited timing ignores the 2/3 law; a human-like time law is an option for ink quality (not needed for legibility here)",
           search_query="WebSearch: Lacquaniti Terzuolo Viviani 1983 two-thirds power law", stream="AMF (handwriting kinematics; CON would fit)"),
        _r(id="AMF-148", topic="Writing speed and line quality: objective speed benchmarks",
           citation="Dziedzic T, Yilmaz AS, Szafranska A. How fast is fluent handwriting? Forensic Sci Int 2026;383:112896.",
           year="2026", doi_or_url="https://doi.org/10.1016/j.forsciint.2026.112896", source_type="journal", evidence_class="physical human study",
           access_level="abstract only", task_or_setup="35 hybrid ink/digitised samples written at 10-60 mm/s; experts rated line quality", participants_or_bench="94 expert responses",
           comparator="speed bins",
           key_quantitative_findings="Samples at average speeds 10-60 mm/s; poor line quality was most often assigned below 20 mm/s and good line quality dominated above 50 mm/s (chi-square significant; strong Spearman correlations)",
           units_and_conditions="mm/s average writing speed", locator="Abstract", limitations="Abstract only; forensic line-quality judgement",
           relevance_to_design="Drawing speed of autowrite (the planner draws at up to 45 mm/s)", transferability="medium",
           transferability_reason="Ink line quality depends on speed for any pen",
           design_implication="Draw autowritten strokes at >= 20 mm/s where possible; slow drawing may look tremulous to readers (test in EXP-N07)",
           search_query="WebSearch: adult handwriting speed letters per minute study; PubMed efetch 41775119", stream="AMF (handwriting kinematics; CON would fit)"),
        _r(id="AMF-149", topic="Handheld swept inkjet printer (a hand-swept device that lays text): PrinCube",
           citation="CNX Software. PrinCube said to be smallest handheld smartphone color-inkjet printer that prints on anything (crowdfunding), 2019-11-01.",
           year="2019", doi_or_url="https://www.cnx-software.com/2019/11/01/princube-smallest-handheld-smartphone-color-inkjet-printer-prints-on-anything/",
           source_type="website", evidence_class="manufacturer statement", access_level="secondary account", task_or_setup="Product description",
           participants_or_bench="not applicable", comparator="PAT-44 (HP handy printer)",
           key_quantitative_findings="Prints one line up to 14.29 mm (0.5625 in) tall as the user sweeps it; 900 mAh; about 6 h of continuous printing; tracking method not disclosed",
           units_and_conditions="Product claims", locator="Article text", limitations="Secondary account; crowdfunding claims; tracking undisclosed",
           relevance_to_design="The hand-sweeps, device-writes interaction exists commercially (inkjet, not a ballpoint)", transferability="low",
           transferability_reason="Inkjet with a wide head, no moving nib", design_implication="Autowrite is a known interaction; the pen's version draws with a nib within +-6 mm",
           search_query="WebSearch: handheld inkjet printer sweep over paper prints text as you move PrinCube specifications", stream="AMF"),
        _r(id="AMF-153", topic="Near-field optical-flow sensor for a page sensor at a distance: PixArt PAA5100JE",
           citation="NZPRG (robots.org.nz). The PAA5100JE near optical flow sensor, 2021-07-09.", year="2021",
           doi_or_url="https://robots.org.nz/2021/07/09/the-paa5100je-near-optical-flow-sensor/", source_type="website",
           evidence_class="manufacturer statement", access_level="secondary account", task_or_setup="Hobbyist evaluation", participants_or_bench="bench (informal)",
           comparator="OPT-54 (PMW3360)",
           key_quantitative_findings="Working range 10-35 mm; tracking speed up to 45 in/s; output depends on the surface (author; no accuracy numbers)",
           units_and_conditions="Blog", locator="Text", limitations="Secondary; datasheet link returned an HTML page",
           relevance_to_design="A paper sensor that tolerates the pen's changing height and tilt", transferability="low",
           transferability_reason="Frame rate (242 fps elsewhere in search results) too low for a 1 kHz page sensor",
           design_implication="A far-field flow sensor is too slow for the 1 kHz, 2 ms page-sensor assumption; a mouse-class sensor needs a flat window near the paper (OPT-54)",
           search_query="WebSearch: PixArt PAA5100JE optical flow sensor datasheet frame rate working distance", stream="OPT (filed under AMF)"),
        # ------------------------------------------------------------------ this study, derived (AMF)
        _r(id="AMF-150", topic="Actuator gap flux by magpylib with iron images; Rev H's lumped leakage factor recalibrated (this study)",
           citation="This study: nose2/magnetics.py, nose2/designs.revh_as_designed; results/nose2/nose2.json -> magnetics.", year="2026",
           doi_or_url="results/nose2/nose2.json", source_type="derived simulation", evidence_class="calculation", access_level="full text",
           task_or_setup="magpylib 5.2 analytic cuboids, infinitely permeable planes by images (3 periods), 720 radial and 240 axial geometries",
           participants_or_bench="not applicable", comparator="opt/inertial/adjoint.py lumped model (eta_leak 0.55)",
           key_quantitative_findings=R.get("amf150", "see nose2.json magnetics"),
           units_and_conditions="T, N/sqrt(W)", locator="docs/nose_v2.md section 4.2", limitations="No saturation, no finite iron, no FEM; image method is an upper bound",
           relevance_to_design="Force constant of every candidate and of Rev H", transferability="medium",
           transferability_reason="Analytic magnets are exact; the iron model is idealised", design_implication="Measure Km on the Rev H bench before relying on 0.47 N/sqrt(W) (EXP-I05)",
           search_query="", stream="AMF"),
        _r(id="AMF-151", topic="Front-end closure (DEC-034) generalised to +-4-9 mm of tip travel (this study)",
           citation="This study: nose2/frontend.py (vectorised re-implementation of opt/inertial/front_end.py, checked to 1e-4 mm).", year="2026",
           doi_or_url="results/nose2/nose2.json", source_type="derived simulation", evidence_class="calculation", access_level="full text",
           task_or_setup="Rules of FrontRules unchanged; 35-75 deg; every direction; z_p 30-80 mm", participants_or_bench="not applicable",
           comparator="Rev H closure (R 6.75 mm, slide 13.5 mm)", key_quantitative_findings=R.get("amf151", "see nose2.json frontend"),
           units_and_conditions="mm", locator="docs/nose_v2.md section 3", limitations="Rigid geometry; no tolerance stack",
           relevance_to_design="Ring size, visibility and refill slide of a larger-travel nose", transferability="high",
           transferability_reason="Geometry", design_implication=R.get("amf151_impl", "see docs/nose_v2.md section 3"),
           search_query="", stream="AMF"),
        _r(id="AMF-152", topic="Architecture B refill: a freely sliding refill follows ordinary pen lifts (this study)",
           citation="This study: CALC with opt/inertial/front_end.protrusion (docs/nose_v2.md section 6).", year="2026", doi_or_url="docs/nose_v2.md",
           source_type="derived simulation", evidence_class="calculation", access_level="full text",
           task_or_setup="Rev H ring (R 6.75 mm): extension available before the refill's forward stop", participants_or_bench="not applicable",
           comparator="aiguide writers' pen-lift height 1.5 mm",
           key_quantitative_findings="With the forward stop set for 35 deg, the ball stays on the paper for pen lifts up to 1.0 / 2.9 / 4.8 / 6.5 mm at 40 / 50 / 60 / 70 deg of tilt; the synthetic writers lift 1.5 mm between strokes",
           units_and_conditions="mm", locator="docs/nose_v2.md section 6", limitations="Assumes a free slide on a constant-force spring (Rev H text); friction ignored",
           relevance_to_design="Strokes would be joined by ink in Rev H and in any larger-travel B nose", transferability="high",
           transferability_reason="Geometry", design_implication="Architecture B needs a controlled refill (pen-up by the pen: brake and latch) for normal writing as well as for autowrite",
           search_query="", stream="AMF"),
        _r(id="AMF-154", topic="Travel needed for delayed ink (the ink trailing the hand by tau) (this study)",
           citation="This study: nose2/tasks.delayed_ink on synthetic aiguide writers (tuning), rescaled to LIT CON-20 speeds.", year="2026",
           doi_or_url="results/nose2/nose2.json", source_type="derived simulation", evidence_class="calculation", access_level="full text",
           task_or_setup="|p(t) - p(t - tau)| on inked samples", participants_or_bench="synthetic writers", comparator="straight-line bound v tau",
           key_quantitative_findings=R.get("amf154", "see nose2.json tasks.delayed_ink"),
           units_and_conditions="mm", locator="docs/nose_v2.md section 2", limitations="Synthetic writers (20-34 mm/s); no human acceptance data",
           relevance_to_design="Whether a +-6 mm nose can support delayed ink", transferability="medium",
           transferability_reason="Speed scaling from CON-20", design_implication=R.get("amf154_impl", "see docs/nose_v2.md section 2"),
           search_query="", stream="AMF"),
        # ------------------------------------------------------------------ handheld actuated tools (ACT)
        _r(id="ACT-100", topic="Position-correcting handheld tool, commercial: Shaper Origin correction range and retraction",
           citation="Shaper Tools. Complete Origin System product page; Help Center 'How does Shaper Origin work?'.", year="n.d.",
           doi_or_url="https://www.shapertools.com/en-us/complete-origin-system ; https://support.shapertools.com/hc/en-us/articles/115002754074-How-does-Shaper-Origin-work",
           source_type="manufacturer", evidence_class="manufacturer statement", access_level="product page",
           task_or_setup="Handheld CNC router with camera localisation and a motorised spindle stage", participants_or_bench="not applicable",
           comparator="HAP-18 (Rivers et al. 2012)",
           key_quantitative_findings="Auto-corrects within a 1/2 in (12.7 mm) range; automatically retracts when the user goes out of bounds; 43 mm digital depth of cut with automated touch-off; tool 6.75 kg; 'accurate to within 1/100th of an inch' of the intended path (claim)",
           units_and_conditions="Product claims", locator="Specifications section; help article", limitations="Manufacturer claims; router, not a pen",
           relevance_to_design="The closest commercial analogue of autowrite: human coarse motion, device fine correction, retract when out of reach",
           transferability="medium", transferability_reason="Same control split; different scale and load",
           design_implication="Autowrite should lift the refill (retract) when the text leaves the reach, as Origin retracts its cutter; the pen's axial DOF provides this",
           search_query="WebSearch: Shaper Origin specifications auto-correct range", stream="ACT"),
        _r(id="HAP-62", topic="Cooperative handheld robots: intention prediction and user frustration when the tool disobeys",
           citation="Stolzenwald J, Mayol-Cuevas WW. Rebellion and obedience: the effects of intention prediction in cooperative handheld robots. arXiv:1903.08158 (2019).",
           year="2019", doi_or_url="https://arxiv.org/abs/1903.08158", source_type="preprint", evidence_class="physical human study",
           access_level="full text (HTML)", task_or_setup="6-DoF-tip handheld robot, block-assembly tasks with intention prediction and 'rebel' modes",
           participants_or_bench="16 + 20 participants (2 excluded)", comparator="follow-intention vs rebel modes",
           key_quantitative_findings="Intention prediction 87.9 % (picking) and 93.3 % (placing) at zero anticipation; 71.6 % 500 ms before picking; 80.1 % 1500 ms before dropping; significantly higher frustration in rebel mode than follow-intention (p = .019); Bristol press release (2015): users preferred a fully autonomous tool and it cut completion time and workload",
           units_and_conditions="Lab tasks", locator="Results", limitations="Pick-and-place, not writing; preprint",
           relevance_to_design="Human factors of a tool that moves on its own while held (autowrite mode)", transferability="low",
           transferability_reason="Different task", design_implication="Autowrite must follow the user's sweep and never fight it; a mode the user turns on (docs/revJ_plan.md section 6)",
           search_query="WebSearch: Gregg-Smith Mayol-Cuevas cooperative handheld robot", stream="ACT"),
        _r(id="ACT-102", topic="Letters presented to the hand by a mechanically moved stylus: size and speed readable",
           citation="Hasegawa K, Sakurai T, Makino Y, Shinoda H. Manual character transmission by presenting trajectories of 7mm-high letters in one second. arXiv:1503.07401 (2015).",
           year="2015", doi_or_url="https://arxiv.org/abs/1503.07401", source_type="preprint", evidence_class="physical human study",
           access_level="full text", task_or_setup="Stylus moved by a 2-D stepper stage with a solenoid for up/down; lower-case letters at 1 letter/s",
           participants_or_bench="sighted adults", comparator="14 mm vs 7 mm letters, before/after 5 min training",
           key_quantitative_findings="14 mm letters at 1 letter/s read 71.9 % at first, 91.3 % after 5 min training (SD 12.7 % -> 6.7 %); 7 mm letters still read 85.1 % (SD 8.2 %)",
           units_and_conditions="Letters per second, mm", locator="Abstract; experiments", limitations="Reading by the hand, not ink",
           relevance_to_design="A device can move a held stylus through letters at about 1 letter/s; up/down by a solenoid (the axial DOF)", transferability="low",
           transferability_reason="Haptic reading task", design_implication="Autowrite at 2-3 letters/s is faster than letter presentation to the hand; the stylus up/down solenoid is prior art for the refill lift",
           search_query="WebSearch: adult handwriting letter height writing speed (result: arXiv 1503.07401)", stream="ACT"),
        _r(id="ACT-103", topic="Tip-mechanism candidates for +-5-8 mm, sized and optimised (this study)",
           citation="This study: nose2/designs.py, nose2/optimise.py (adjoint + CMA-ES); results/nose2/nose2.json -> optimise, recommended.", year="2026",
           doi_or_url="results/nose2/nose2.json", source_type="derived simulation", evidence_class="calculation", access_level="full text",
           task_or_setup="Six candidates x travel 4-8 mm x mass weight x bore 22/24 mm; duty calibrated on HW1", participants_or_bench="not applicable",
           comparator="Rev H nose (+-3 mm)", key_quantitative_findings=R.get("act103", "see nose2.json optimise"),
           units_and_conditions="mm, N/sqrt(W), g, W", locator="docs/nose_v2.md sections 4-5", limitations=R.get("act103_lim", "Lumped models; magnetic surrogate fitted to magpylib; no FEM"),
           relevance_to_design="Recommended Rev J nose", transferability="medium", transferability_reason="Model-to-model",
           design_implication=R.get("act103_impl", "see docs/nose_v2.md section 4"),
           search_query="", stream="ACT"),
        _r(id="ACT-104", topic="Autowrite in model HW1: the pen draws a known text while the hand sweeps (this study)",
           citation="This study: nose2/autowrite.py, nose2/evaluate.py; results/nose2/nose2.json -> test.", year="2026", doi_or_url="results/nose2/nose2.json",
           source_type="derived simulation", evidence_class="numerical simulation", access_level="full text",
           task_or_setup="HW1 (handwriting/, read-only) with a causal page-sensor + IMU estimator, look-ahead DP planner, axial pen-lift; test writers 0-5, seeds 200-203",
           participants_or_bench="synthetic writers", comparator="the clean target (recogniser ceiling); no axial DOF; Rev H travel",
           key_quantitative_findings=R.get("act104", "see nose2.json test"),
           units_and_conditions="um, fraction, W, letters/s", locator="docs/nose_v2.md section 5", limitations="Synthetic writers and tremor; recogniser not people; page sensor ASSUMPTION",
           relevance_to_design="Whether 'the pen writes for you' works inside the nose's reach", transferability="medium",
           transferability_reason="Model-to-model", design_implication=R.get("act104_impl", "see docs/nose_v2.md section 5"),
           search_query="", stream="ACT"),
        # ------------------------------------------------------------------ sensing and visual feedback (OPT)
        _r(id="HAP-90", topic="Perceived latency while inking with a stylus (delayed digital ink)",
           citation="Annett M, Ng A, Dietz P, Bischof WF, Gupta A. How low should we go? Understanding the perception of latency while inking. Proc Graphics Interface 2014:167-174.",
           year="2014", doi_or_url="https://webdocs.cs.ualberta.ca/~wfb/publications/C-2014-GI-Latency.pdf", source_type="conference",
           evidence_class="physical human study", access_level="full text",
           task_or_setup="High Performance Stylus System (1 ms rendering, 7 ms inking baseline); JND by PEST; line, word 'party', star; ink offset 6.5 / 65 mm; hand hidden",
           participants_or_bench="12 + 12 right-handed adults", comparator="7 ms baseline latency",
           key_quantitative_findings="JND 53 ms line drawing (range 31-76), 50 ms writing 'party' (32-87), 61 ms star (21-82); median 53 ms; hand and stylus visible: median 59 ms (33-104); hidden: 97 ms (59-105), p < 0.005; cites prior work: 1 vs 2 ms discriminable while dragging, 7 vs 40 ms not while scribbling",
           units_and_conditions="ms", locator="Sections 4.5, 5.4", limitations="Digital ink on a projected surface; perception, not acceptance",
           relevance_to_design="Delayed ink (100-200 ms) trails the hand: will writers notice?", transferability="medium",
           transferability_reason="Visual latency perception transfers; paper ink differs",
           design_implication="100-200 ms of ink delay is 2-4x the perception threshold with the hand visible: writers will see it; acceptance is untested (EXP-N08)",
           search_query="WebSearch: Annett Ng How low should we go perception of latency while inking", stream="OPT (visual feedback)"),
        _r(id="HAP-91", topic="Delayed visual feedback during handwriting: errors grow with delay",
           citation="Tamada T. Effects of delayed visual feedback on handwriting. Japanese Psychological Research 1995;37(2):103-109.", year="1995",
           doi_or_url="https://doi.org/10.4992/psycholres1954.37.103", source_type="journal", evidence_class="physical human study", access_level="abstract only",
           task_or_setup="English words written with visual feedback delayed 0, 33, 67, 100, 133, 167, 267, 500 ms", participants_or_bench="not stated in the abstract",
           comparator="0 ms", key_quantitative_findings="Writing error rate increased with delay; frequent addition errors (strokes duplicated, e.g. 'feeling' -> 'feeeling'); visual monitoring indispensable for repeating a set of strokes",
           units_and_conditions="ms", locator="Abstract", limitations="Abstract only; whole visual scene delayed (TV), not only the ink",
           relevance_to_design="Delayed ink", transferability="low", transferability_reason="Delayed-ink pens show the hand in real time; only the ink lags",
           design_implication="Delayed ink could disturb repeated strokes (m, n, u, w); test before adopting (EXP-N08)",
           search_query="WebSearch: delayed visual feedback handwriting study delay 100 ms 200 ms", stream="OPT (visual feedback)"),
        _r(id="HAP-92", topic="Delayed visual feedback on handwriting and tapping: insertion errors and larger letters",
           citation="Morikiyo Y, Matsushima T. Effects of delayed visual feedback on motor control performance. Percept Mot Skills 1990;70(1):111-114.", year="1990",
           doi_or_url="https://doi.org/10.2466/pms.1990.70.1.111", source_type="journal", evidence_class="physical human study", access_level="abstract only",
           task_or_setup="Reciprocal tapping and handwriting of Kanji and English words with delays 200-1000 ms", participants_or_bench="not stated in the abstract",
           comparator="no delay", key_quantitative_findings="Handwriting performance showed a large decrement with increasing delay; most frequent errors: insertion of line elements or letter duplication; written letters grew larger with longer delays",
           units_and_conditions="ms", locator="Abstract", limitations="Abstract only; whole visual feedback delayed",
           relevance_to_design="Delayed ink", transferability="low", transferability_reason="As HAP-91",
           design_implication="Treat delayed ink as a risk to fluency and letter size; measure with the hand visible and only the ink delayed",
           search_query="PubMed efetch 2326107", stream="OPT (visual feedback)"),
        _r(id="OPT-53", topic="3-D Hall sensor for a larger nose travel: TI TMAG5170",
           citation="Texas Instruments. TMAG5170 high-precision 3D linear Hall-effect sensor with SPI, datasheet (2021).", year="2021",
           doi_or_url="https://www.ti.com/lit/ds/symlink/tmag5170.pdf", source_type="datasheet", evidence_class="manufacturer statement", access_level="full text",
           task_or_setup="Datasheet", participants_or_bench="bench (manufacturer)", comparator="OPT-45 (TMAG5273)",
           key_quantitative_findings="Ranges +-25/50/100 mT (A1; A2 to +-300 mT); 20 kSPS single axis; sensitivity linearity error +-0.1 % (XY); XY noise 140 uT RMS typical at CONV_AVG 000 (24 uT at 101), Z 61 / 11 uT; offset +-200 uT max (25/50 mT); 3.4 mA active; 2.3-5.5 V; -40 to 150 degC",
           units_and_conditions="25 degC typical", locator="Section 6.5", limitations="SPI; field map calibration needed at large travel",
           relevance_to_design="Nose position sensing over +-6 mm (a larger field swing than Rev H's +-3 mm)", transferability="high",
           transferability_reason="Same sensing principle", design_implication="Use the +-50 mT range and a per-unit field map; noise as the TMAG5273 (OPT-45)",
           search_query="WebSearch: TMAG5170 3D Hall sensor datasheet measurement range sample rate noise", stream="OPT"),
        _r(id="OPT-54", topic="Mouse-class optical navigation sensor for the page sensor: PixArt PMW3360",
           citation="PixArt Imaging. PMW3360DM-T2QU product datasheet, optical gaming navigation sensor (rev 1.50, 2016).", year="2016",
           doi_or_url="https://www.epsglobal.com/Media-Library/EPSGlobal/Products/files/pixart/PMW3360DM-T2QU.pdf", source_type="datasheet",
           evidence_class="manufacturer statement", access_level="full text", task_or_setup="Datasheet with LM19-LSI lens", participants_or_bench="bench (manufacturer)",
           comparator="AMF-153 (PAA5100JE), OPT-02 (DeltaPen)",
           key_quantitative_findings="Up to 12000 frames/s; 250 in/s (6.35 m/s) typical; 50 g; up to 12000 cpi (about 2.1 um per count); resolution error 1 % typical; lens reference plane 2.2-2.6 mm (2.4 nominal) from the surface; lift cut-off 2 or 3 mm; 16.3-18.6 mA",
           units_and_conditions="1.9 V", locator="Pages 1, 14-16", limitations="Needs a flat lens parallel to the surface at 2.4 mm; the pen tilts 35-75 deg",
           relevance_to_design="Autowrite depends on a fast page sensor (1 kHz, 2 ms assumed)", transferability="medium",
           transferability_reason="Frame rate and resolution meet the assumption; the mounting does not (tilt)",
           design_implication="Mount the sensor in a gimballed foot on the skid ring or accept a tilted optical path; EXP-N06 must confirm 1 kHz / 2 ms / <= 5 um on paper at 35-75 deg",
           search_query="WebSearch: PMW3360 datasheet frame rate lift-off distance max speed CPI", stream="OPT"),
        # ------------------------------------------------------------------ patents (PAT)
        _r(id="PAT-40", topic="Guided tool with a coarse and a fine positioning system (Shaper Tools)",
           citation="Shaper Tools Inc (inventors Hebenstreit JJ, Moyer IE, Blum JE, Rivers AR). Systems, methods and apparatus for guided tools with multiple positioning systems. US 2021/0034032 A1, published 2021-02-04; granted 2023-03-21 (as displayed).",
           year="2021", doi_or_url="https://patents.google.com/patent/US20210034032A1/en", source_type="patent", evidence_class="patent disclosure",
           access_level="patent page (Google Patents summary)", task_or_setup="Claims and description", participants_or_bench="not applicable", comparator="PAT-10",
           key_quantitative_findings="Claim 1: a first (fine) positioning system with a frame moving a working member over a small region; a second (coarse) system positioning the frame over a large region with less accuracy; a controller moving the second system to keep target points within the first system's region. Description: fine range 0.5 in (about 12.7 mm), accuracy +-0.01 in; coarse +-0.25 in; z-position by force sensing on the tool base. Status displayed: active to 2039-01-29",
           units_and_conditions="Patent", locator="Claim 1; description", limitations="Summary tool read; attorney must read the granted claims",
           relevance_to_design="Candidate 3 (coarse-fine) and the autowrite split (hand = coarse, nose = fine)", transferability="high",
           transferability_reason="Claim language is general", design_implication="FTO item for autowrite: in the pen the coarse system is the human hand (not a motorised stage); record this for the attorney",
           search_query="WebSearch: Shaper Tools patent Systems methods and apparatus for guided tools", stream="PAT"),
        _r(id="PAT-41", topic="Plotter pen lift by solenoid: high-speed pen up/down (CalComp)",
           citation="California Computer Products Inc (inventors Klassen FE, Miller DG). High speed pen actuating mechanism. US 3,340,541 A, filed 1965-01-18, published 1967-09-05. Expired.",
           year="1967", doi_or_url="https://patents.google.com/patent/US3340541A/en", source_type="patent", evidence_class="patent disclosure",
           access_level="patent page", task_or_setup="Claims and description", participants_or_bench="not applicable", comparator="AMF-145",
           key_quantitative_findings="Solenoid plunger with an annular pole piece lifts the pen; a pen-pressure spring of about 7 g presses it down; axial movement 0.020-0.025 in (0.5-0.64 mm) at 40-50 Z pulses per second; air gap < 0.050 in for fast response",
           units_and_conditions="Patent description", locator="Description", limitations="Plotter, not handheld",
           relevance_to_design="Candidate 5: the pen's own pen-up/down", transferability="medium", transferability_reason="Same function at pen scale",
           design_implication="A 0.5 mm refill lift at >= 40 switches/s is established (expired) art; the pen needs a low-power latch variant",
           search_query="WebSearch: patent pen plotter pen lift solenoid mechanism fast pen up down", stream="PAT"),
        _r(id="PAT-42", topic="Voice-coil actuator for angular movements with arc-shaped magnets (constant gap under rotation) (Thorlabs)",
           citation="Thorlabs GmbH (inventors Boehme T, Krause E, Baumhackl SMF). Voice coil actuator for angular movements. US 11,960,143 B2, granted 2024-04-16; priority 2019-11-13.",
           year="2024", doi_or_url="https://patents.google.com/patent/US11960143B2/en", source_type="patent", evidence_class="patent disclosure",
           access_level="patent page (Google Patents summary)", task_or_setup="Claims and description", participants_or_bench="not applicable", comparator="PAT-43",
           key_quantitative_findings="Two plates on a pivot joint; a pair of voice-coil actuators per axis at equal and opposite distances; each magnet structure conforms to an arc centred on the rotation axis; segmented coils switched by magnet position; +-8 deg per axis; net force on the pivot about zero at all tilts; active, expires 2042-12-11 (as displayed)",
           units_and_conditions="Patent", locator="Claim 1", limitations="Summary read; tip-tilt mirror mounts",
           relevance_to_design="The constant-gap (spherical) actuator variant gimbal_sphere", transferability="high", transferability_reason="Same geometry idea",
           design_implication="FTO item if the spherical-gap actuator is chosen; the recommended flat-coil pole-pair design avoids arc magnets",
           search_query="WebSearch: patent two-axis tilt actuator moving magnet coils fast steering mirror flexure gimbal voice coil", stream="PAT"),
        _r(id="PAT-43", topic="Dual-axis flexure gimbal with four voice coils for tip-tilt (Raytheon)",
           citation="Raytheon Co (inventors Gallagher JM, Ready R, Fierro E). Dual-axis flexure gimbal device. US 11,441,598 B2, granted 2022-09-13; priority 2018-12-20.",
           year="2022", doi_or_url="https://patents.google.com/patent/US11441598B2/en", source_type="patent", evidence_class="patent disclosure",
           access_level="patent page (Google Patents summary)", task_or_setup="Claims and description", participants_or_bench="not applicable", comparator="PAT-12, PAT-08",
           key_quantitative_findings="Claim 1: a flexure spring-mass body with two sections joined by a diaphragm with a central aperture, and a cylindrical flexure unit in the aperture with four slots forming flexures for x/y rotation while restricting other motions; four voice coils tip/tilt the moving section; 'a few degrees' (e.g. 0.5 deg for image stabilisation); active, expires 2040-12-19 (as displayed)",
           units_and_conditions="Patent", locator="Claim 1", limitations="Summary read; optical use",
           relevance_to_design="Rev H and Rev J noses (flexure gimbal + four voice coils)", transferability="medium",
           transferability_reason="Structure similar; the claim's slotted-cylinder flexure differs from cross-strip flexures",
           design_implication="Add to the Rev H FTO list with PAT-12 and PAT-08; the attorney should compare the claim's slotted cylinder and diaphragm with the cross-strip gimbal",
           search_query="WebSearch: patent two-axis tilt actuator ... flexure gimbal voice coil", stream="PAT"),
        _r(id="PAT-44", topic="Hand-held printer that prints while moved freehand, tracked by optical navigation sensors (HP)",
           citation="Hewlett-Packard Co (inventor Yamada N). Handy printer system. US 5,927,872 A, granted 1999-07-27; priority 1997-08-08. Expired.",
           year="1999", doi_or_url="https://patents.google.com/patent/US5927872A/en", source_type="patent", evidence_class="patent disclosure",
           access_level="patent page", task_or_setup="Claims and description", participants_or_bench="not applicable", comparator="AMF-149, PAT-24",
           key_quantitative_findings="Optical sensors image the print medium's surface features to generate navigation data; a navigation processor maps image data to positions and deposits ink segments as the user moves the device freely (non-linear motion); four sensors, 32 x 64 pixel arrays with a 24 x 56 reference frame; 600 dpi; about 50 us sampling at 0.45 m/s",
           units_and_conditions="Patent", locator="Claim 1; description", limitations="Inkjet; expired",
           relevance_to_design="Prior art for autowrite (device lays text where it is while the hand sweeps, using surface-feature navigation)", transferability="high",
           transferability_reason="Same principle", design_implication="Expired prior art supporting novelty/FTO arguments for autowrite with page-sensor navigation",
           search_query="WebSearch: patent hand-held printer navigation sensor prints image while moved freehand", stream="PAT"),
    ]
    # the same sources were read by studies D and L; the ledger keeps their rows under these ids (lead, 2026-09-29)
    out = [r for r in out if r["id"] not in SHARED_WITH_OTHER_STUDIES]
    return out


def write(path: str, results: Dict = None) -> int:
    rs = rows(results)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=HEADER)
        w.writeheader()
        for r in rs:
            w.writerow(r)
    return len(rs)
