#!/usr/bin/env python3
r"""Export the int8 TCN to C and verify it.

Where: the exported model (common.EXPORT_MODEL = tcn_s_nofest; contract v1.1, inputs dp_x,
dp_y) is written to ml/export/.  Any other model (e.g. --model tcn_s: contract v1.0 with the
f_est channel) is exported out of tree to ml/runs/export_<model>/ (git-ignored; the hand-
written sources are copied next to its generated headers), so reproducing it never
overwrites the committed artefact.  The input channel count (TCN_CIN = 2 or 3) comes from
the quantised model's config; tcn_int8.c and test_host.c are the same for both.
1. tcn_model.h     generated model identity and shape: TCN_CIN, name, hash, scratch size
                   (included by tcn_int8.h)
2. tcn_weights.h   generated weights, biases, requantisation parameters (tcn_int8.c only)
3. test_vectors.h  64 int8 windows + 32 float windows (test writers) with the Python
                   integer reference outputs, and requantisation unit cases
4. host test: gcc -O2 -Werror (and clang UBSan, trap mode) builds of tcn_int8.c +
   test_host.c; also a 20 000-window binary file from the test writers (ml/runs/, git-ignored)
5. arm-none-eabi-gcc -mcpu=cortex-m33 -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -O2
   compile of tcn_int8.c, section sizes (arm-none-eabi-size -A), -Os for comparison
6. optional: the same test program on an emulated Cortex-M33 (QEMU mps2-an505, semihosting),
   bit-exactness on the target ISA and an executed-instruction count (-icount + SysTick,
   calibrated with a 2-instruction loop).  QEMU is not cycle accurate.
Output: results/ml/export_c.json (exported model) or results/ml/export_c_<model>.json.
Run: python3 -m ml.export_c [--model tcn_s_nofest]      (python3 -m ml.export_c --model tcn_s)
Evidence status: the model is trained on SIMULATION / synthetic data.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import time

import numpy as np

from . import common as C
from . import datasets as D
from . import models as M
from . import quantize as Q

BUILD = os.path.join(C.RUNS, "export_build")        # build dir of the exported model (ml/export/)
ARM_FLAGS = ["-mcpu=cortex-m33", "-mfpu=fpv5-sp-d16", "-mfloat-abi=hard", "-mthumb"]
COMMON_CFLAGS = ["-std=c99", "-ffp-contract=off", "-Wall", "-Wextra", "-Wpedantic", "-Werror"]
HAND_WRITTEN = ("tcn_int8.h", "tcn_int8.c", "test_host.c", os.path.join("qemu", "startup_m33.c"),
                os.path.join("qemu", "an505.ld"))
CONTRACT = {2: "docs/icd.md s5 contract v1.1: no f_est input", 3: "docs/icd.md s5 contract v1.0: f_est input channel"}


def export_dirs(model):
    """(directory of sources + generated headers, build directory) for a model."""
    if model == C.EXPORT_MODEL:
        return C.EXPORT, BUILD
    d = os.path.join(C.RUNS, f"export_{model}")
    return d, os.path.join(d, "build")


def _fmt_f32(v):
    return np.format_float_positional(np.float32(v), unique=True, trim="0") + "f"


def _nested(a, fmt, per_line, indent):
    if a.ndim == 1:
        items = [fmt(x) for x in a]
        rows = [", ".join(items[i:i + per_line]) for i in range(0, len(items), per_line)]
        if len(rows) <= 1:
            return "{" + (rows[0] if rows else "") + "}"
        pad = " " * (indent + 4)
        return "{\n" + pad + (",\n" + pad).join(rows) + "\n" + " " * indent + "}"
    pad = " " * (indent + 4)
    return "{\n" + pad + (",\n" + pad).join(_nested(x, fmt, per_line, indent + 4) for x in a) + "\n" + " " * indent + "}"


def c_array(name, arr, ctype, per_line=20, fmt=str):
    """C initialiser with nested braces for multi-dimensional arrays (-Wmissing-braces clean)."""
    a = np.asarray(arr)
    shape = "".join(f"[{d}]" for d in a.shape)
    return f"static const {ctype} {name}{shape} = {_nested(a, fmt, per_line, 0)};\n"


def folded_bias(L):
    """bias + in_offset * row sums of W (exact integer identity used by the plain-C kernel)."""
    fb = L["b"].astype(np.int64) + int(L["in_offset"]) * L["w"].astype(np.int64).sum(axis=1)
    assert np.all(np.abs(fb) < 2 ** 31)
    return fb.astype(np.int64)


def scratch_sizes(qm):
    outs = []
    L = C.W
    for Ly in qm["layers"][:6]:
        L //= 2
        outs.append(L * Ly["c_out"])
    head = qm["layers"][6]["c_out"]
    a = max(outs[0], outs[2], outs[4], head)
    b = max(outs[1], outs[3], outs[5])
    return a, b


def gen_model_header(qm, name, path):
    """Public, model-dependent constants; included by tcn_int8.h (no data)."""
    c_in = Q.qm_c_in(qm)
    hs = qm["hash"]
    lines = [
        "/*",
        " * tcn_model.h - GENERATED by ml/export_c.py; do not edit.",
        " * EVIDENCE STATUS: SIMULATION / synthetic data.  Trained only on synthetic handwriting and",
        " * synthetic tremor; never validated on a person.  See ml/model_card.md.",
        f" * model: {name}  inputs per sample: {', '.join(M.input_names(c_in))}  ({CONTRACT[c_in]})",
        f" * sha256(quantised parameters) = {hs}",
        " * Included by tcn_int8.h.  The parameters are in tcn_weights.h (included by tcn_int8.c only).",
        " */",
        "#ifndef TCN_MODEL_H",
        "#define TCN_MODEL_H",
        "",
        f"#define TCN_MODEL_NAME \"{name}\"",
        f"#define TCN_CIN {c_in}   /* input channels per sample: {', '.join(M.input_names(c_in))} */",
        f"#define TCN_MODEL_HASH_LOW32 0x{hs[-8:]}u   /* event 0x0005 argument */",
        f"#define TCN_SCRATCH_BYTES {sum(scratch_sizes(qm))}   /* = tcn_scratch_bytes() */",
        "",
        "#endif /* TCN_MODEL_H */",
        "",
    ]
    with open(path, "w") as f:
        f.write("\n".join(lines))


def gen_weights_header(qm, name, path):
    a, b = scratch_sizes(qm)
    hs = qm["hash"]
    c_in = Q.qm_c_in(qm)
    lines = [
        "/*",
        " * tcn_weights.h - GENERATED by ml/export_c.py; do not edit.  Included by tcn_int8.c only.",
        " * EVIDENCE STATUS: SIMULATION / synthetic data.  Trained only on synthetic handwriting and",
        " * synthetic tremor; never validated on a person.  See ml/model_card.md.",
        f" * model: {name}  arch: {qm['arch']['channels']} head {qm['arch']['head']}  "
        f"inputs: {', '.join(M.input_names(c_in))}  calibration: {qm['calib']}",
        f" * sha256(quantised parameters) = {hs}",
        " */",
        "#ifndef TCN_WEIGHTS_H",
        "#define TCN_WEIGHTS_H",
        "",
        f"#if TCN_CIN != {c_in} || TCN_MODEL_HASH_LOW32 != 0x{hs[-8:]}u || TCN_SCRATCH_BYTES != {a + b}",
        "#error \"tcn_weights.h and tcn_model.h come from different exports\"",
        "#endif",
        "",
        f"#define TCN_IN_INV_SCALE {_fmt_f32(qm['in_inv_scale'])}   /* LSB per um of dp */",
    ]
    if c_in == 3:
        lines += [f"#define TCN_F_INV_SCALE {_fmt_f32(qm['f_inv_scale'])}   /* LSB per Hz of f_est */",
                  f"#define TCN_F_REF_HZ {_fmt_f32(qm['f_ref_hz'])}"]
    lines += [
        f"#define TCN_OUT_LSB_UM {_fmt_f32(qm['out']['out_lsb_um'])}",
        f"#define TCN_SCRATCH_A {a}",
        f"#define TCN_SCRATCH_B {b}",
        "",
    ]
    for i, L in enumerate(qm["layers"]):
        lines.append(c_array(f"TCN_L{i}_W", L["w"], "int8_t"))
        lines.append(c_array(f"TCN_L{i}_B", L["b"], "int32_t", per_line=8))
        lines.append(c_array(f"TCN_L{i}_BF", folded_bias(L), "int32_t", per_line=8))
    O = qm["out"]
    lines.append(c_array("TCN_OUT_W", O["w"].ravel(), "int8_t"))
    lines.append(c_array("TCN_OUT_B", O["b"], "int32_t", per_line=8))
    lines.append(c_array("TCN_OUT_BF", folded_bias(O), "int32_t", per_line=8))
    lines += [f"#define TCN_OUT_N_IN {O['c_in']}", f"#define TCN_OUT_IN_OFFSET ({O['in_offset']})",
              f"#define TCN_OUT_MULT ({O['mult']})", f"#define TCN_OUT_SHIFT ({O['shift']})", ""]

    def params(i, L):
        return (f"{{TCN_L{i}_W[0], TCN_L{i}_B, TCN_L{i}_BF, {L['w'].shape[1]}, {L['c_out']}, {L['in_offset']}, {L['out_zp']}, "
                f"{L['mult']}, {L['shift']}, {L['act_min']}, {L['act_max']}}}")
    lines.append("static const tcn_fc_params_t TCN_LEVELS[TCN_NLEVELS] = {\n    " +
                 ",\n    ".join(params(i, L) for i, L in enumerate(qm["layers"][:6])) + "\n};\n")
    lines.append(f"static const tcn_fc_params_t TCN_HEAD = {params(6, qm['layers'][6])};\n")
    lines.append("#endif /* TCN_WEIGHTS_H */\n")
    with open(path, "w") as f:
        f.write("\n".join(lines))


def pick_ticks(recs, rng, n):
    """Stratified scored ticks: tremor, no tremor, fast strokes (clipped input), pen up."""
    pools = {"tremor": [], "no_tremor": [], "fast": [], "pen_up": []}
    for ri, r in enumerate(recs):
        ok = (r["t"] >= C.WARMUP_S) & (np.arange(len(r["t"])) >= C.W - 1)
        fast = np.max(np.abs(r["dp_um"]), axis=1) > C.IN_CLIP_UM
        for k in np.flatnonzero(ok & r["pen_tgt"] & (r["env_tgt"] > 0))[::97]:
            pools["tremor"].append((ri, k))
        for k in np.flatnonzero(ok & r["pen_tgt"] & (r["env_tgt"] == 0))[::97]:
            pools["no_tremor"].append((ri, k))
        for k in np.flatnonzero(ok & fast):
            pools["fast"].append((ri, k))
        for k in np.flatnonzero(ok & ~r["pen_tgt"])[::97]:
            pools["pen_up"].append((ri, k))
    share = {"tremor": 0.4, "no_tremor": 0.3, "fast": 0.15, "pen_up": 0.15}
    out = []
    for k, frac in share.items():
        p = pools[k]
        m = min(len(p), int(round(frac * n)))
        if m:
            out += [p[i] for i in rng.choice(len(p), m, replace=False)]
    while len(out) < n:
        p = pools["tremor"]
        out.append(p[rng.integers(len(p))])
    return out[:n]


def gen_test_vectors(qm, recs, path, bin_path, seed=3, n_int=64, n_f=32, n_bin=20000):
    c_in = Q.qm_c_in(qm)
    hash_low32 = int(qm["hash"][-8:], 16)
    rng = np.random.default_rng(seed)
    qwin = {}

    def win(ri):
        if ri not in qwin:
            qwin[ri] = Q.int_windows(Q.quantize_inputs(recs[ri]["dp_um"], recs[ri]["f_est"], c_in))
        return qwin[ri]
    ti = pick_ticks(recs, rng, n_int)
    xin = np.stack([win(ri)[k] for ri, k in ti])
    yin = Q.run_int8(qm, xin)
    tf = pick_ticks(recs, np.random.default_rng(seed + 1), n_f)
    fdp = np.stack([recs[ri]["dp_um"][k - C.W + 1:k + 1] for ri, k in tf]).astype(np.float32)
    # f_est of each float window: an input of the float API only when c_in == 3 (ignored by 2-channel models)
    ffe = np.array([recs[ri]["f_est"][k] for ri, k in tf], np.float32)
    xf = np.stack([Q.int_windows(Q.quantize_inputs(fdp[i], np.full(C.W, ffe[i], np.float32), c_in))[-1]
                   for i in range(n_f)])
    yf = Q.run_int8(qm, xf)
    rq = []
    r2 = np.random.default_rng(seed + 2)
    for _ in range(96):
        shift = int(r2.integers(-24, 3))
        mult = int(r2.integers(1 << 30, (1 << 31) - 1))
        lim = (1 << 30) >> max(shift, 0)
        v = int(r2.integers(-lim, lim))
        rq.append([v, mult, shift, int(Q.requantize(np.array([v], np.int64), mult, shift)[0])])
    for v, m, s in ((0, 1 << 30, -1), (-1, 1 << 30, -1), (1, 1 << 30, -1), (-3, 1 << 30, -1), (3, 1 << 30, -1),
                    (2 ** 30 - 1, 2 ** 31 - 1, 0), (-(2 ** 30), 2 ** 31 - 1, 0), (12345, 1518500250, -7)):
        rq.append([v, m, s, int(Q.requantize(np.array([v], np.int64), m, s)[0])])
    rq = np.array(rq, np.int64)
    lines = ["/* test_vectors.h - GENERATED by ml/export_c.py from TEST writers (SIMULATION / synthetic data). */",
             "#ifndef TCN_TEST_VECTORS_H", "#define TCN_TEST_VECTORS_H", "#include <stdint.h>",
             f"#define TV_CIN {c_in}", f"#define TV_MODEL_HASH_LOW32 0x{qm['hash'][-8:]}u",
             f"#define TV_N_INT {n_int}", f"#define TV_N_F {n_f}", f"#define TV_N_RQ {len(rq)}", "",
             c_array("tv_int_in", xin, "int8_t", per_line=24), c_array("tv_int_out", yin, "int16_t", per_line=8),
             c_array("tv_f_dp", fdp, "float", per_line=8, fmt=_fmt_f32),
             c_array("tv_f_fest", ffe, "float", per_line=8, fmt=_fmt_f32),
             c_array("tv_f_out", yf, "int16_t", per_line=8),
             c_array("tv_rq", rq.astype(np.int64), "int32_t", per_line=4,
                     fmt=lambda x: str(int(x)) if int(x) != -(2 ** 31) else "(-2147483647 - 1)"),
             "#endif", ""]
    with open(path, "w") as f:
        f.write("\n".join(lines))
    # large binary set (host only)
    tb = []
    for ri, r in enumerate(recs):
        ok = np.flatnonzero((r["t"] >= C.WARMUP_S) & (np.arange(len(r["t"])) >= C.W - 1))
        tb += [(ri, k) for k in ok]
    sel = np.random.default_rng(seed + 3).choice(len(tb), n_bin, replace=False)
    xb = np.stack([win(tb[i][0])[tb[i][1]] for i in sel])
    yb = Q.run_int8(qm, xb)
    with open(bin_path, "wb") as f:           # "TCNV", u32 N, u32 c_in, u32 hash_low32, N x (int8[64][c_in], int16[2])
        f.write(b"TCNV")
        f.write(np.array([n_bin, c_in, hash_low32], "<u4").tobytes())
        for i in range(n_bin):
            f.write(xb[i].astype(np.int8).tobytes())
            f.write(yb[i].astype("<i2").tobytes())
    return {"n_int": n_int, "n_float": n_f, "n_requant": int(len(rq)), "n_binary": n_bin, "c_in": c_in,
            "int_out_range_01um": [int(yin.min()), int(yin.max())]}


def run(cmd, timeout=300, **kw):
    p = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout, **kw)
    return p.returncode, p.stdout + p.stderr


def parse_test(out):
    res = {}
    for line in out.splitlines():
        m = re.match(r"(\w+) (.*)", line.strip())
        if not m:
            continue
        kv = dict(re.findall(r"(\w+)=(\S+)", m.group(2)))
        if kv:
            res[m.group(1)] = kv
        elif m.group(1) == "RESULT":
            res["RESULT"] = m.group(2)
    return res


def arm_sizes(obj):
    rc, out = run(["arm-none-eabi-size", "-A", obj])
    sec = {}
    for line in out.splitlines():
        parts = line.split()
        if len(parts) >= 2 and parts[0].startswith(".") and parts[1].isdigit():
            sec[parts[0]] = int(parts[1])
    return sec


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default=C.EXPORT_MODEL)
    ap.add_argument("--no-qemu", action="store_true")
    args = ap.parse_args()
    t0 = time.time()
    src_dir, build = export_dirs(args.model)
    os.makedirs(build, exist_ok=True)
    if src_dir != C.EXPORT:                   # out-of-tree export: same hand-written sources, own headers
        os.makedirs(os.path.join(src_dir, "qemu"), exist_ok=True)
        for f in HAND_WRITTEN:
            shutil.copy2(os.path.join(C.EXPORT, f), os.path.join(src_dir, f))
    qm = Q.load_qmodel(os.path.join(C.RESULTS, "model", f"{args.model}_int8.npz"))
    c_in = Q.qm_c_in(qm)
    mh = os.path.join(src_dir, "tcn_model.h")
    hdr = os.path.join(src_dir, "tcn_weights.h")
    tvh = os.path.join(src_dir, "test_vectors.h")
    binp = os.path.join(build, "vectors_test_20000.bin")
    gen_model_header(qm, args.model, mh)
    gen_weights_header(qm, args.model, hdr)
    test = D.load_split("test")
    tv = gen_test_vectors(qm, test, tvh, binp)
    res = {"model": args.model, "c_in": c_in, "inputs": M.input_names(c_in), "icd_contract": CONTRACT[c_in],
           "export_dir": C.rpath(src_dir), "hash_sha256": qm["hash"], "hash_low32_hex": f"0x{qm['hash'][-8:]}",
           "test_vectors": tv, "generated": [C.rpath(mh), C.rpath(hdr), C.rpath(tvh)],
           "scratch_bytes": int(sum(scratch_sizes(qm))), "input_window_int8_B": C.W * c_in}
    srcs = [os.path.join(src_dir, "tcn_int8.c"), os.path.join(src_dir, "test_host.c")]
    # ---- host gcc
    exe = os.path.join(build, "test_host")
    cmd = ["gcc", "-O2", *COMMON_CFLAGS, "-I", src_dir, *srcs, "-lm", "-o", exe]
    rc, out = run(cmd)
    host = {"compiler": run(["gcc", "--version"])[1].splitlines()[0], "cmd": " ".join(cmd[:-2] + ["-o", "test_host"]),
            "build_rc": rc}
    if rc == 0:
        rc2, out2 = run([exe, binp])
        host.update({"run_rc": rc2, "parsed": parse_test(out2), "stdout": out2})
    else:
        host["build_log"] = out
    res["host_gcc"] = host
    print("host gcc:", host.get("parsed", host.get("build_log")), flush=True)
    # ---- host clang + sanitizers
    if shutil.which("clang"):
        exe2 = os.path.join(build, "test_host_ubsan")
        # trap mode: any undefined behaviour (signed overflow, bad shift, out-of-bounds index with a
        # known bound, ...) aborts with SIGILL; no sanitizer runtime library is needed
        cmd = ["clang", "-O1", "-g", "-fsanitize=undefined", "-fsanitize-trap=undefined", *COMMON_CFLAGS,
               "-I", src_dir, *srcs, "-lm", "-o", exe2]
        rc, out = run(cmd)
        san = {"cmd": "clang -O1 -fsanitize=undefined -fsanitize-trap=undefined ...", "build_rc": rc}
        if rc == 0:
            rc2, out2 = run([exe2, binp], timeout=600)
            san.update({"run_rc": rc2, "parsed": parse_test(out2)})
        else:
            san["build_log"] = out
        res["host_clang_sanitizers"] = san
        print("clang ubsan/asan:", san.get("parsed", san.get("build_log")), flush=True)
    # ---- ARM Cortex-M33 compile + size
    arm = {"compiler": run(["arm-none-eabi-gcc", "--version"])[1].splitlines()[0], "flags": {}, "sections": {}}
    for opt in ("-O2", "-Os"):
        obj = os.path.join(build, f"tcn_int8_m33{opt}.o")
        cmd = ["arm-none-eabi-gcc", *ARM_FLAGS, opt, *COMMON_CFLAGS, "-ffunction-sections", "-fdata-sections",
               "-I", src_dir, "-c", srcs[0], "-o", obj]
        rc, out = run(cmd)
        arm["flags"][opt] = " ".join(cmd[:-2])
        if rc != 0:
            arm["sections"][opt] = {"build_log": out}
            continue
        sec = arm_sizes(obj)
        code = sum(v for k, v in sec.items() if k.startswith(".text"))
        ro = sum(v for k, v in sec.items() if k.startswith(".rodata"))
        data = sum(v for k, v in sec.items() if k.startswith(".data"))
        bss = sum(v for k, v in sec.items() if k.startswith(".bss"))
        arm["sections"][opt] = {"text_code_B": code, "rodata_B": ro, "data_B": data, "bss_B": bss,
                                "flash_total_B": code + ro + data, "detail": sec}
        _, dis = run(["arm-none-eabi-objdump", "-d", "--no-show-raw-insn", obj])
        with open(os.path.join(build, f"tcn_int8_m33{opt}.dis"), "w") as f:
            f.write(dis)
    res["arm_m33"] = arm
    print("arm:", {k: {kk: vv for kk, vv in v.items() if kk != "detail"} for k, v in arm["sections"].items()}, flush=True)
    # ---- QEMU Cortex-M33 (AN505) run
    if not args.no_qemu and shutil.which("qemu-system-arm"):
        elf = os.path.join(build, "test_m33.elf")
        cmd = ["arm-none-eabi-gcc", *ARM_FLAGS, "-O2", "-std=c99", "-ffp-contract=off", "-DTCN_BAREMETAL", "-I", src_dir,
               *srcs, os.path.join(src_dir, "qemu", "startup_m33.c"), "-T", os.path.join(src_dir, "qemu", "an505.ld"),
               "-nostartfiles", "--specs=nano.specs", "--specs=rdimon.specs", "-lm", "-o", elf]
        rc, out = run(cmd)
        qe = {"build_rc": rc, "machine": "mps2-an505 (Cortex-M33)", "qemu": run(["qemu-system-arm", "--version"])[1].splitlines()[0]}
        if rc == 0:
            for shift in (0,):
                qcmd = ["qemu-system-arm", "-M", "mps2-an505", "-nographic", "-monitor", "none", "-serial", "none",
                        "-semihosting-config", "enable=on,target=native", "-icount", f"shift={shift}", "-kernel", elf]
                try:
                    rc2, out2 = run(qcmd, timeout=180)
                except subprocess.TimeoutExpired:
                    rc2, out2 = -9, "timeout"
                p = parse_test(out2)
                qe.update({"run_rc": rc2, "cmd": " ".join(qcmd[:-1] + ["test_m33.elf"]), "parsed": p, "stdout": out2[-2000:]})
                try:
                    ticks = int(p["bench"]["systick_ticks"])
                    reps = int(p["bench"]["reps"])
                    cal_i = int(p["calib"]["loop_instructions"])
                    cal_t = int(p["calib"]["systick_ticks"])
                    qe["instructions_per_inference"] = ticks / reps * cal_i / cal_t
                except Exception as e:  # noqa: BLE001
                    qe["instr_error"] = str(e)
        else:
            qe["build_log"] = out[-3000:]
        res["qemu_m33"] = qe
        print("qemu:", {k: v for k, v in qe.items() if k not in ("stdout", "build_log")}, flush=True)
    res["meta"] = C.meta(extra={"elapsed_s": time.time() - t0})
    txt = json.dumps(res, indent=2, default=str).replace(C.ROOT + "/", "")
    out = C.result_json("export_c", args.model)
    with open(out, "w") as f:
        f.write(txt)
    print(f"wrote {C.rpath(out)}; done {time.time() - t0:.0f} s", flush=True)


if __name__ == "__main__":
    main()
