"""Proposed evidence-ledger rows of study D (results/drive/evidence_rows.csv; 23-column header of docs/evidence.csv).

Every row is a source that was actually opened in this study (full text, a manufacturer page or datasheet, or an
abstract, as `access_level` says).  Ids: HAP-60..79, AMF-100..119, CON-36..45, PAT-30..34.  Retrieved 2026-09-28.
"""
from __future__ import annotations

import csv
from pathlib import Path

from . import REPO_ROOT

HEADER = ["id", "topic", "citation", "year", "doi_or_url", "source_type", "evidence_class", "access_level", "task_or_setup",
          "participants_or_bench", "comparator", "key_quantitative_findings", "units_and_conditions", "locator",
          "limitations", "relevance_to_design", "transferability", "transferability_reason", "design_implication",
          "retrieved", "search_query", "stream", "lead_verification"]
R = "2026-09-28"


def _row(**k):
    d = {h: "" for h in HEADER}
    d.update(k)
    d.setdefault("retrieved", R)
    d["retrieved"] = d["retrieved"] or R
    d["stream"] = d["id"].split("-")[0]
    return d


ROWS = [
    # ------------------------------------------------------------------ HAP: guidance, cobots, handheld robots, damping
    _row(id="HAP-60", topic="Cobots: steered, non-driven wheels create virtual paths with almost no power (unicycle, scooter)",
         citation="Peshkin MA, Colgate JE, Wannasuphoprasit W, Moore CA, Gillespie RB, Akella P. Cobot architecture. IEEE Trans Robot Autom. 2001;17(4):377-390.",
         year="2001", doi_or_url="10.1109/70.954751 ; https://public.websites.umich.edu/~brentg/Publications/Journal/PeshkinTROCobotArchitecture.pdf",
         source_type="journal", evidence_class="physical bench experiment", access_level="full text",
         task_or_setup="Unicycle cobot: one free-rolling Rollerblade wheel, steering motor, no caster (steering axis through the contact point), force sensor at the handle; path mode (bilateral virtual surface) and free mode (steering nulls the operator's perpendicular force, eq. 2); Scooter: three steered wheels",
         participants_or_bench="Prototypes; operator trajectories shown (Fig. 3); no controlled user study with statistics",
         comparator="Brakes (joint brakes cannot render smooth arbitrary surfaces and dissipate energy); powered backdrivable robots",
         key_quantitative_findings="'Virtual surface strength well over 100 pounds is attainable'; free mode 'qualitatively isotropic' 'at speeds of a few cm/s or faster'; 'noticeable hesitation as the wheels reorient' after a standstill; Scooter: speeds up to about 2 m/s comfortable; unrestricted steering angle found important (encoder wire wind-up).",
         units_and_conditions="Rollerblade wheels on a floor; payloads of several hundred pounds",
         locator="Sec. I.C (brakes), Sec. II.A-B and Fig. 1-3 (unicycle, eq. 1-2), Sec. III.A (Scooter)",
         limitations="Floor-scale devices; no handwriting; strength set by the wheel's skid limit, which is small for a pen (mu x 0.5 N)",
         relevance_to_design="The principle of the steered heel wheel: across-path force by the tyre's grip, along-path free; free mode by steering toward the writer's push; passive by construction",
         transferability="medium", transferability_reason="Same kinematics and control laws; the skid limit and steering dynamics scale down with the pen",
         design_implication="Steer the heel wheel through its contact point; free mode by lateral-force nulling; expect hesitation at stroke starts and corners",
         search_query="WebSearch: Peshkin Colgate Cobot architecture IEEE Transactions 2001 pdf"),
    _row(id="HAP-61", topic="Position-correcting handheld tool: the user moves a frame coarsely, a stage moves the tool within 1/4 inch",
         citation="Rivers A, Moyer IE, Durand F. Position-correcting tools for 2D digital fabrication. ACM Trans Graph (SIGGRAPH). 2012;31(4):88.",
         year="2012", doi_or_url="10.1145/2185520.2185584 ; https://groups.csail.mit.edu/graphics/positioncorrectingtools/",
         source_type="journal", evidence_class="physical bench experiment", access_level="full text",
         task_or_setup="Handheld router/vinyl cutter/pen plotter; camera localisation on a marker map; eccentric-cam stage moves the tool; constant-speed and freeform path strategies",
         participants_or_bench="Device demonstrations and one plotted accuracy test",
         comparator="Unaided freehand positioning",
         key_quantitative_findings="With location information a user keeps the tool within 1/8 in of the plan; stage range set to correct errors up to 1/4 in (1/2 in circle); plotted pattern (6 in wide): mean error 0.009 in, max 0.023 in.",
         units_and_conditions="inch; pen as the tool for the accuracy test",
         locator="Sec. 4.1 (range), Sec. 6 and Fig. 10 (accuracy)",
         limitations="Not grounded force on the hand; the tool moves relative to the frame (like the Rev H nose); no user statistics",
         relevance_to_design="Macro-mini division: the hand (or the heel drive) does the gross path, a short-range stage (the nose) the detail",
         transferability="medium", transferability_reason="Same division of labour; different scale and task",
         design_implication="Pair the heel drive (gross, grounded) with the nose (fine, +/-3 mm)",
         search_query="WebSearch: Rivers Moyer Durand Position-correcting tools pdf"),
    _row(id="HAP-62", topic="Handheld robots: users' frustration when the tool acts against their intention ('rebellion') versus obedience",
         citation="Stolzenwald J, Mayol-Cuevas WW. Rebellion and obedience: the effects of intention prediction in cooperative handheld robots. arXiv:1903.08158 (IROS 2019).",
         year="2019", doi_or_url="https://arxiv.org/abs/1903.08158",
         source_type="conference", evidence_class="physical human study", access_level="full text",
         task_or_setup="Handheld robot (lineage: 4-DoF then 6-DoF cable-driven tools, Gregg-Smith & Mayol-Cuevas 2015); gaze-based intention prediction; assisted pick-and-place (block copying)",
         participants_or_bench="Participants in a simulated block-copy task (number in the paper)",
         comparator="Robot obeying vs rebelling against predicted intention",
         key_quantitative_findings="Intention predicted up to 1.5 s before actions; the paper reports task performance and user frustration differences between obedient and rebellious behaviour (read in full text; not re-quantified here).",
         units_and_conditions="Laboratory task; healthy adults",
         locator="Abstract; Sec. II.A (handheld robots); results section",
         limitations="Ungrounded handheld robot; pick-and-place, not writing",
         relevance_to_design="Support for 'the writer must always win' and for yielding when the writer insists",
         transferability="low", transferability_reason="Different task and device; the principle transfers",
         design_implication="Supervisor yields to a persistent writer; never act against a detected intention for long",
         search_query="WebSearch: Gregg-Smith Mayol-Cuevas cooperative handheld robot"),
    _row(id="HAP-63", topic="Viscous damping loads reduce disabling action tremor (grounded energy-dissipating orthosis)",
         citation="Aisen ML, Arnold A, Baiges I, Maxwell S, Rosen M. The effect of mechanical damping loads on disabling action tremor. Neurology. 1993;43(7):1346-1350.",
         year="1993", doi_or_url="10.1212/wnl.43.7.1346 ; PMID 8327136",
         source_type="journal", evidence_class="physical human study", access_level="abstract only",
         task_or_setup="Upper-extremity damping in three degrees of freedom by computer-controlled magnetic particle brakes (energy-dissipating orthoses)",
         participants_or_bench="10 patients with cerebellar action tremor (multiple sclerosis or traumatic brain injury)",
         comparator="No damping",
         key_quantitative_findings="All patients had statistically and functionally significant tremor reduction with damping; rationale: damping opposes the high-velocity tremor more than slower voluntary motion.",
         units_and_conditions="Cerebellar tremor; damping values not in the abstract",
         locator="Abstract (Europe PMC)",
         limitations="Abstract only; cerebellar, not essential tremor; not handwriting; damping values unknown here",
         relevance_to_design="Grounded damping is the principle of the heel damper (ball) and the along-path brake",
         transferability="medium", transferability_reason="Handwriting strokes are as fast as tremor, so damping discriminates less than in slow tasks",
         design_implication="Damp only above the writing band and measure the cost on clean writing (EXP-D09)",
         search_query="WebSearch + Europe PMC: effect of mechanical damping loads on disabling action tremor"),
    _row(id="HAP-64", topic="Wearable viscous tremor orthosis (Viscous Beam): damping constants achievable",
         citation="Kotovsky J, Rosen MJ. A wearable tremor-suppression orthosis. J Rehabil Res Dev. 1998;35(4):373-387.",
         year="1998", doi_or_url="PMID 10220215", source_type="journal", evidence_class="physical bench experiment",
         access_level="abstract only",
         task_or_setup="Constrained-layer silicone-fluid damper at the wrist (flexion-extension), bending-plate transmission",
         participants_or_bench="Bench characterisation", comparator="-",
         key_quantitative_findings="Damping up to 2.0e-3 N m/(deg/s) (0.115 N m s/rad) at strain rates up to 4580 deg/s; elastic stiffness 4.1e-2 N m/deg; reduces tremor amplitude (abstract).",
         units_and_conditions="Silicone fluids up to 10 million cS, shear layers 0.76 mm",
         locator="Abstract (Europe PMC)", limitations="Abstract only; wrist orthosis, not a pen",
         relevance_to_design="Order of magnitude of useful tremor damping, for comparison with the heel damper's 2-5 N s/m at the pen",
         transferability="low", transferability_reason="Different joint, lever and grounding",
         design_implication="Heel damping of a few N s/m is small against the arm's own 11 N s/m (HAP-26): expect partial effects",
         search_query="Europe PMC: wearable tremor-suppression orthosis"),
    _row(id="HAP-65", topic="Biomechanical loading for tremor: exoskeleton (active and passive) and neuroprosthesis results",
         citation="Rocon E, Gallego JA, Belda-Lois JM, Benito-Leon J, Pons JL. Biomechanical loading as an alternative treatment for tremor: a review of two approaches. Tremor Other Hyperkinet Mov. 2012;2.",
         year="2012", doi_or_url="10.7916/d82z147g ; PMC3569933", source_type="review", evidence_class="physical human study",
         access_level="full text (PMC)",
         task_or_setup="Wearable exoskeleton applying forces (viscosity/inertia) to tremulous upper limbs; transcutaneous neurostimulation",
         participants_or_bench="10 patients (exoskeleton), 12 (neuroprosthesis); parkinsonian or essential tremor",
         comparator="Active vs passive suppression strategies",
         key_quantitative_findings="Exoskeleton: consistent 40 % tremor power reduction in all patients, about 80 % in specific joints of severe cases; active strategy 81.2 % vs passive 70 % mean power reduction.",
         units_and_conditions="Tremor power at the joints", locator="Results of the exoskeleton project (full text)",
         limitations="Small samples; wearable, not pen-grounded; writing not tested",
         relevance_to_design="Evidence that loading tremulous limbs reduces tremor; frames what a grounded heel damper might do",
         transferability="low", transferability_reason="Joint-level wearable robot; the heel acts on the pen only",
         design_implication="Test the heel damper on people before claiming benefit (EXP-D09)",
         search_query="Europe PMC: Biomechanical loading as an alternative treatment for tremor"),
    _row(id="HAP-66", topic="Viscous damping of wrist tremor by a wearable robot (simulation and test bed)",
         citation="Raghavendra Kulkarni S, Accoto D, Campolo D. Viscous damping of tremor using a wearable robot with an optimized mechanical metamaterial. Wearable Technol. 2024;5:e20.",
         year="2024", doi_or_url="10.1017/wtc.2024.15 ; PMC11729489", source_type="journal", evidence_class="physical bench experiment",
         access_level="full text (PMC)",
         task_or_setup="Cable-driven wearable robot with a metamaterial interface; viscous damping on wrist flexion-extension velocity",
         participants_or_bench="Simulation and dedicated test bed", comparator="Without damping",
         key_quantitative_findings="Tremor attenuation 20-30 dB depending on tremor frequency (>= 3 Hz band).",
         units_and_conditions="Wrist FE; bench", locator="Abstract and results (full text)",
         limitations="Not human trials; wrist, not pen", relevance_to_design="Supports damping above about 3 Hz",
         transferability="low", transferability_reason="Different interface and scale",
         design_implication="Damper cut-on above the writing band; tune on tuning writers",
         search_query="Europe PMC: Viscous damping of tremor using a wearable robot"),
    _row(id="HAP-67", topic="Handwriting training with virtual fixtures versus error amplification: transfer to unassisted writing",
         citation="Clamann M, Kaber DB. Augmenting fine motor skill training with haptic error amplification. Proc Hum Factors Ergon Soc Annu Meet. 2018:1547-1551.",
         year="2018", doi_or_url="https://stacks.cdc.gov/view/cdc/207112", source_type="conference",
         evidence_class="physical human study", access_level="full text",
         task_or_setup="PHANToM Omni stylus; copying Georgian characters with the non-dominant hand; virtual fixture (VF) stencil vs error amplification (EA) vs control",
         participants_or_bench="24 participants (8 per condition)", comparator="VF, EA, control",
         key_quantitative_findings="VF threshold 0.05 in, EA 0.20 in; accuracy gained under VF did not transfer to unassisted test trials; EA training increased unaided accuracy (not all intervals significant).",
         units_and_conditions="Healthy adults; screen drawing", locator="Abstract; Haptic feature design; Results",
         limitations="Small groups; screen, not paper; non-dominant hand as a learning model",
         relevance_to_design="Strong guidance (a steered wheel's hard wall) helps performance, not necessarily learning",
         transferability="medium", transferability_reason="Handwriting-like task with a grounded stylus",
         design_implication="Use fading, catch trials and error-amplification modes; judge by unassisted retention",
         search_query="WebSearch: Mullins Mawson Nahavandi haptic handwriting aid (result list)"),
    _row(id="HAP-68", topic="Stylus with a braked ball at the tip (electromagnetic brake) for friction feedback",
         citation="Wintergerst G, Jagodzinski R, Hemmert F, Muller A, Joost G. Reflective Haptics: enhancing stylus-based interactions on touch screens. EuroHaptics 2010, LNCS 6191:360-366.",
         year="2010", doi_or_url="10.1007/978-3-642-14064-8_52 ; https://www.fabianhemmert.com/download/hemmert2010i_eh10_reflectivehaptics.pdf",
         source_type="conference", evidence_class="physical bench experiment", access_level="full text",
         task_or_setup="Steel ball at the stylus tip braked by an electromagnetic coil; soft PVC film on the screen for friction; three prototypes",
         participants_or_bench="Informal evaluation", comparator="-",
         key_quantitative_findings="Ball diameters 25, 10 and 5 mm in bodies of 35, 15 and 9 mm; users could tell brake levels apart from the ball's basic friction (informal).",
         units_and_conditions="Touch screen with PVC film", locator="Sec. 3 and Table 1",
         limitations="No force data; informal evaluation; screen not paper",
         relevance_to_design="Prior art for the braked-ball concept; a braked ball can only resist",
         transferability="medium", transferability_reason="Same mechanism at pen scale",
         design_implication="A braked ball is feasible in a pen body but only resists; not enough for guidance",
         search_query="WebSearch: Reflective haptics stylus rolling ball brake"),
    _row(id="HAP-69", topic="dePENd: a magnet under the table moved by an XY stage pulls a ballpoint pen's steel tip",
         citation="Yamaoka J, Kakehi Y. dePENd: augmented handwriting system using ferromagnetism of a ballpoint pen. UIST 2013:203-210.",
         year="2013", doi_or_url="10.1145/2501988.2502017 ; https://futurecrafts.kmd.keio.ac.jp/depend/",
         source_type="conference", evidence_class="physical bench experiment", access_level="secondary account",
         task_or_setup="Permanent magnet on a computer-controlled XY stage under the table attracts the steel ball tip of a normal pen",
         participants_or_bench="Demonstrations", comparator="-",
         key_quantitative_findings="No force or speed values on the project page; helps draw lines and circles, copy and scale drawings, remote transfer.",
         units_and_conditions="-", locator="Project page", limitations="Project page only; no numbers",
         relevance_to_design="Grounded under-table guidance (like the board); contrasts with the self-contained heel drive",
         transferability="low", transferability_reason="Needs a table stage", design_implication="Board remains the desk option",
         search_query="WebSearch: Yamaoka Kakehi dePENd UIST 2013"),
    _row(id="HAP-70", topic="Collaborative-robot contact limits for hands and fingers (quasi-static and transient)",
         citation="ISO/TS 15066:2016 Robots and robotic devices - Collaborative robots. Annex A, Table A.2.",
         year="2016", doi_or_url="https://www.iso.org/standard/62996.html ; full text read from https://www.diag.uniroma1.it/deluca/pHRI_elective/ISO_TS_15066_2016_en.pdf", source_type="standard", evidence_class="standard",
         access_level="full text",
         task_or_setup="Body model with permissible quasi-static and transient contact pressure and force per body region",
         participants_or_bench="Pain-onset studies (standard's references)", comparator="-",
         key_quantitative_findings="Hands and fingers: maximum permissible quasi-static force 140 N; pressure 300 N/cm2 (forefinger pad, dominant), 260 N/cm2 (palm); transient multiplier 2.",
         units_and_conditions="Industrial collaborative robots", locator="Annex A, Table A.2",
         limitations="Pain thresholds for industrial robots, not comfort thresholds for guidance",
         relevance_to_design="The heel drive's physical limit (mu x P <= 0.6 N) is more than 200 x below the hand limit",
         transferability="medium", transferability_reason="Safety bound, not a comfort target",
         design_implication="Safety case: the force limit is physical (preload x friction), far below injury limits; comfort cap set by guidance literature (0.43-0.49 N, HAP-15/16/51)",
         search_query="WebSearch: ISO/TS 15066 body model hand finger 140 N table"),
    # ------------------------------------------------------------------ AMF: actuators, materials, mechanisms
    _row(id="AMF-100", topic="6 mm brushless DC motor Faulhaber 0620 B (heel drive and steering motor)",
         citation="FAULHABER. Brushless DC-motor Series 0620 ... B, variant 0620K006B (eshop page).", year="n.d.",
         doi_or_url="https://eshop.faulhaber.com/en/0620-...-B/Serie-0620-...-B", source_type="manufacturer",
         evidence_class="manufacturer statement", access_level="full text",
         task_or_setup="Catalogue data", participants_or_bench="not applicable", comparator="maxon DCX 6 M (AMF-101)",
         key_quantitative_findings="6 x 20 mm, 2.5 g; 6 V: no-load 48 600 rpm, rated torque 0.28 mNm, stall 0.732 mNm, kt 1.09 mNm/A, R 8.8 ohm, rotor inertia 0.0095 g cm2, static friction 0.011 mNm, Rth 13.2 + 84.3 K/W, max winding 125 C, mechanical time constant 7 ms.",
         units_and_conditions="20 C, 6 V variant", locator="Product page data table",
         limitations="At the pen's 3.7 V the stall torque is voltage-limited to about 0.46 mNm (CALC)",
         relevance_to_design="Drive and steering motor of the steered wheel; drive rollers of the ball",
         transferability="high", transferability_reason="Catalogue part", design_implication="Selected class; two per heel drive",
         search_query="WebSearch: Faulhaber 0620 datasheet; WebFetch eshop page"),
    _row(id="AMF-101", topic="6 and 8 mm coreless DC motors maxon DCX 6 M and DCX 8 M",
         citation="maxon. Product range 2020/21, DCX 6 M (p. 75) and DCX 8 M (p. 76).", year="2020",
         doi_or_url="https://people.ece.ubc.ca/leos/pdf/datasheets/Maxon/MaxonCat.pdf", source_type="datasheet",
         evidence_class="manufacturer statement", access_level="full text",
         task_or_setup="Catalogue data", participants_or_bench="not applicable", comparator="Faulhaber 0620 B",
         key_quantitative_findings="DCX 6 M (3 V): no-load 17 500 rpm, nominal torque 0.332 mNm, stall 0.524 mNm, R 9.0 ohm, kt 1.56 mNm/A, rotor 0.0183 g cm2, 2.4 g, Rth 105 + 20 K/W. DCX 8 M (4.2 V): nominal 0.649 mNm, stall 1.14 mNm, R 12 ohm, kt 3.36 mNm/A, rotor 0.0379 g cm2.",
         units_and_conditions="Catalogue values", locator="pp. 75-76", limitations="Lengths/masses of the 8 mm motor not read",
         relevance_to_design="Alternatives in the design optimisation", transferability="high",
         transferability_reason="Catalogue parts", design_implication="Ø8 mm does not fit beside the nose arm; Ø6 mm preferred",
         search_query="WebSearch: maxon DCX 6 M datasheet"),
    _row(id="AMF-102", topic="6 mm planetary gearhead maxon GP 6 A (ratios, efficiency, torque, backlash)",
         citation="maxon. Product range 2020/21, Planetary Gearhead GP 6 A (p. 358).", year="2020",
         doi_or_url="https://people.ece.ubc.ca/leos/pdf/datasheets/Maxon/MaxonCat.pdf", source_type="datasheet",
         evidence_class="manufacturer statement", access_level="full text",
         task_or_setup="Catalogue data", participants_or_bench="not applicable", comparator="Faulhaber 06/1",
         key_quantitative_findings="3.9:1 88 % 1.7 g 5.3 mm 2/5 mNm (cont./int.) backlash 1.8 deg; 15:1 77 % 2.1 g 7.8 mm 5/10 mNm; 57:1 68 % 2.5 g 10.4 mm 10/20 mNm; 221:1 60 %; max input 40 000 rpm.",
         units_and_conditions="Catalogue values", locator="p. 358 gearhead data", limitations="-",
         relevance_to_design="Efficiency per stage (about 0.9) and torque limits in the sizing", transferability="high",
         transferability_reason="Catalogue part", design_implication="Low ratios keep the reflected mass small",
         search_query="grep of the maxon catalogue"),
    _row(id="AMF-103", topic="6 mm planetary gearhead Faulhaber 06/1",
         citation="FAULHABER. Planetary gearhead Series 06/1 (series page and 256:1 eshop variant).", year="n.d.",
         doi_or_url="https://eshop.faulhaber.com/en/06-1-256-1/06-1-256-1", source_type="manufacturer",
         evidence_class="manufacturer statement", access_level="full text",
         task_or_setup="Catalogue data", participants_or_bench="not applicable", comparator="maxon GP 6 A",
         key_quantitative_findings="Series: 1-6 stages, ratios 4-4096, continuous torque up to 25 mNm, intermittent up to 35 mNm, length 9.2-22.7 mm, Ø6 mm; 256:1 variant: max efficiency 60 %, 4 g, 17.3 mm, max input 8000 rpm.",
         units_and_conditions="Catalogue values", locator="Series and variant pages",
         limitations="Efficiencies of 1-3 stage versions not read (0.9 per stage assumed)", relevance_to_design="Gear option",
         transferability="high", transferability_reason="Catalogue part", design_implication="1 stage (4:1) for the steering motor",
         search_query="WebSearch: Faulhaber 06/1 gearhead"),
    _row(id="AMF-104", topic="4 mm brushless micromotor Orbray (Namiki) BMN04-08",
         citation="Orbray Co. Brushless Motor BMN04-08 product page.", year="n.d.",
         doi_or_url="https://orbray.com/en/product/dccorelessmotor/brushless_ca_bmn04-08.html", source_type="manufacturer",
         evidence_class="manufacturer statement", access_level="full text",
         task_or_setup="Catalogue data", participants_or_bench="not applicable", comparator="6 mm motors",
         key_quantitative_findings="Ø4 mm, 0.7 g, 3 V, no-load 37 600 rpm, rated torque 0.01 mNm, stall 0.04 mNm, kt 0.52 mNm/A, R 30.5 ohm; SPG04 gearhead referenced without data.",
         units_and_conditions="Catalogue values", locator="Product page", limitations="Gearhead data not published on the page",
         relevance_to_design="A motor small enough to sit at the heel", transferability="high", transferability_reason="Catalogue part",
         design_implication="Too weak and slow to drive the wheel directly (0.40 N, about 26 mm/s with an assumed 100:1 head, CALC); keep motors in the handle",
         search_query="WebSearch: Namiki SBL04 4 mm; WebFetch Orbray page"),
    _row(id="AMF-105", topic="8 mm two-phase stepper Faulhaber AM0820 (steering option)",
         citation="FAULHABER. Stepper Motors Series AM0820 datasheet (EN_AM0820_FPS).", year="2026",
         doi_or_url="https://www.faulhaber.com/fileadmin/Import/Media/EN_AM0820_FPS.pdf", source_type="datasheet",
         evidence_class="manufacturer statement", access_level="full text",
         task_or_setup="Catalogue data", participants_or_bench="not applicable", comparator="DC motor + Hall servo",
         key_quantitative_findings="20 steps/rev; holding torque 0.65 mNm (1 mNm boosted); residual torque 0.13 mNm; rotor 2.75e-9 kg m2; max angular acceleration 363e3 rad/s2; no-load resonance 75 Hz; 3.3 g.",
         units_and_conditions="20 C", locator="Data table", limitations="Open-loop; 18 deg steps need microstepping",
         relevance_to_design="Steering actuator alternative", transferability="high", transferability_reason="Catalogue part",
         design_implication="A DC motor with a Hall angle sensor is preferred for a 40 Hz steering servo",
         search_query="WebSearch: Faulhaber AM0820 stepper datasheet"),
    _row(id="AMF-106", topic="Smallest piezo linear motor: New Scale SQUIGGLE SQL-RV-1.8",
         citation="New Scale Technologies. SQL-RV-1.8 SQUIGGLE RV technical bulletin, Rev. G, 2021.", year="2021",
         doi_or_url="https://newscaletech.com/wp-content/uploads/SQL-RV-1-8_datasheet-2.pdf", source_type="datasheet",
         evidence_class="manufacturer statement", access_level="full text",
         task_or_setup="Catalogue data", participants_or_bench="not applicable", comparator="-",
         key_quantitative_findings="2.8 x 2.8 x 6 mm, 0.16 g; stall 0.33 N (3.3 V); > 7 mm/s at 15 gf; < 340 mW moving; holds with 0 mW; 6 mm travel; 171 kHz.",
         units_and_conditions="NSD-2101 driver", locator="System performance table", limitations="Sold only in modules",
         relevance_to_design="Candidate brake-pad actuator; too slow to drive the pen or steer", transferability="high",
         transferability_reason="Catalogue part", design_implication="Not used for drive or steering",
         search_query="WebSearch: SQUIGGLE SQL-RV-1.8 datasheet"),
    _row(id="AMF-107", topic="Miniature travelling-wave ultrasonic rotary motor (4.12 mm PZT stator)",
         citation="Hareesh P, DeVoe DL. Miniature bulk PZT traveling wave ultrasonic motors for low-speed high-torque rotary actuation. J Microelectromech Syst. 2018;27(3):547-554.",
         year="2018", doi_or_url="10.1109/jmems.2018.2823980 ; PMC6261514", source_type="journal",
         evidence_class="physical bench experiment", access_level="abstract only",
         task_or_setup="Monolithic PZT stator with interdigitated electrodes; glass rotor; preload", participants_or_bench="Bench",
         comparator="-", key_quantitative_findings="4.12 mm stator: max 30 rpm, stall torque 0.501 mNm at 0.323 N preload.",
         units_and_conditions="Research device", locator="Abstract", limitations="Research prototype",
         relevance_to_design="Silent, self-holding heel actuator option", transferability="low",
         transferability_reason="30 rpm is 10-50 x too slow for steering or driving",
         design_implication="Not used", search_query="WebSearch: miniature piezo rotary ultrasonic motor"),
    _row(id="AMF-108", topic="Magnetorheological fluid LORD MRF-132DG (braked-ball option)",
         citation="LORD Corporation. MRF-132DG Magneto-Rheological Fluid, technical data sheet.", year="n.d.",
         doi_or_url="https://www.creact.co.jp/measure/mr-er/mr/file/MRF-132DG_datasheet.pdf", source_type="datasheet",
         evidence_class="manufacturer statement", access_level="full text",
         task_or_setup="Typical properties", participants_or_bench="not applicable", comparator="-",
         key_quantitative_findings="Viscosity 0.112 +/- 0.02 Pa s at 40 C; density 2.95-3.15 g/cm3; 80.98 % solids by weight; -40 to +130 C; yield stress plotted up to about 50 kPa (read from the plot).",
         units_and_conditions="Datasheet", locator="Typical properties table; yield-stress plot",
         limitations="Plot reading approximate; sealing at mm scale not addressed", relevance_to_design="MR brake sizing (CALC)",
         transferability="medium", transferability_reason="Needs a coil and seals in a 3 mm heel pod",
         design_implication="MR brake rejected for complexity; motor braking used instead",
         search_query="WebSearch: LORD MRF-132DG datasheet"),
    _row(id="AMF-109", topic="Optical navigation sensor PixArt PMW3360 (pen-over-paper velocity, slip detection)",
         citation="PixArt Imaging. PMW3360DM-T2QU product datasheet, rev. 1.50, 2016.", year="2016",
         doi_or_url="https://www.pixart.com/products-detail/10/PMW3360DM-T2QU", source_type="datasheet",
         evidence_class="manufacturer statement", access_level="full text",
         task_or_setup="Catalogue data", participants_or_bench="not applicable", comparator="-",
         key_quantitative_findings="250 ips typical (300 on some mouse pads), acceleration 50 g, up to 12 000 cpi, up to 12 000 fps, run current 16.3-21.6 mA with 1 ms polling, lift detection.",
         units_and_conditions="Mouse-pad surfaces", locator="Key specifications; electrical characteristics",
         limitations="Gaming-mouse part: size and lens height to be checked for a pen; paper tracking not specified",
         relevance_to_design="Measures the heel's velocity over the paper to detect slip and to feed the drive laws",
         transferability="medium", transferability_reason="Surface and lens distance differ in a pen",
         design_implication="The Rev H paper sensor doubles as the slip sensor (EXP-D04)",
         search_query="WebSearch: PixArt PMW3360 datasheet"),
    _row(id="AMF-110", topic="Smallest commercial omni-wheel found (Vinci micro omni wheels)",
         citation="Vinci Innova. Vinci Micro Omni Wheels, Crowd Supply campaign page.", year="n.d.",
         doi_or_url="https://www.crowdsupply.com/vinci-innova/vinci-micro-omni-wheels", source_type="website",
         evidence_class="manufacturer statement", access_level="full text",
         task_or_setup="Pre-launch product page", participants_or_bench="not applicable", comparator="Nexus 38 mm omni-wheels",
         key_quantitative_findings="11.5 mm diameter, 7.5 mm wide, 6 silicone rollers, 1.5 or 2 mm shaft holes; load, mass and price not given.",
         units_and_conditions="-", locator="Specifications", limitations="Pre-launch; no load data",
         relevance_to_design="Omni-wheel concept size", transferability="high", transferability_reason="Catalogue-class part",
         design_implication="Too large for the heel (needs a contact radius of about 16 mm, CALC)",
         search_query="WebSearch: smallest omni wheel diameter mm"),
    _row(id="AMF-111", topic="Rubber (polyurethane) on paper friction: paper-feed rollers new and after 300 000 sheets",
         citation="Yoshida Y, Kawano A, Doi K, Suzuki S (Sumitomo Riko). Paper feed roller. US 9,815,644 B2, 2017.",
         year="2017", doi_or_url="https://patents.google.com/patent/US9815644B2/en", source_type="patent",
         evidence_class="patent disclosure", access_level="full text",
         task_or_setup="Examples: polyurethane elastic layers with plasticiser; PPC paper pressed with 2.94 N via a PTFE sheet; 180 mm/s",
         participants_or_bench="Bench (assignee's examples)", comparator="Samples 1-8",
         key_quantitative_findings="Friction coefficient against paper 1.30-2.20 initially and 1.05-1.52 after feeding 300 000 sheets (23 C, 53 % RH); JIS-A hardness 43-75.",
         units_and_conditions="Roller on PPC paper", locator="Table 1 (examples)",
         limitations="Assignee data; roller compounds optimised for paper feeding; paper dust in printers",
         relevance_to_design="Upper bound of elastomer-on-paper traction; wear lowers it", transferability="medium",
         transferability_reason="Same contact pair; different load, speed and paper",
         design_implication="Design mu range 0.6-1.2 for a general-purpose tyre; measure on 6 papers (EXP-D01)",
         search_query="WebSearch: paper feed roller rubber coefficient of friction"),
    _row(id="AMF-112", topic="Rolling friction of a hard sphere or cylinder on a viscoelastic solid",
         citation="Persson BNJ. Rolling friction for hard cylinder and sphere on viscoelastic solid. Eur Phys J E. 2010;33:327-333.",
         year="2010", doi_or_url="10.1140/epje/i2010-10678-y ; https://arxiv.org/abs/1008.4493", source_type="journal",
         evidence_class="analytical derivation", access_level="full text",
         task_or_setup="Theory; comparison with Hunter's exact result and Greenwood-Tabor", participants_or_bench="-",
         comparator="Hunter 1961; Greenwood & Tabor", key_quantitative_findings="Low-velocity limit for a sphere: mu_R ~ 2.34 (p_a/E0) tan(delta); Greenwood-Tabor form mu = (9 pi/64)(p_a/E0) alpha with alpha ~ 5.3 tan(delta).",
         units_and_conditions="Linear viscoelasticity", locator="Eq. (19)-(21)", limitations="Hard ball on rubber; here a rubber tyre on paper (roles swapped; same order)",
         relevance_to_design="Rolling resistance of the tyre: 0.04-0.07 N/N at 0.2-0.6 N (CALC)", transferability="medium",
         transferability_reason="Scaling law; paper compliance ignored", design_implication="Rolling drag about 20-30 mN, below the skid's 96 mN",
         search_query="WebSearch: Persson rolling friction viscoelastic arXiv"),
    _row(id="AMF-113", topic="Paper friction test method and its precision (TAPPI T 549)",
         citation="TAPPI/ANSI T 549 om-20. Coefficients of static and kinetic friction of uncoated writing and printing paper by use of the horizontal plane method.",
         year="2020", doi_or_url="https://www.tappi.org/contentassets/58af997fbe9b4f40a7545ee183554082/2025/t549-b-2-d-1-sarg.pdf",
         source_type="standard", evidence_class="standard", access_level="full text",
         task_or_setup="Horizontal plane, sled 150 mm/min, paper on paper", participants_or_bench="26 labs",
         comparator="-", key_quantitative_findings="Between-lab SD 0.057 (static) and 0.056 (kinetic); repeatability 12-13 %; reproducibility 24-27 %.",
         units_and_conditions="Paper on paper", locator="Table 1 (precision)", limitations="Paper-on-paper, not rubber-on-paper or paper-on-desk",
         relevance_to_design="Friction values vary by +/-25 % between labs: measure, do not assume", transferability="medium",
         transferability_reason="Method and precision transfer", design_implication="Use a calibrated traction estimate per session (EXP-D01, EXP-D03)",
         search_query="WebSearch: paper-to-paper coefficient of friction TAPPI"),
    _row(id="AMF-114", topic="Electroadhesion pressure before and after contact (conductive and dielectric objects)",
         citation="Schaller S, Shea H. Measuring electro-adhesion pressure before and after contact. Sci Rep. 2023;13:11768.",
         year="2023", doi_or_url="10.1038/s41598-023-38872-6 ; PMC10359345", source_type="journal",
         evidence_class="physical bench experiment", access_level="full text (PMC)",
         task_or_setup="Over 100 interdigitated EA patches; conductive and glass targets; AC and DC drive", participants_or_bench="Bench",
         comparator="Pre-contact vs release pressure", key_quantitative_findings="At 400 V release pressures 1-100 kPa on conductive objects; for dielectric objects release pressures are 1-100 x the pre-contact adhesion; at 2 kV release 5 kPa (AC) to about 60 kPa (DC, 90 s hold).",
         units_and_conditions="Glass chip as the dielectric", locator="Abstract; results", limitations="Not paper",
         relevance_to_design="Electroadhesive heel pad adds at most about 0.02-0.12 N of normal force on 24 mm2 (CALC)",
         transferability="low", transferability_reason="Paper is porous and moist; hand safety at 400-2000 V",
         design_implication="Reject electroadhesion at the heel", search_query="WebSearch: electroadhesion paper pressure kPa"),
    _row(id="AMF-115", topic="Ultrasonic squeeze-film friction reduction (fingertip on glass)",
         citation="Wiertlewski M, Fenton Friesen R, Colgate JE. Partial squeeze film levitation modulates fingertip friction. PNAS. 2016;113(33):9210-9215.",
         year="2016", doi_or_url="10.1073/pnas.1603908113 ; PMC4995990", source_type="journal",
         evidence_class="physical bench experiment", access_level="abstract only",
         task_or_setup="Glass plate excited with ultrasonic transverse waves; frustrated total internal reflection imaging",
         participants_or_bench="Fingertips (lab)", comparator="Plate at rest",
         key_quantitative_findings="Load shared between skin asperities and an air squeeze film; dynamic levitation reduces the number of asperities in contact and so friction (abstract; the up-to-95 % figure at +/-3 um was seen only in a search summary).",
         units_and_conditions="Finger on glass", locator="Abstract", limitations="Abstract only; skin on glass, not a pad on paper",
         relevance_to_design="Controllable-friction heel pad", transferability="low",
         transferability_reason="Needs a smooth, airtight contact; paper is porous", design_implication="Not pursued",
         search_query="WebSearch: Wiertlewski squeeze film PNAS 2016"),
    _row(id="AMF-116", topic="Directional (anisotropic) friction by buckled kirigami skins",
         citation="Rafsanjani A, Zhang Y, Liu B, Rubinstein SM, Bertoldi K. Kirigami skins make a simple soft actuator crawl. Sci Robot. 2018;3(15):eaar7555.",
         year="2018", doi_or_url="10.1126/scirobotics.aar7555 ; PMID 33141681", source_type="journal",
         evidence_class="physical bench experiment", access_level="abstract only",
         task_or_setup="Stretchable kirigami sheets pop up into scale-like textures; friction anisotropy used for crawling",
         participants_or_bench="Bench", comparator="Flat sheet", key_quantitative_findings="Buckling-induced change of frictional properties enables efficient crawling (abstract; no numbers read).",
         units_and_conditions="-", locator="Abstract", limitations="Abstract only; no anisotropy ratio read",
         relevance_to_design="A steered anisotropic pad as a sliding 'skate' alternative to the steered wheel", transferability="low",
         transferability_reason="A sliding pad drags far more than a rolling wheel", design_implication="Not pursued",
         search_query="Europe PMC: kirigami skins crawl"),
    _row(id="AMF-117", topic="Inverse mouse-ball drive: rollers drive a ball; the orthogonal roller must slip",
         citation="Lauwers T, Kantor G, Hollis R. One is enough! In: Robotics Research (ISRR 2005), Springer STAR 28, 2007 (and ICRA 2006, 'A dynamically stable single-wheeled mobile robot with inverse mouse-ball drive').",
         year="2005", doi_or_url="http://robots.stanford.edu/isrr-papers/final/final-31.pdf", source_type="conference",
         evidence_class="physical bench experiment", access_level="full text",
         task_or_setup="200 mm steel ball with 3.2 mm urethane; two 12.7 mm smooth stainless drive rollers at the equator; spring-loaded idlers",
         participants_or_bench="Robot prototype", comparator="-",
         key_quantitative_findings="'Some slippage is always present ... if one roller is being driven, the orthogonal roller must be slipping'; needs a high- and a low-friction ball at once; 'a fair amount of ball wear'.",
         units_and_conditions="Floor robot", locator="Sec. 3 (drive)", limitations="Floor scale",
         relevance_to_design="The driven-ball concept's internal scrub and wear", transferability="medium",
         transferability_reason="Kinematic fact holds at any scale", design_implication="Use omni-type rollers or four driven rollers; smooth rollers cost about 0.2 N of drag (CALC)",
         search_query="WebSearch: Lauwers Kantor Hollis inverse mouse-ball drive"),
    _row(id="AMF-118", topic="Ballbot drive, second generation: four driven rollers, measured drive friction",
         citation="Nagarajan U, Kantor G, Hollis R. The ballbot: an omnidirectional balancing mobile robot. Int J Robot Res. 2014;33(6):917-930.",
         year="2014", doi_or_url="10.1177/0278364913509126 ; http://www.msl.ri.cmu.edu/publications/pdfs/ballbotIJRR_final.pdf",
         source_type="journal", evidence_class="physical bench experiment", access_level="full text",
         task_or_setup="Four DC servomotors drive four rollers (pure torques) to avoid the 'hopping' of drive + idler pairs; friction identified",
         participants_or_bench="Robot", comparator="First-generation IMB",
         key_quantitative_findings="Ball radius 0.1058 m, roller radius 6.335 mm; Coulomb friction torque 3.82 N m, viscous 3.68 N m s/rad (Table I); 0.185 m aluminium sphere with 13.5 mm urethane (Rezero comparison text).",
         units_and_conditions="Robot scale", locator="Sec. III.A, Table I", limitations="Scale",
         relevance_to_design="Driven-ball friction is large relative to the drive torque", transferability="low",
         transferability_reason="Scale", design_implication="Budget internal friction in the ball concept",
         search_query="WebSearch: ballbot inverse mouse-ball drive pdf"),
    # ------------------------------------------------------------------ CON: hand, writing, safety context
    _row(id="CON-36", topic="Mechanical impedance of the index fingertip: stiffness rises with activation",
         citation="Hajian AZ, Howe RD. Identification of the mechanical impedance at the human finger tip. J Biomech Eng. 1997;119(1):109-114.",
         year="1997", doi_or_url="10.1115/1.2796052", source_type="journal", evidence_class="physical human study",
         access_level="abstract only", task_or_setup="Rapid transients at the outstretched index fingertip; second-order fits over 20 ms",
         participants_or_bench="Healthy subjects", comparator="Force levels 2-20 N (extension), 2-8 N (abduction)",
         key_quantitative_findings="Effective mass constant above 6 N (extension); stiffness increased linearly with muscle activation; damping ratio in extension about 1.7 x abduction (abstract; no values read).",
         units_and_conditions="Fingertip", locator="Abstract", limitations="Abstract only; no values",
         relevance_to_design="A writer who grips harder stiffens: the drive's effect falls (as the HAP-26 upper-CI case)",
         transferability="medium", transferability_reason="Finger, not stylus grip", design_implication="Report the lightly-resisting case",
         search_query="Europe PMC: mechanical impedance at the human finger tip"),
    _row(id="CON-37", topic="Speed-curvature power law of drawing and handwriting (2/3 law)",
         citation="Zago M, Matic A, Flash T, Gomez-Marin A, Lacquaniti F. The speed-curvature power law of movements: a reappraisal. Exp Brain Res. 2018;236:69-82.",
         year="2018", doi_or_url="10.1007/s00221-017-5108-z", source_type="journal", evidence_class="review",
         access_level="abstract only", task_or_setup="Reappraisal of the 2/3 power law (Lacquaniti, Terzuolo, Viviani 1983)",
         participants_or_bench="Human drawing data; Drosophila larvae", comparator="Marken & Shaffer 2017 artefact claim",
         key_quantitative_findings="Angular speed varies approximately with the 2/3 power of curvature; the exponent varies with shape and environment; the law is not a statistical artefact.",
         units_and_conditions="Drawing movements", locator="Abstract", limitations="Abstract only",
         relevance_to_design="Sharp curves are drawn slowly: the steering rate needed grows slower than curvature", transferability="medium",
         transferability_reason="General law; exponent varies", design_implication="Size steering from the letters' heading rates (CALC p90 71 rad/s, p99 283 rad/s)",
         search_query="WebSearch: Lacquaniti two-thirds power law"),
    _row(id="CON-38", topic="Pen lifts and pen stops in proficient and dysgraphic handwriting",
         citation="Paz-Villagran V, Danna J, Velay JL. Lifts and stops in proficient and dysgraphic handwriting. Hum Mov Sci. 2014;33:381-394.",
         year="2014", doi_or_url="10.1016/j.humov.2013.11.005", source_type="journal", evidence_class="physical human study",
         access_level="abstract only", task_or_setup="Writing a single word at normal and fast speed; lifts vs stops",
         participants_or_bench="Dysgraphic children, proficient children, adults", comparator="Groups",
         key_quantitative_findings="Number of lifts did not differ between groups; adults' lift durations shorter; dysgraphic children made more and longer stops than proficient children.",
         units_and_conditions="Digitiser", locator="Abstract", limitations="Abstract only; no durations read",
         relevance_to_design="A paper-grounded drive acts only while the pen is down; pen stops matter for the wheel's re-steering",
         transferability="medium", transferability_reason="Children; single word", design_implication="Pre-steer the wheel during pen lifts and stops",
         search_query="WebSearch: in-air time handwriting dysgraphia"),
    # ------------------------------------------------------------------ PAT
    _row(id="PAT-30", topic="Drawing device steered by a single driven, steerable wheel (prior art for a steered wheel that draws)",
         citation="May RL, Curren KJ (Androbot Singapore). Drafting device for use with computers. US 4,485,555 A, 1984.",
         year="1984", doi_or_url="https://patents.google.com/patent/US4485555A/en", source_type="patent",
         evidence_class="patent disclosure", access_level="full text",
         task_or_setup="Pen between two free wheels; one motor-driven wheel whose axis angle is varied acts as a steering wheel",
         participants_or_bench="-", comparator="Two-motor plotters", key_quantitative_findings="Claim 1: marking instrument, two free support wheels, a steerable drive wheel with means to rotate it and vary its angle. Status: expired (fee related).",
         units_and_conditions="-", locator="Abstract; claim 1", limitations="Not handheld; not guiding a hand",
         relevance_to_design="Prior art for steered-and-driven drawing on paper", transferability="medium",
         transferability_reason="Same principle, different use", design_implication="Expired; note for freedom to operate",
         search_query="WebSearch: steerable wheel drawing device patent"),
    _row(id="PAT-31", topic="Stylus with a rotating contact ball whose friction is set by a gripping mechanism",
         citation="Adhikari S (Sony). Stylus based haptic peripheral for touch screen and tablet devices. US 8,681,130 B2, 2014.",
         year="2014", doi_or_url="https://patents.google.com/patent/US8681130B2/en", source_type="patent",
         evidence_class="patent disclosure", access_level="full text",
         task_or_setup="Contact ball at the stylus tip; prongs grip the ball to vary friction; separate feedback actuator",
         participants_or_bench="-", comparator="-", key_quantitative_findings="Claim 1: stylus with a rotating contact ball and a gripping mechanism producing a variable ball friction force independent of the feedback actuator. Status: expired (fee related).",
         units_and_conditions="-", locator="Claim 1", limitations="Touch screens", relevance_to_design="Prior art for the braked ball",
         transferability="medium", transferability_reason="Same mechanism at the tip", design_implication="Expired",
         search_query="WebSearch (result list): stylus haptic ball brake patent"),
    _row(id="PAT-32", topic="Automatically guided (position-correcting) handheld tools (Shaper)",
         citation="Rivers AR, Moyer IE (Shaper Tools). Automatically guided tools. US 10,788,804 B2, 2020 (priority 2011-05-19).",
         year="2020", doi_or_url="https://patents.google.com/patent/US10788804B2/en", source_type="patent",
         evidence_class="patent disclosure", access_level="full text",
         task_or_setup="Handheld frame moved roughly by the user; motors move a stage holding the working member to follow the design; camera map localisation",
         participants_or_bench="-", comparator="-", key_quantitative_findings="Claim 1: stage, motors, controllers, processor, camera building a map and positioning the working member; example: bit moves 0.5 in from centre. Status: active, anticipated expiry 2032-05-21.",
         units_and_conditions="-", locator="Claim 1; description", limitations="Tool stage, not paper-grounded force",
         relevance_to_design="The nose (not the heel) is closest; the heel drive pushes the frame itself", transferability="medium",
         transferability_reason="Different mechanism", design_implication="Freedom-to-operate check of camera-map localisation if the pen adopts it",
         search_query="WebSearch: Shaper Tools guided tools patent"),
    _row(id="PAT-33", topic="Hand-support platform rolling on the paper on frictionally slowed ball bearings",
         citation="Bricker BL. Rolling support platform device for writing, drawing and the like. US 4,313,585 A, 1982.",
         year="1982", doi_or_url="https://patents.google.com/patent/US4313585A/en", source_type="patent",
         evidence_class="patent disclosure", access_level="full text",
         task_or_setup="Platform under the hand with 3-5 ball bearings in cleats; cleat friction slows the rolling",
         participants_or_bench="-", comparator="Bearing-race designs", key_quantitative_findings="Claim 1: platform, three or more cleats with ball bearings, frictional contact sufficient to slow rolling; removable bearings because earlier designs jammed with eraser particles. Status: expired.",
         units_and_conditions="-", locator="Claim 1; background", limitations="Passive hand support",
         relevance_to_design="Prior art for paper-rolling balls with friction; warns of debris jamming", transferability="medium",
         transferability_reason="Same contact with paper", design_implication="Replaceable, cleanable tyre/ball; seal the pod against paper dust",
         search_query="WebSearch: rolling support platform writing patent"),
    _row(id="PAT-34", topic="Ball-balancing robot drive with three omniwheels (ballbot drive assembly)",
         citation="Bewley TR, Friesen JM, Sihite E, Yang D (UC San Diego). Ball-balancing robot and drive assembly therefor. US 10,189,342 B2, 2019.",
         year="2019", doi_or_url="https://patents.google.com/patent/US10189342B2/en", source_type="patent",
         evidence_class="patent disclosure", access_level="full text",
         task_or_setup="Three omniwheel assemblies at 120 deg, axles at alpha (about 70 deg) from the pole, mutually orthogonal planes",
         participants_or_bench="-", comparator="-", key_quantitative_findings="Normal force per wheel N = mg / (3 cos alpha); omniwheels drive in one direction and pass perpendicular ball rotation with little friction. Status: active.",
         units_and_conditions="-", locator="Description; claim 1", limitations="Robot scale",
         relevance_to_design="Omni-roller ball drive avoids the orthogonal roller's scrub (AMF-117)", transferability="medium",
         transferability_reason="Kinematics transfer; micro omni-rollers are the hard part", design_implication="Freedom-to-operate check if a 3-omniwheel ball drive is chosen",
         search_query="WebSearch (result list): ball-balancing robot drive assembly patent"),
]


def write_rows(path=None) -> Path:
    path = Path(path or (REPO_ROOT / "results" / "drive" / "evidence_rows.csv"))
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=HEADER)
        w.writeheader()
        for r in ROWS:
            w.writerow(r)
    return path
