"""PROPOSED ICD record 0x06: template segment (phone -> pen), reference encoder/decoder.

This is a proposal for docs/icd.md (not adopted; docs/ai_guidance.md s6).  It
uses the ICD s4.1 record framing (type u8 | length u8 | payload | CRC-16), so
the same bytes can travel over BLE and be logged in the research log; today's
reader (app/penapp/logfmt.py) keeps an unknown type with a valid CRC as raw
bytes, so older readers are unaffected.

Payload (little-endian, 24-byte header + 2 bytes per point, <= 255 bytes):

    seg_id        u16   template segment id (one predicted letter), monotonic per session
    part          u8    stroke index within the segment (bits 0-6); bit 7 = last stroke
    flags         u8    bit0 ANCHOR: points are relative to the nib position at the first
                              contact after t_valid_from (pen-side anchoring);
                        bit1 SUPERSEDE: drop every pending segment with id >= seg_id first;
                        bit2 CANCEL: drop segment seg_id (no points);
                        bit3 SYNTHETIC: generated by a test tool
    glyph         u8    predicted character (ASCII), 0 if none
    confidence    u8    calibrated c_hat x 255 (ICD s5 rule 5: c = min(1, c_hat / c_full); c_hat < c_min -> ignore)
    t_valid_from  u32   ms, session clock (ICD 4.3): not used before
    t_valid_to    u32   ms, session clock: expiry (the guard drops expired segments)
    x0_um, y0_um  i32   stroke start, um: page frame, or relative to the anchor if ANCHOR
    speed         u8    nominal pen-down speed, mm/s (the pen times the template at the stage rate)
    n             u8    number of points after the start (<= 115)
    points        n x (dx i8, dy i8) in units of RES_UM (10 um), successive differences

A stroke longer than 115 points continues in the next record with the same
seg_id and part (bit 7 clear until the last).  Points are spaced ~100 um
along the path; the pen resamples them to its stage rate with a minimum-jerk
time law at ``speed``.
"""
from __future__ import annotations

import struct
from dataclasses import dataclass, field
from typing import Dict, Iterable, List, Sequence, Tuple

import numpy as np

from . import ensure_paths
from .glyphs import arclength, resample

ensure_paths()
from penapp.logfmt import RawRecord, encode_record  # noqa: E402

RTYPE_TEMPLATE = 0x06
RES_UM = 10
SPACING_UM = 100
HDR = struct.Struct("<HBBBBIIiiBB")
MAX_POINTS = (255 - HDR.size) // 2
F_ANCHOR, F_SUPERSEDE, F_CANCEL, F_SYNTHETIC = 1, 2, 4, 8


@dataclass
class TemplateRecord:
    seg_id: int
    part: int
    last: bool
    flags: int
    glyph: str
    confidence: float
    t_from_ms: int
    t_to_ms: int
    x0_um: int
    y0_um: int
    speed_mm_s: int
    deltas: List[Tuple[int, int]] = field(default_factory=list)

    def payload(self) -> bytes:
        if len(self.deltas) > MAX_POINTS:
            raise ValueError("too many points for one record")
        h = HDR.pack(self.seg_id & 0xFFFF, (self.part & 0x7F) | (0x80 if self.last else 0), self.flags & 0xFF,
                     ord(self.glyph) if self.glyph else 0, int(round(min(max(self.confidence, 0.0), 1.0) * 255)),
                     self.t_from_ms, self.t_to_ms, self.x0_um, self.y0_um, min(max(self.speed_mm_s, 0), 255),
                     len(self.deltas))
        return h + b"".join(struct.pack("<bb", dx, dy) for dx, dy in self.deltas)

    @classmethod
    def from_payload(cls, b: bytes) -> "TemplateRecord":
        seg, part, flags, g, c, tf, tt, x0, y0, sp, n = HDR.unpack_from(b, 0)
        if len(b) != HDR.size + 2 * n:
            raise ValueError("payload length does not match its point count")
        d = [struct.unpack_from("<bb", b, HDR.size + 2 * i) for i in range(n)]
        return cls(seg, part & 0x7F, bool(part & 0x80), flags, chr(g) if g else "", c / 255.0, tf, tt, x0, y0, sp, d)

    def points_um(self) -> np.ndarray:
        p = np.array([[self.x0_um, self.y0_um]], float)
        if self.deltas:
            p = np.vstack([p, p[0] + np.cumsum(np.asarray(self.deltas, float) * RES_UM, axis=0)])
        return p

    def framed(self) -> bytes:
        return encode_record(RTYPE_TEMPLATE, self.payload())

    def raw_record(self) -> RawRecord:
        return RawRecord(RTYPE_TEMPLATE, self.payload())


def _quantise(P_um: np.ndarray) -> Tuple[Tuple[int, int], List[Tuple[int, int]]]:
    """Start point and i8 deltas with error feedback (the decoded path never drifts)."""
    x0 = (int(round(P_um[0, 0])), int(round(P_um[0, 1])))
    rec = np.array(x0, float)
    out = []
    for p in P_um[1:]:
        d = np.round((p - rec) / RES_UM).astype(int)
        while np.any(np.abs(d) > 127):                     # cannot happen at 100 um spacing; split the step
            step = np.clip(d, -127, 127)
            out.append((int(step[0]), int(step[1])))
            rec = rec + step * RES_UM
            d = np.round((p - rec) / RES_UM).astype(int)
        out.append((int(d[0]), int(d[1])))
        rec = rec + d * RES_UM
    return x0, out


def encode_letter(strokes_m: Sequence[np.ndarray], *, seg_id: int, glyph: str, confidence: float, t_from_ms: int,
                  t_to_ms: int, speed_mm_s: float, anchor: bool = True, flags: int = 0) -> List[TemplateRecord]:
    """Records for one letter template (strokes in metres, page frame)."""
    origin = np.asarray(strokes_m[0][0], float) if anchor else np.zeros(2)
    recs: List[TemplateRecord] = []
    for si, s in enumerate(strokes_m):
        s = np.asarray(s, float)
        L = arclength(s)[-1]
        P = resample(s, max(2, int(np.ceil(L * 1e6 / SPACING_UM)) + 1)) if L > 0 else s[:1]
        P_um = (P - origin) * 1e6
        start, deltas = _quantise(P_um)
        chunks = [deltas[i:i + MAX_POINTS] for i in range(0, max(len(deltas), 1), MAX_POINTS)] or [[]]
        x, y = start
        for ci, ch in enumerate(chunks):
            last = si == len(strokes_m) - 1 and ci == len(chunks) - 1
            recs.append(TemplateRecord(seg_id, si, last, flags | (F_ANCHOR if anchor else 0), glyph, confidence,
                                       t_from_ms, t_to_ms, x, y, int(round(speed_mm_s)), list(ch)))
            if ch:
                x += RES_UM * sum(d[0] for d in ch)
                y += RES_UM * sum(d[1] for d in ch)
    return recs


def decode_letter(recs: Sequence[TemplateRecord]) -> List[np.ndarray]:
    """Strokes (um, relative to the anchor if ANCHOR) from the records of one segment."""
    by_part: Dict[int, List[np.ndarray]] = {}
    for r in recs:
        by_part.setdefault(r.part, []).append(r.points_um())
    out = []
    for k in sorted(by_part):
        pieces = by_part[k]
        s = pieces[0]
        for p in pieces[1:]:
            s = np.vstack([s, p[1:]])
        out.append(s)
    return out


def bandwidth(letters: Iterable[Tuple[Sequence[np.ndarray], float]], writing_time_s: float,
              resend_factor: float = 3.0) -> Dict[str, float]:
    """Bytes and points per letter and per second of writing (CALCULATION).

    ``letters``: (strokes in m, confidence).  ``resend_factor``: each letter's
    template is sent this many times on average (predictions revised as
    recognition proceeds, SUPERSEDE).  Framing adds 4 bytes per record.
    """
    n_rec = n_pts = n_bytes = n_letters = 0
    for strokes, conf in letters:
        recs = encode_letter(strokes, seg_id=1, glyph="a", confidence=conf, t_from_ms=0, t_to_ms=1000, speed_mm_s=28)
        n_letters += 1
        n_rec += len(recs)
        n_pts += sum(len(r.deltas) + 1 for r in recs)
        n_bytes += sum(len(r.framed()) for r in recs)
    per_s = n_letters / writing_time_s
    return {"letters": n_letters, "records_per_letter": n_rec / n_letters, "points_per_letter": n_pts / n_letters,
            "bytes_per_letter": n_bytes / n_letters, "letters_per_s": per_s,
            "points_per_s": n_pts / n_letters * per_s, "bytes_per_s_once": n_bytes / n_letters * per_s,
            "bytes_per_s_with_resends": n_bytes / n_letters * per_s * resend_factor, "resend_factor": resend_factor,
            "uplink_stroke_samples_bytes_per_s": 200 * (20 + 4),
            "note": "uplink: ICD 0x02 stroke samples at 200 Hz, 20 B payload + 4 B framing"}
