/* AUTO-GENERATED by firmware/tools/gen_params.py -- DO NOT EDIT.
 * Regenerate: make -C firmware params   (after config/parameters.yaml changes)
 * Evidence status: PROPOSED DESIGN. Every value is calculated, assumed or copied
 * from a design file as cited; none is a measurement of Rev A hardware.
 *   generator: firmware/tools/gen_params.py
 *   yaml_version: 0.4.4
 *   yaml_sha16: a9d3d0016461d690
 *   estimator_selection_sha16: eace6b899bb37c3a
 *   drive_sense_sha16: 7fcbd6c40ee3b4af
 *   design_revA_sha16: 69844a9aa4e6bd48
 *   model_py_sha16: d8e582e84966892f
 *   core_py_sha16: 7b86d3e72d535bce
 *   icd_sha16: 7c379c5d77455a2f
 *   model_version: M1.0
 *   git_head: 4bccea4
 *   nominal_theta_deg: 50.0
 *   nominal_N0: 1.0
 *   evidence_status: proposed design / calculated / assumed values; no hardware measurement
 */
#ifndef PEN_PARAMS_GEN_H
#define PEN_PARAMS_GEN_H

#define PEN_PARAMS_YAML_VERSION "0.4.4"
#define PEN_PARAMS_YAML_SHA16 "a9d3d0016461d690"
#define PEN_PARAMS_MODEL_VERSION "M1.0"
#define PEN_PARAMS_YAML_VERSION_NUM (404u)
#define PEN_PARAMS_SEL_SHA16 "eace6b899bb37c3a"
#define PEN_PARAMS_DRV_SHA16 "7fcbd6c40ee3b4af"
#define PEN_PARAMS_MODEL_SHA16 "d8e582e84966892f"
#define PEN_PARAMS_CORE_SHA16 "7b86d3e72d535bce"

/* ---- Timing (ICD section 2) ---- */
#define PEN_F_PWM_HZ               (40000.0f) /* Hz; config/parameters.yaml electrical.f_pwm (calculated) */
#define PEN_F_CURRENT_HZ           (40000.0f) /* Hz; config/parameters.yaml control.f_current */
#define PEN_F_STAGE_HZ             (2000.0f) /* Hz; config/parameters.yaml control.f_stage (REQ-CTRL-001) */
#define PEN_PWM_PER_STAGE          (20) /* -; derived f_pwm / f_stage (ICD s2: every 20 PWM periods) */
#define PEN_TS_STAGE               (0.000500000024f) /* s; sim/pensim/model.py build_params(): Ts = stage_decim * dt */
#define PEN_TS_CURRENT             (2.49999994e-05f) /* s; 1 / f_current */
#define PEN_CUR_DECIM_SIM          (1) /* -; sim/pensim/model.py build_params(): cur_decim (sim steps of 25 us per current update; 1 = 40 kHz) */
#define PEN_PWM_CLOCK_HZ           (16000000.0f) /* Hz; results/electronics/drive_sense.json components.pwm_clock_hz (nRF5340 PWM base clock) */
#define PEN_PWM_COUNTERTOP         (200) /* counts; derived: centre-aligned up/down counter, 16 MHz / (2 x 40 kHz) = 200 levels (ICD s2) */
#define PEN_F_ML_HZ                (250.0f) /* Hz; config/parameters.yaml control.f_predictor; ICD s2/s5 */
#define PEN_ML_DECIM               (8) /* ticks; derived f_stage / f_predictor (ICD s2: every 8 stage ticks) */
#define PEN_F_STROKE_LOG_HZ        (200.0f) /* Hz; docs/icd.md s2/s4.3 stroke sample rate */

/* ---- Stage, lever and actuator (tip-equivalent; used by servo and tests) ---- */
#define PEN_M_EQ                   (0.0136909494f) /* kg; sim/pensim/model.py build_params(): Geometry.reduce() J_pivot/L1^2 (CAD Rev A masses; calculated) */
#define PEN_K_TIP                  (80.0f) /* N/m; config/parameters.yaml stage.k_tip (calculated) */
#define PEN_C_TIP                  (0.10465543f) /* N s/m; sim/pensim/model.py build_params(): 2 zeta_open sqrt(k_tip m_eq) */
#define PEN_M_COUPLE               (0.00449291663f) /* kg; sim/pensim/model.py build_params(): Geometry.reduce() m_mov L_cm / L1 */
#define PEN_L1                     (0.0120000001f) /* m; config/parameters.yaml stage.L1 */
#define PEN_N_LEVER                (3.16666675f) /* -; sim/pensim/model.py build_params(): L2 / L1 (config/parameters.yaml stage.L2 / stage.L1) */
#define PEN_Q_STOP                 (0.000600000028f) /* m; config/parameters.yaml stage.travel_tip_mech (mechanical stop radius at the tip) */
#define PEN_F_PRE                  (0.25f) /* N; config/parameters.yaml stage.axial_preload */
#define PEN_K_AX                   (2000.0f) /* N/m; config/parameters.yaml stage.axial_k */
#define PEN_S_MAX                  (0.000600000028f) /* m; config/parameters.yaml stage.axial_travel */
#define PEN_KF20                   (0.717000008f) /* N/A; config/parameters.yaml actuator.Kf (per axis, at the actuator; calculated) */
#define PEN_R20                    (6.0f) /* ohm; config/parameters.yaml actuator.R20 (DEC-012) */
#define PEN_L_COIL                 (0.000174999994f) /* H; config/parameters.yaml actuator.L */
#define PEN_R_BRIDGE               (0.419999987f) /* ohm; config/parameters.yaml electrical.r_bridge (DRV8212P HS+LS hot; VERIFY) */
#define PEN_R_SHUNT                (0.100000001f) /* ohm; config/parameters.yaml electrical.r_shunt */
#define PEN_I_MAX                  (0.600000024f) /* A; config/parameters.yaml actuator.i_max (software limit per axis) */
#define PEN_I_TRIP_HW              (0.800000012f) /* A; config/parameters.yaml actuator.i_trip (hardware window comparator + latch) */
#define PEN_ALPHA_CU               (0.00393000012f) /* 1/K; config/parameters.yaml actuator.alpha_cu */
#define PEN_ALPHA_B                (-0.00120000006f) /* 1/K; sim/pensim/model.py build_params(): alpha_B default (NdFeB Br tempco, assumed) */
#define PEN_RTH_COIL               (145.0f) /* K/W; config/parameters.yaml actuator.Rth_coil_amb (calculated): coil to structure through the air gaps (key name historical) */
#define PEN_CTH_COIL               (0.25f) /* J/K; config/parameters.yaml actuator.Cth_coil (assumed) */
#define PEN_RTH_STRUCT             (12.5f) /* K/W; config/parameters.yaml actuator.Rth_struct_amb (calculated): structure to ambient and hand */
#define PEN_CTH_STRUCT             (14.8999996f) /* J/K; config/parameters.yaml actuator.Cth_struct (calculated) */
#define PEN_T_STRUCT_RISE_IDLE     (5.9000001f) /* K; config/parameters.yaml actuator.T_struct_rise_idle: structure above ambient with no coil loss (electronics, hand) */
#define PEN_T_AMB                  (25.0f) /* degC; config/parameters.yaml thermal.t_ambient (assumed) */
#define PEN_V_BAT_NOM              (3.70000005f) /* V; config/parameters.yaml electrical.v_bat_nom */
#define PEN_V_BAT_MIN              (3.29999995f) /* V; config/parameters.yaml electrical.v_bat_min (actuation cut-off) */

/* ---- Current loop (40 kHz PI per axis) ---- */
#define PEN_CUR_BW_HZ              (2000.0f) /* Hz; config/parameters.yaml control.current_bw as resolved by sim/pensim/model.py build_params() (Controller.cur_bw None) */
#define PEN_KP_I                   (2.1991148f) /* V/A; sim/pensim/model.py build_params(): Kp_i = L wc_i */
#define PEN_KI_I                   (81932.7344f) /* V/(A s); sim/pensim/model.py build_params(): Ki_i = (R20 + r_bridge + r_shunt) wc_i */
#define PEN_R_LOOP_FF              (6.51999998f) /* ohm; sim/pensim/model.py build_params(): Rhat used for the R*i_ref voltage feedforward (at 20 C) */
#define PEN_CUR_R_FF               (0.0f) /* -; firmware default 0: PI with pole-zero cancellation as designed in electronics/calcs/drive_sense.py; the simulator adds R*i_ref (= 1), which overshoots 55 % with the 1-period sample-to-PWM delay (README D10) */
#define PEN_DUTY_MAX               (0.970000029f) /* -; results/electronics/drive_sense.json components.d_max (sampling window) */
#define PEN_R_LOAD_SWITCH          (0.0799999982f) /* ohm; drive_sense.json components.r_load_switch_ohm (TPS22917, shared; VERIFY) */
#define PEN_DUTY_HEADROOM          (0.949999988f) /* -; docs/icd.md s6 fault bit 6 threshold */

/* ---- Analogue sense chain (electronics/gen/design_revA.py, drive_sense.json) ---- */
#define PEN_ISNS_V_PER_A           (1.0f) /* V/A; INA241A1 G = 10 x 0.1 ohm shunt (drive_sense sense_chain.sensitivity_V_per_A) */
#define PEN_ISNS_VREF              (1.25f) /* V; REF3012 1.25 V (INA241 REF and SAADC negative input AIN4) */
#define PEN_SAADC_DIFF_FS_V        (1.20000005f) /* V; SAADC gain 1/2, internal 0.6 V reference, differential (drive_sense adc_fs_diff_v) */
#define PEN_SAADC_BITS             (12) /* bit; SAADC 12-bit mode (drive_sense adc_bits) */
#define PEN_ISNS_COUNTS_PER_A      (1706.66663f) /* count/A; derived: 2^(bits-1)/FS x V/A (differential result is signed) */
#define PEN_ISNS_OFFSET_MAX_A      (0.0250000004f) /* A; proposed plausibility bound on the pen-up offset (drive_sense offset_mA_uncal 0.25 mA + ADC offset; generous) */
#define PEN_ISNS_OFFSET_SAMPLES    (32) /* samples; proposed: centre+edge samples averaged during a coast window */
#define PEN_VBAT_DIV               (0.5f) /* -; design_revA.py R9/R10 470k/470k (VBAT_SENSE = VBAT/2) */
#define PEN_SAADC_SE_FS_V          (3.5999999f) /* V; SAADC gain 1/6 x internal 0.6 V reference (single-ended; VERIFY) */
#define PEN_NTC_R25                (10000.0f) /* ohm; design_revA.py sheet_sensing note: NTC 10k */
#define PEN_NTC_BETA               (3435.0f) /* K; design_revA.py sheet_sensing note: B25/85 ~3435 K (VERIFY part) */
#define PEN_NTC_R_PULLUP           (10000.0f) /* ohm; design_revA.py R14 10k to +3V0A (ratiometric read, REFSEL VDD/4, gain 1/4) */
#define PEN_I_HOLD_DESIGN          (0.334728032f) /* A; drive_sense.json design_point_hold_current_A (50 deg, 1 N, mu 0.15 worst direction) */
#define PEN_R_EXT_HOT              (0.579999983f) /* ohm; drive_sense.json headroom.r_ext_ohm (bridge hot + shunt + wiring) */
#define PEN_T_COIL_DESIGN          (96.6061859f) /* degC; drive_sense.json components.t_coil_design_c */

/* ---- Stage position servo (2 kHz) ---- */
#define PEN_POS_BW_HZ              (60.0f) /* Hz; config/parameters.yaml control.pos_bw as resolved by sim/pensim/model.py build_params() (Controller.pos_bw None) */
#define PEN_ZETA                   (0.699999988f) /* -; model.Controller.zeta */
#define PEN_KP                     (1865.78918f) /* N/m; sim/pensim/model.py build_params(): Kp = m_eq wc^2 - k_tip */
#define PEN_KD                     (7.22591257f) /* N s/m; sim/pensim/model.py build_params(): Kd = 2 zeta m_eq wc */
#define PEN_KI                     (140677.188f) /* N/(m s); sim/pensim/model.py build_params(): Ki = Kp wc ki_ratio */
#define PEN_D_FILT_HZ              (300.0f) /* Hz; sim/pensim/model.py build_params(): d_filt = d_filt_ratio pos_bw */
#define PEN_ALPHA_D                (0.610338867f) /* -; core.simulate(): alpha_d = 1 - exp(-2 pi d_filt Ts) */
#define PEN_FF_REF                 (1.0f) /* -; model.Controller.ff_ref */
#define PEN_FF_ACCEL               (1.0f) /* -; model.Controller.ff_accel */
#define PEN_FF_CONTACT             (0.0f) /* -; model.Controller.ff_contact = 0 (DEC-011: contact feedforward disabled by default; bench option) */
#define PEN_FFC_FC_HZ              (60.0f) /* Hz; model.Controller.ff_contact_fc (2nd-order Butterworth, DEC-011) */
#define PEN_FFC_B0                 (0.00782020763f) /* -; sim/pensim/model.py build_params(): scipy.signal.butter(2, fc, fs=f_stage) sos[0] (b0) */
#define PEN_FFC_B1                 (0.0156404153f) /* -; sim/pensim/model.py build_params(): scipy.signal.butter(2, fc, fs=f_stage) sos[0] (b1) */
#define PEN_FFC_B2                 (0.00782020763f) /* -; sim/pensim/model.py build_params(): scipy.signal.butter(2, fc, fs=f_stage) sos[0] (b2) */
#define PEN_FFC_A1                 (-1.73472571f) /* -; sim/pensim/model.py build_params(): scipy.signal.butter(2, fc, fs=f_stage) sos[0] (a1) */
#define PEN_FFC_A2                 (0.766006589f) /* -; sim/pensim/model.py build_params(): scipy.signal.butter(2, fc, fs=f_stage) sos[0] (a2) */

/* ---- Authority, Jacobian and limits ---- */
#define PEN_G_ASSIST               (1.0f) /* -; model.Controller.g_assist */
#define PEN_Q_LIM                  (0.000549999997f) /* m; model.Controller.q_lim (= yaml stage.travel_tip_ctrl 0.00055) */
#define PEN_Q_TAPER                (9.99999975e-05f) /* m; model.Controller.q_taper */
#define PEN_SLEW                   (0.0799999982f) /* m/s; model.Controller.slew */
#define PEN_AUTHORITY_TAU          (0.0500000007f) /* s; model.Controller.authority_tau */
#define PEN_ALPHA_A                (0.00995016657f) /* -; core.simulate(): alpha_a = 1 - exp(-Ts/authority_tau) */
#define PEN_GAMMA_NOM              (0.190106094f) /* -; sim/pensim/model.py build_params(): gamma = Kn sin^2(th)/(Kn sin^2(th) + k_ax) at the nominal theta (reference for tests) */
#define PEN_K_HAND_NORMAL          (800.0f) /* N/m; config/parameters.yaml hand.normal_stiffness (gamma formula) */
#define PEN_R_N_NOM                (0.400000006f) /* -; config/parameters.yaml hand.normal_stiffness / stage.axial_k: default CAL_USER v2 r_n = K_n/k_ax (docs/icd.md s1, s3 v1.3) */
#define PEN_R_N_MIN                (0.0199999996f) /* -; docs/icd.md s3 v1.3: CAL_USER r_n range 0.02-10 */
#define PEN_R_N_MAX                (10.0f) /* -; docs/icd.md s3 v1.3: CAL_USER r_n range 0.02-10 */
#define PEN_THETA_NOM              (0.87266463f) /* rad; config/parameters.yaml writing.tilt_deg (v1 CAL_USER gamma -> r_n conversion at this tilt, ICD s3) */
#define PEN_KAPPA_S                (1.0f) /* -; config/parameters.yaml stage.kappa_s via sim/pensim/model.py build_params() (DEC-007 rev.: 1 = refill slides in the carrier, lever arm L1 - s) */
#define PEN_AXIAL_COMP             (0.0f) /* -; model.Controller.axial_comp (off) */
#define PEN_AXIAL_COMP_TAU         (2.0f) /* s; model.Controller.axial_comp_tau */
#define PEN_AXIAL_COMP_MAX         (0.000300000014f) /* m; core.simulate(): axial compensation magnitude clamp 0.3e-3 */
#define PEN_LAM_MIN                (0.5f) /* -; core.simulate(): lam_hat = max(0.5, 1 - kappa s/L1) */
#define PEN_CONTACT_DF             (0.0199999996f) /* N; core.simulate(): in_contact = F_ax > F_pre + 0.02 */

/* ---- Estimators (profiles: BAL = estimator_selection selected, ASR = selected_assertive) ---- */
#define PEN_BP_DERIV_ALPHA         (0.200000003f) /* -; core.simulate() mode 2: ybpd += 0.2 (yd - ybpd) */
#define PEN_HORIZON                (0.00132957753f) /* s; sim/pensim/model.py build_params(): imu_delay + Ts/2 + servo_lag(0 with ff_ref) + 1/(2 pi cur_bw) */
#define PEN_KF_R                   (2.50000003e-11f) /* m^2; model.Controller.kf_r */
#define PEN_KF_RDAMP               (0.99900049f) /* -; sim/pensim/model.py build_params(): exp(-Ts/kf_tau_decay) */
#define PEN_KF_RH                  (0.997344375f) /* -; core.simulate(): rh = rdamp^(horizon/Ts) (constant) */
#define PEN_KF_WGAIN               (0.00166666671f) /* -; sim/pensim/model.py build_params(): Ts/kf_tau_w */
#define PEN_KF_WMIN                (15.707963f) /* rad/s; sim/pensim/model.py build_params(): 2 pi kf_wmin_hz */
#define PEN_KF_WMAX                (87.964592f) /* rad/s; sim/pensim/model.py build_params(): 2 pi kf_wmax_hz */
#define PEN_CONF_NIS_HI            (6.0f) /* -; model.Controller.conf_nis_hi */
#define PEN_NIS_ALPHA              (0.00999999978f) /* -; core.simulate(): nis_f += 0.01 (0.5 nis_sum - nis_f) */
#define PEN_KF_AMP_MIN             (1.99999995e-05f) /* m; core.simulate(): frequency adaptation only if oscillator amplitude > 2e-5 */
#define PEN_KF_P0_POS              (9.99999994e-09f) /* m^2; core.simulate(): reinit P diag */
#define PEN_KF_P0_VEL              (9.99999975e-05f) /* (m/s)^2; core.simulate(): reinit P diag */
#define PEN_KF_P0_ACC              (0.00999999978f) /* (m/s^2)^2; core.simulate(): reinit P diag */
#define PEN_KF_P0_OSC              (1.00000001e-07f) /* m^2; core.simulate(): reinit P diag */
#define PEN_KF_P_INIT              (9.99999997e-07f) /* -; core.simulate(): initial P = 1e-6 I (before first reinit) */
#define PEN_F_GATE_WIDTH           (1.5f) /* Hz; model.Controller.f_gate_width */
#define PEN_BAL_KF_QJ              (0.100000001f) /* m^2/s^5; results/sim/estimator_selection.json kfosc.selected kf_qj=0.1 */
#define PEN_BAL_KF_QT              (9.99999994e-09f) /* m^2/s; results/sim/estimator_selection.json kfosc.selected kf_qt=1e-08 */
#define PEN_BAL_KF_W0              (43.982296f) /* rad/s; results/sim/estimator_selection.json kfosc.selected kf_w0_hz=7.0 */
#define PEN_BAL_F_GATE             (7.5f) /* Hz; results/sim/estimator_selection.json kfosc.selected f_gate=7.5 (default CAL_USER f_gate) */
#define PEN_BAL_KF_Q00             (1.56249997e-19f) /* SI; core._kf_step(): Q entries precomputed in double precision */
#define PEN_BAL_KF_Q01             (7.81249986e-16f) /* SI; core._kf_step(): Q entries precomputed in double precision */
#define PEN_BAL_KF_Q02             (2.08333329e-12f) /* SI; core._kf_step(): Q entries precomputed in double precision */
#define PEN_BAL_KF_Q11             (4.16666658e-12f) /* SI; core._kf_step(): Q entries precomputed in double precision */
#define PEN_BAL_KF_Q12             (1.25000001e-08f) /* SI; core._kf_step(): Q entries precomputed in double precision */
#define PEN_BAL_KF_Q22             (4.99999987e-05f) /* SI; core._kf_step(): Q entries precomputed in double precision */
#define PEN_BAL_KF_QOSC            (4.99999998e-12f) /* SI; core._kf_step(): Q entries precomputed in double precision */
#define PEN_ASR_KF_QJ              (0.100000001f) /* m^2/s^5; results/sim/estimator_selection.json kfosc.selected_assertive kf_qj=0.1 */
#define PEN_ASR_KF_QT              (9.99999994e-09f) /* m^2/s; results/sim/estimator_selection.json kfosc.selected_assertive kf_qt=1e-08 */
#define PEN_ASR_KF_W0              (43.982296f) /* rad/s; results/sim/estimator_selection.json kfosc.selected_assertive kf_w0_hz=7.0 */
#define PEN_ASR_F_GATE             (7.5f) /* Hz; results/sim/estimator_selection.json kfosc.selected_assertive f_gate=7.5 (default CAL_USER f_gate) */
#define PEN_ASR_KF_Q00             (1.56249997e-19f) /* SI; core._kf_step(): Q entries precomputed in double precision */
#define PEN_ASR_KF_Q01             (7.81249986e-16f) /* SI; core._kf_step(): Q entries precomputed in double precision */
#define PEN_ASR_KF_Q02             (2.08333329e-12f) /* SI; core._kf_step(): Q entries precomputed in double precision */
#define PEN_ASR_KF_Q11             (4.16666658e-12f) /* SI; core._kf_step(): Q entries precomputed in double precision */
#define PEN_ASR_KF_Q12             (1.25000001e-08f) /* SI; core._kf_step(): Q entries precomputed in double precision */
#define PEN_ASR_KF_Q22             (4.99999987e-05f) /* SI; core._kf_step(): Q entries precomputed in double precision */
#define PEN_ASR_KF_QOSC            (4.99999998e-12f) /* SI; core._kf_step(): Q entries precomputed in double precision */
#define PEN_BAL_BP1_B0             (0.986759782f) /* -; sim/pensim/model.py build_params(): butter(2, bp_lo=6.0 Hz, high) sos (b0); results/sim/estimator_selection.json bpf.selected */
#define PEN_BAL_BP1_B1             (-1.97351956f) /* -; sim/pensim/model.py build_params(): butter(2, bp_lo=6.0 Hz, high) sos (b1); results/sim/estimator_selection.json bpf.selected */
#define PEN_BAL_BP1_B2             (0.986759782f) /* -; sim/pensim/model.py build_params(): butter(2, bp_lo=6.0 Hz, high) sos (b2); results/sim/estimator_selection.json bpf.selected */
#define PEN_BAL_BP1_A1             (-1.97334421f) /* -; sim/pensim/model.py build_params(): butter(2, bp_lo=6.0 Hz, high) sos (a1); results/sim/estimator_selection.json bpf.selected */
#define PEN_BAL_BP1_A2             (0.973694861f) /* -; sim/pensim/model.py build_params(): butter(2, bp_lo=6.0 Hz, high) sos (a2); results/sim/estimator_selection.json bpf.selected */
#define PEN_BAL_BP2_B0             (0.000346041343f) /* -; sim/pensim/model.py build_params(): butter(2, bp_hi=12.0 Hz, low) sos (b0); results/sim/estimator_selection.json bpf.selected */
#define PEN_BAL_BP2_B1             (0.000692082685f) /* -; sim/pensim/model.py build_params(): butter(2, bp_hi=12.0 Hz, low) sos (b1); results/sim/estimator_selection.json bpf.selected */
#define PEN_BAL_BP2_B2             (0.000346041343f) /* -; sim/pensim/model.py build_params(): butter(2, bp_hi=12.0 Hz, low) sos (b2); results/sim/estimator_selection.json bpf.selected */
#define PEN_BAL_BP2_A1             (-1.94669759f) /* -; sim/pensim/model.py build_params(): butter(2, bp_hi=12.0 Hz, low) sos (a1); results/sim/estimator_selection.json bpf.selected */
#define PEN_BAL_BP2_A2             (0.948081732f) /* -; sim/pensim/model.py build_params(): butter(2, bp_hi=12.0 Hz, low) sos (a2); results/sim/estimator_selection.json bpf.selected */
#define PEN_BAL_BP_GAIN_COMP       (1.3107183f) /* -; sim/pensim/model.py build_params(): 1/|H(bp_tune_hz=7.0)|; results/sim/estimator_selection.json bpf.selected */
#define PEN_ASR_BP1_B0             (0.986759782f) /* -; sim/pensim/model.py build_params(): butter(2, bp_lo=6.0 Hz, high) sos (b0); results/sim/estimator_selection.json bpf.selected_assertive */
#define PEN_ASR_BP1_B1             (-1.97351956f) /* -; sim/pensim/model.py build_params(): butter(2, bp_lo=6.0 Hz, high) sos (b1); results/sim/estimator_selection.json bpf.selected_assertive */
#define PEN_ASR_BP1_B2             (0.986759782f) /* -; sim/pensim/model.py build_params(): butter(2, bp_lo=6.0 Hz, high) sos (b2); results/sim/estimator_selection.json bpf.selected_assertive */
#define PEN_ASR_BP1_A1             (-1.97334421f) /* -; sim/pensim/model.py build_params(): butter(2, bp_lo=6.0 Hz, high) sos (a1); results/sim/estimator_selection.json bpf.selected_assertive */
#define PEN_ASR_BP1_A2             (0.973694861f) /* -; sim/pensim/model.py build_params(): butter(2, bp_lo=6.0 Hz, high) sos (a2); results/sim/estimator_selection.json bpf.selected_assertive */
#define PEN_ASR_BP2_B0             (0.000346041343f) /* -; sim/pensim/model.py build_params(): butter(2, bp_hi=12.0 Hz, low) sos (b0); results/sim/estimator_selection.json bpf.selected_assertive */
#define PEN_ASR_BP2_B1             (0.000692082685f) /* -; sim/pensim/model.py build_params(): butter(2, bp_hi=12.0 Hz, low) sos (b1); results/sim/estimator_selection.json bpf.selected_assertive */
#define PEN_ASR_BP2_B2             (0.000346041343f) /* -; sim/pensim/model.py build_params(): butter(2, bp_hi=12.0 Hz, low) sos (b2); results/sim/estimator_selection.json bpf.selected_assertive */
#define PEN_ASR_BP2_A1             (-1.94669759f) /* -; sim/pensim/model.py build_params(): butter(2, bp_hi=12.0 Hz, low) sos (a1); results/sim/estimator_selection.json bpf.selected_assertive */
#define PEN_ASR_BP2_A2             (0.948081732f) /* -; sim/pensim/model.py build_params(): butter(2, bp_hi=12.0 Hz, low) sos (a2); results/sim/estimator_selection.json bpf.selected_assertive */
#define PEN_ASR_BP_GAIN_COMP       (1.3107183f) /* -; sim/pensim/model.py build_params(): 1/|H(bp_tune_hz=7.0)|; results/sim/estimator_selection.json bpf.selected_assertive */
#define PEN_MLG_BP1_B0             (0.993357837f) /* -; docs/icd.md s5 v1.1: realised disturbance band-pass 3-15 Hz; scipy butter(2, 3 Hz, high, fs=2 kHz) */
#define PEN_MLG_BP1_B1             (-1.98671567f) /* -; docs/icd.md s5 v1.1: realised disturbance band-pass 3-15 Hz; scipy butter(2, 3 Hz, high, fs=2 kHz) */
#define PEN_MLG_BP1_B2             (0.993357837f) /* -; docs/icd.md s5 v1.1: realised disturbance band-pass 3-15 Hz; scipy butter(2, 3 Hz, high, fs=2 kHz) */
#define PEN_MLG_BP1_A1             (-1.98667157f) /* -; docs/icd.md s5 v1.1: realised disturbance band-pass 3-15 Hz; scipy butter(2, 3 Hz, high, fs=2 kHz) */
#define PEN_MLG_BP1_A2             (0.986759782f) /* -; docs/icd.md s5 v1.1: realised disturbance band-pass 3-15 Hz; scipy butter(2, 3 Hz, high, fs=2 kHz) */
#define PEN_MLG_BP2_B0             (0.000537169748f) /* -; docs/icd.md s5 v1.1: realised disturbance band-pass 3-15 Hz; scipy butter(2, 15 Hz, low, fs=2 kHz) */
#define PEN_MLG_BP2_B1             (0.0010743395f) /* -; docs/icd.md s5 v1.1: realised disturbance band-pass 3-15 Hz; scipy butter(2, 15 Hz, low, fs=2 kHz) */
#define PEN_MLG_BP2_B2             (0.000537169748f) /* -; docs/icd.md s5 v1.1: realised disturbance band-pass 3-15 Hz; scipy butter(2, 15 Hz, low, fs=2 kHz) */
#define PEN_MLG_BP2_A1             (-1.93338025f) /* -; docs/icd.md s5 v1.1: realised disturbance band-pass 3-15 Hz; scipy butter(2, 15 Hz, low, fs=2 kHz) */
#define PEN_MLG_BP2_A2             (0.935528934f) /* -; docs/icd.md s5 v1.1: realised disturbance band-pass 3-15 Hz; scipy butter(2, 15 Hz, low, fs=2 kHz) */

/* ---- Sensing and housing-position fusion ---- */
#define PEN_HALL_ICT_COMP          (1.99999999e-06f) /* m/A; config/parameters.yaml sensing.hall_i_crosstalk_tip (sim compensation; firmware uses CAL_HALL T/A) */
#define PEN_HALL_DELAY             (9.99999975e-05f) /* s; config/parameters.yaml sensing.hall_delay */
#define PEN_OPT_DELAY              (0.00200000009f) /* s; config/parameters.yaml sensing.opt_delay */
#define PEN_IMU_DELAY              (0.00100000005f) /* s; config/parameters.yaml sensing.imu_delay */
#define PEN_FUSION_LAG_TICKS       (2) /* ticks; core.simulate(): lag_t = max(0, (opt_delay - imu_delay) // stage_decim) in sim steps */
#define PEN_IMU_LEAK_TAU           (0.5f) /* s; core.simulate(): vimu *= (1 - dti/0.5) leaky velocity */
#define PEN_IMU_RATE_HZ            (3840.0f) /* Hz; config/parameters.yaml sensing.imu_rate (ICD s2 v1.2: 3.84 kHz ODR, 7.68 kHz available) */
#define PEN_OPT_RATE_HZ            (1000.0f) /* Hz; config/parameters.yaml sensing.opt_rate (ICD s2 v1.3: 1 kHz) */
#define PEN_OPT_LIFT_MAX           (0.00079999998f) /* m; model.build_params default sensing.opt_lift_max */
#define PEN_FUSION_RING            (1024) /* ticks; core.simulate(): rb_pimu length */

/* ---- Safety thresholds (docs/icd.md s5, s6; requirements; proposed values marked) ---- */
#define PEN_HEADROOM_TIME          (0.0500000007f) /* s; docs/icd.md s6 fault bit 6: duty > 0.95 for > 50 ms */
#define PEN_OPT_INVALID_TIME       (0.300000012f) /* s; docs/icd.md s6 fault bit 4: optical invalid > 300 ms */
#define PEN_HALL_DETECT_BUDGET     (0.00499999989f) /* s; docs/icd.md s6: frozen Hall detected within 5 ms */
#define PEN_HALL_STUCK_TICKS       (8) /* ticks; proposed: 8 bit-identical x/y/z readings (4 ms < 5 ms budget); needs >= 1 LSB noise (VERIFY EXP-B04) */
#define PEN_HALL_JUMP_MAX          (9.99999975e-05f) /* m; proposed: |second difference| residual bound (physical accel <= ~330 m/s^2 -> 83 um/tick^2) */
#define PEN_HALL_RANGE_MARGIN      (4.99999987e-05f) /* m; proposed: |q| > q_stop + margin is implausible */
#define PEN_PENUP_TIMEOUT          (5.0f) /* s; docs/icd.md s6: soft-fault shutdown waits for pen-up, timeout 5 s */
#define PEN_RAMP_DOWN_TIME         (0.0299999993f) /* s; REQ-SAF-004: ramp actuator current down over >= 30 ms */
#define PEN_VBAT_RECOVER           (3.45000005f) /* V; proposed: low-battery clear threshold (hysteresis) */
#define PEN_VBAT_DEBOUNCE          (0.200000003f) /* s; proposed: low-battery debounce */
#define PEN_VBAT_LPF_TAU           (0.0500000007f) /* s; proposed: VBAT measurement low-pass */
#define PEN_T_COIL_LIMIT           (120.0f) /* degC; REQ-THM-002 coil hot-spot limit */
#define PEN_T_DERATE_START         (100.0f) /* degC; proposed: authority cap starts falling */
#define PEN_T_FAULT                (115.0f) /* degC; proposed: over-temperature fault (bit 2), 5 degC margin for observer error */
#define PEN_T_RECOVER              (90.0f) /* degC; proposed: over-temperature clear threshold */
#define PEN_T_NTC_GAIN             (0.100000001f) /* -; proposed: coil-node correction toward the coil-former NTC per 100 Hz update (NTC preferred when valid; time constant 0.1 s) */
#define PEN_T_RES_GAIN             (0.0500000007f) /* -; proposed: resistance-thermometry gain per valid 100 Hz observer update (used when the NTC is invalid) */
#define PEN_R_EST_I_MIN            (0.100000001f) /* A; proposed: minimum |I| for resistance estimate */
#define PEN_R_EST_DI_MAX           (0.0199999996f) /* A; proposed: max current change over a tick for 'steady' */
#define PEN_OC_CLEAR_RETRIES       (3.0f) /* -; proposed: latch clear attempts before the fault is permanent */
#define PEN_ML_RATE_MAX            (0.0500000007f) /* m/s; docs/icd.md s5 v1.1 rule 3: slew-limit d_hat at 50 mm/s */
#define PEN_ML_HORIZON             (0.00600000005f) /* s; docs/icd.md s5 v1.1: h = 6 ms after the acquisition time of the newest sample */
#define PEN_ML_WINDOW              (64) /* samples; docs/icd.md s5 v1.1: W = 64 x (dx, dy) at 250 Hz (f_est dropped) */
#define PEN_ML_APOST_WINDOW        (0.200000003f) /* s; docs/icd.md s5 v1.1 rule 4: running RMS over 200 ms */
#define PEN_ML_FALLBACK_HOLD       (1.0f) /* s; docs/icd.md s5 v1.1 rule 4: fall back to the Kalman estimate for >= 1 s */
#define PEN_ML_REAL_SETTLE         (0.300000012f) /* s; proposed: a-posteriori evaluation suspended 300 ms after the realised-disturbance band-pass is reset */
#define PEN_ML_STALE_TIME          (0.00800000038f) /* s; docs/icd.md s5 v1.2: expiry = t_acq_newest + 8 ms (REQ-SAF-003, REQ-ML-002) */
#define PEN_ML_FADE_TIME           (0.0199999996f) /* s; REQ-SAF-003: fall back smoothly within 20 ms */
#define PEN_ML_C_MIN               (0.0f) /* -; docs/icd.md s5 v1.2 rule 5: normalised confidence c^ = byte/255 below c_min is a rejected inference (0-1; default 0) */
#define PEN_ML_C_FULL              (1.0f) /* -; docs/icd.md s5 v1.2 rule 5: ML share scaled by min(1, c^/c_full) (0-1; default 1; an uncalibrated model reports 255) */
#define PEN_ML_DHAT_FS_UM          (3276.69995f) /* um; docs/icd.md s5 v1.2 rule 1: output saturation = int16 d_hat (0.1 um) at full scale, +/-3.2767 mm */
#define PEN_ML_CONF_SLEW_TIME      (0.0199999996f) /* s; docs/icd.md s5 v1.2 rule 5: the scaled ML share reaches its new value within 20 ms */
#define PEN_ML_TRIP_COUNT          (5) /* trips; proposed: fault bit 8 when > 5 guard trips within ML_TRIP_WINDOW */
#define PEN_ML_TRIP_WINDOW         (10.0f) /* s; proposed */
#define PEN_PENUP_DEBOUNCE         (0.0199999996f) /* s; proposed: contact must be absent 20 ms to declare pen-up */

#endif /* PEN_PARAMS_GEN_H */
