"""Bill of materials of the recommended board, and the proposed evidence-ledger rows.

Catalogue data are MFR with the ledger ids proposed in
results/board/evidence_rows.csv (AMF-90...99, HAP-51...54, PAT-26...27).
Custom parts are PROPOSED DESIGN.  Prices are given only where a price was
seen on the vendor page on the retrieval date; no cost class is claimed for
the whole board.
"""
from __future__ import annotations

import csv
import os

RETRIEVED = "2026-09-28"

BOM = [
    # item, qty, part, key data, ledger, url, note
    {"item": "Head magnet", "qty": 1, "part": "K&J Magnetics D88-N52, NdFeB cylinder 12.7 x 12.7 mm, axial",
     "key_data": "N52, Br max 1.48 T, 12.07 g, 80 C max", "ledger": "AMF-90",
     "url": "https://www.kjmagnetics.com/d88-n52-neodymium-cylinder-magnet", "price_seen": "USD 4.78 each (vendor page, 2026-09-28)"},
    {"item": "Pen magnet (pen add-on, in the heel of the Rev H front sleeve)", "qty": 1,
     "part": "K&J Magnetics D42-N52, NdFeB disc 6.35 x 3.17 mm, axial", "key_data": "N52, Br max 1.48 T, 0.75 g, 80 C max",
     "ledger": "AMF-91", "url": "https://www.kjmagnetics.com/d42-n52-neodymium-disc-magnet", "price_seen": "USD 0.52 each (qty 1-49, 2026-09-28)"},
    {"item": "Stepper motors (CoreXY A and B)", "qty": 2, "part": "StepperOnline 17HS19-2004S1 NEMA 17",
     "key_data": "0.59 N m holding, 2.0 A, 1.40 ohm, 3.0 mH, 82 g cm2, 0.40 kg", "ledger": "AMF-92",
     "url": "https://www.omc-stepperonline.com/download/17HS19-2004S1.pdf", "price_seen": ""},
    {"item": "Stepper drivers", "qty": 2, "part": "ADI/Trinamic TMC2209 (on a carrier or on the main PCB)",
     "key_data": "2 A RMS, 2.8 A peak, 4.75-29 V, StealthChop2, StallGuard4, UART", "ledger": "AMF-93",
     "url": "https://www.analog.com/media/en/technical-documentation/data-sheets/tmc2209_datasheet_rev1.09.pdf", "price_seen": ""},
    {"item": "Linear guides", "qty": "2 x MGN12 (Y, 330 mm) + 1 x MGN9 (X, 300 mm)", "part": "HIWIN MGN12H and MGN9H blocks and rails",
     "key_data": "MGN12H: H 13 mm, C 3.72 kN, block 0.054 kg, rail 0.65 kg/m; MGN9H: H 10 mm, C 2.55 kN, block 0.026 kg, rail 0.38 kg/m",
     "ledger": "AMF-94", "url": "https://s3.amazonaws.com/www.motionusa.com/hiwin/2025/MG%20Series-2025.pdf", "price_seen": ""},
    {"item": "Hall sensors (ring on the carriage)", "qty": 8, "part": "TI TMAG5170A2 (VSSOP-8)",
     "key_data": "+/-75/150/300 mT, 12-bit, 20 ksps single axis, 10 MHz SPI, noise X/Y 160 uT RMS (28 uT with 32x averaging)",
     "ledger": "AMF-95", "url": "https://www.ti.com/lit/ds/symlink/tmag5170.pdf", "price_seen": ""},
    {"item": "Z-lift servo (guidance level and off)", "qty": 1, "part": "ROBOTIS DYNAMIXEL XL330-M288-T",
     "key_data": "0.52 N m stall at 5 V (1.47 A), 12-bit absolute encoder, current-based position mode, 18 g",
     "ledger": "AMF-96", "url": "https://emanual.robotis.com/docs/en/dxl/x/xl330-m288/", "price_seen": ""},
    {"item": "Power supply (external, desktop)", "qty": 1, "part": "MEAN WELL GST60A24-P1J",
     "key_data": "24 V 2.5 A 60 W, 90.5 % typ. efficiency, IEC/UL/EN 62368-1", "ledger": "AMF-97",
     "url": "https://www.meanwell.com/Upload/PDF/GST60A/GST60A-SPEC.PDF", "price_seen": ""},
    {"item": "MCU with Bluetooth LE", "qty": 1, "part": "Nordic nRF54L15 (module or QFN40 on the main PCB)",
     "key_data": "128 MHz Cortex-M33, 256 KB RAM, BLE; same family as the pen", "ledger": "AMF-44 (existing row)",
     "url": "https://www.nordicsemi.com/Products/nRF54L15", "price_seen": ""},
    {"item": "Belts, pulleys, idlers", "qty": "2 x ~1.3 m GT2 6 mm belt, 2 x 20T pulleys, 6 idlers", "part": "GT2 2 mm pitch (to select; Gates PowerGrip GT2 class)",
     "key_data": "belt stiffness not published by the maker: ASSUMPTION 15-40 kN per unit strain", "ledger": "none (ASSUMPTION)",
     "url": "https://www.gates.com/us/en/search.p.9231-000000-000000.html", "price_seen": ""},
    {"item": "Variant only: diametric head magnet", "qty": "(1)", "part": "K&J Magnetics D8X0DIA, 12.7 x 25.4 mm, N42, diametric",
     "key_data": "Br max 1.32 T, 24.14 g", "ledger": "AMF-99",
     "url": "https://www.kjmagnetics.com/d8x0dia-neodymium-diametric-cylinder-magnet", "price_seen": "USD 8.05 each (2026-09-28)"},
]

CUSTOM = [
    {"part": "Cover glass (writing surface)", "dims_mm": "300 x 360 x 2.0", "material": "chemically strengthened soda-lime or aluminosilicate glass, anti-shatter PET film on the underside", "process": "cut and edge-ground by a glass supplier", "why": "2 mm keeps the magnetic gap small; 0.18 mm sag under a 10 N hand (CALC)"},
    {"part": "Base plate", "dims_mm": "300 x 400 x 3", "material": "aluminium 5052 or 6061", "process": "laser or waterjet cut, tapped", "why": "stiff, non-magnetic ground for the rails"},
    {"part": "Side frame and glass support rim", "dims_mm": "walls 3 mm, height 48 mm", "material": "aluminium sheet or 20 x 20 extrusion; PA12 corners", "process": "cut + 3D-printed corners", "why": "carries the glass on its edges; encloses all moving parts"},
    {"part": "Gantry beam (X)", "dims_mm": "300 x 20 x 10 rectangular tube", "material": "aluminium 6063", "process": "cut, drilled", "why": "carries the MGN9 rail and the carriage"},
    {"part": "Carriage plate and Z parallelogram", "dims_mm": "60 x 50 x 3 plate; two 40 mm links", "material": "aluminium plate; PA12 or POM links; brass pins", "process": "CNC / 3D print", "why": "non-magnetic; keeps the head magnet vertical over 12 mm of lift"},
    {"part": "Head magnet cup with aluminium spacer", "dims_mm": "cup OD 16, spacer >= 20 mm to the steel rail", "material": "aluminium 6061", "process": "turned", "why": "keeps the magnet's pull on the steel rail below ~0.8 N (CALC image-dipole bound)"},
    {"part": "Hall ring PCB", "dims_mm": "ring OD 52, ID 20, 1.0 thick, 8 x TMAG5170 at radius 22", "material": "FR4, 4 layers", "process": "PCB assembly", "why": "measures the pen magnet relative to the head"},
    {"part": "Main PCB", "dims_mm": "100 x 60", "material": "FR4, 4 layers", "process": "PCB assembly", "why": "nRF54L15, 2 x TMC2209, 24 V -> 5 V/3.3 V buck, servo TTL bus, e-stop input, fan-less"},
    {"part": "Pen heel boss (Rev H team)", "dims_mm": "pocket 6.45 dia x 3.3 deep, axis along the pen axis", "material": "PEEK front sleeve (Rev H)", "process": "machined or moulded; magnet bonded", "why": "a small keel under the fixed front sleeve holds the D42 magnet 3.8 mm above the paper and about 16.5 mm behind the ball at 50 deg, outside the nose envelope (ASSUMPTION to confirm in Rev H CAD)"},
    {"part": "Writing underlay and paper stop", "dims_mm": "0.2 PET sheet; L-shaped corner stop 2 mm high", "material": "PET; PA12", "process": "cut / 3D print", "why": "a consistent writing feel on glass; registers printed practice sheets"},
    {"part": "Arm-rest wedge", "dims_mm": "300 x 80, 0 -> 50 high", "material": "PU foam in a PA12 shell", "process": "moulded / printed", "why": "the writing surface is ~50 mm above the desk"},
]

HEADER = ["id", "topic", "citation", "year", "doi_or_url", "source_type", "evidence_class", "access_level",
          "task_or_setup", "participants_or_bench", "comparator", "key_quantitative_findings", "units_and_conditions",
          "locator", "limitations", "relevance_to_design", "transferability", "transferability_reason",
          "design_implication", "retrieved", "search_query", "stream", "lead_verification"]


def _row(**kw):
    r = {k: "" for k in HEADER}
    r.update(kw)
    r.setdefault("retrieved", RETRIEVED)
    if not r["retrieved"]:
        r["retrieved"] = RETRIEVED
    return r


def evidence_rows() -> list:
    na = "not applicable (manufacturer data; test method not published)"
    return [
        _row(id="AMF-90", topic="Guidance board head magnet: NdFeB N52 cylinder 12.7 x 12.7 mm (K&J D88-N52)",
             citation="K&J Magnetics. D88-N52 product page (1/2 x 1/2 inch cylinder, N52).", year="n.d.",
             doi_or_url="https://www.kjmagnetics.com/d88-n52-neodymium-cylinder-magnet", source_type="manufacturer",
             evidence_class="manufacturer statement", access_level="full text",
             task_or_setup="Retailer/manufacturer product specification", participants_or_bench=na, comparator="Supreme Magnets 12 x 12 mm N52 (7.32 kg pull, surface 6619 G, USD 3.92)",
             key_quantitative_findings="12.7 x 12.7 mm (+/-0.1 mm); N52; axially magnetised; Ni-Cu-Ni; 12.07 g; pull force case 1 8.2 kg, case 2 9.24 kg; surface field 6619 G; Br max 14 800 G; max operating temperature 80 C; USD 4.78 each (page, 2026-09-28).",
             units_and_conditions="Vendor values; pull force per vendor test cases", locator="Product page specification table",
             limitations="Br given as a maximum; the design uses the N52 lower bound 1.45 T (AMF-28); no tolerance on magnetisation angle.",
             relevance_to_design="Sets the head field; magpylib force maps (board.magnetics)", transferability="high",
             transferability_reason="Catalogue part used as is", design_implication="Baseline head magnet; keep >= 20 mm from steel; 80 C limit is far above the head's temperature",
             search_query="WebFetch https://www.kjmagnetics.com/d88-n52-neodymium-cylinder-magnet", stream="AMF"),
        _row(id="AMF-91", topic="Pen add-on magnet for the guidance board: NdFeB N52 disc 6.35 x 3.17 mm (K&J D42-N52); ring alternative R422-N52",
             citation="K&J Magnetics. D42-N52 and R422-N52 product pages.", year="n.d.",
             doi_or_url="https://www.kjmagnetics.com/d42-n52-neodymium-disc-magnet ; https://www.kjmagnetics.com/r422-n52-neodymium-ring-magnet",
             source_type="manufacturer", evidence_class="manufacturer statement", access_level="full text",
             task_or_setup="Product specifications", participants_or_bench=na, comparator="R422-N52 ring for a nose-mounted option",
             key_quantitative_findings="D42-N52: 6.35 x 3.17 mm (+/-0.1 mm), N52, axial, Ni-Cu-Ni, 0.75 g, pull 1.29 kg (case 1), 2.08 kg (case 2), surface field 5233 G, Br max 14 800 G, 80 C max, USD 0.52 each (qty 1-49). R422-N52: 6.35 OD x 3.17 ID x 3.17 mm, N52, through thickness, 0.57 g, pull 1.01/1.57 kg, Br max 14 800 G, USD 0.46.",
             units_and_conditions="Vendor values", locator="Product page specification tables",
             limitations="Br as maximum; the fit in the Rev H front sleeve heel is an ASSUMPTION to be checked in Rev H CAD.",
             relevance_to_design="The only pen add-on the board needs; it is also what the board senses", transferability="high",
             transferability_reason="Catalogue part", design_implication="Bond the D42 in a heel boss of the FIXED front sleeve (not the moving nose, whose actuator carries only 0.21 N continuously)",
             search_query="WebSearch K&J ring magnet 1/4 x 1/8; WebFetch product pages", stream="AMF"),
        _row(id="AMF-92", topic="Stage motor: NEMA 17 hybrid stepper 17HS19-2004S1",
             citation="STEPPERONLINE 17HS19-2004S1 datasheet (Oyostepper-branded copy of the full datasheet, PDF created 2017-04-26, modified 2019-11-05).", year="2017",
             doi_or_url="https://www.oyostepper.com/images/upload/File/17HS19-2004S1.pdf ; https://www.omc-stepperonline.com/download/17HS19-2004S1.pdf",
             source_type="datasheet", evidence_class="manufacturer statement", access_level="full text",
             task_or_setup="Specification table and drawing", participants_or_bench=na, comparator="",
             key_quantitative_findings="Bipolar, 2.80 V, 2.00 A/phase, 1.40 ohm +/-10 % at 25 C, 3.00 mH +/-20 % at 1 kHz, holding torque 0.59 N m, 1.8 deg, step accuracy +/-5 %, rotor inertia 82 g cm2, 0.40 kg, 42 x 48 mm, 5 mm shaft, temperature rise max 80 C (standstill, 2 phases energised), insulation class B.",
             units_and_conditions="Manufacturer table", locator="Page 1 specification table",
             limitations="No torque-speed curve on the copy read; the curve used is a CALC from R, L, k_t (board.stage). The omc-stepperonline URL returned an HTML page to the script.",
             relevance_to_design="Stage acceleration, top speed, power", transferability="high", transferability_reason="Catalogue part",
             design_implication="Run at 1.2 A RMS with standby reduction: about 4 W copper per motor while moving (CALC)",
             search_query="WebSearch StepperOnline 17HS19-2004S1 datasheet; curl oyostepper PDF", stream="AMF"),
        _row(id="AMF-93", topic="Stepper driver IC: ADI/Trinamic TMC2209",
             citation="TRINAMIC Motion Control GmbH & Co. KG. TMC2209 Datasheet, Rev. 1.03 (2019-06-26), copy hosted by chipdip; current ADI revision 1.09 not retrievable (HTTP 503 / empty reply on 2026-09-28).", year="2019",
             doi_or_url="https://static.chipdip.ru/lib/619/DOC010619079.pdf ; https://www.analog.com/media/en/technical-documentation/data-sheets/tmc2209_datasheet_rev1.09.pdf",
             source_type="datasheet", evidence_class="manufacturer statement", access_level="full text",
             task_or_setup="Features and description (page 1-2)", participants_or_bench=na, comparator="TMC5130 used by KATIB (HAP-51)",
             key_quantitative_findings="2-phase stepper up to 2.8 A peak, 2 A RMS; 4.75-29 V; STEP/DIR with 8/16/32/64 microsteps, 256 by interpolation; StealthChop2 'no-noise' chopper; SpreadCycle; StallGuard4 load/stall detection; CoolStep up to 75 % energy saving; RDSon LS and HS 170 mOhm typ at 25 C; single-wire UART; integrated pulse generator; QFN.",
             units_and_conditions="Typical values", locator="Page 1 features; page 2 header",
             limitations="Older revision read; 'inaudible' is a manufacturer claim, not a measured noise level.",
             relevance_to_design="Quiet stage drive; stall detection for safety and homing", transferability="high", transferability_reason="Catalogue IC",
             design_implication="Use StealthChop at low speed; StallGuard as one input of the fault monitor; measure noise (EXP-G04)",
             search_query="WebSearch TMC2209 datasheet; curl mirror PDF", stream="AMF"),
        _row(id="AMF-94", topic="Miniature linear guides for the stage: HIWIN MGN9H / MGN12H",
             citation="HIWIN. Linear Guideway MG Series catalogue (G99TE24-2410), 2025 edition as hosted by Motion Industries.", year="2025",
             doi_or_url="https://s3.amazonaws.com/www.motionusa.com/hiwin/2025/MG%20Series-2025.pdf",
             source_type="manufacturer", evidence_class="manufacturer statement", access_level="full text",
             task_or_setup="Dimension, load and stiffness tables", participants_or_bench=na, comparator="",
             key_quantitative_findings="MGN9H: assembly H 10 mm, block W 20, L 39.9 mm, C 2.55 kN, C0 4.02 kN, block 0.026 kg, rail 9 x 6.5 mm, 0.38 kg/m. MGN12H: H 13, W 27, L 45.4 mm, C 3.72 kN, C0 5.88 kN, block 0.054 kg, rail 12 x 8 mm, 0.65 kg/m. Radial stiffness MGN9H 86 (Z0) / 165 (Z1) N/um; MGN12H 105 / 182 N/um.",
             units_and_conditions="Catalogue values", locator="Table of MGN-C/MGN-H dimensions (p. 89); Table 2-4-7 radial stiffness",
             limitations="Rails and blocks are steel: they attract the head magnet (keep >= 20 mm) and distort its field (calibrate in place).",
             relevance_to_design="Stage guides, moving mass", transferability="high", transferability_reason="Catalogue part",
             design_implication="MGN12 for Y, MGN9 for X; aluminium spacer >= 20 mm between the head magnet and the X rail",
             search_query="WebSearch HIWIN MG series catalogue MGN9H MGN12H; curl PDF", stream="AMF"),
        _row(id="AMF-95", topic="3-axis Hall sensor for the carriage ring: TI TMAG5170",
             citation="Texas Instruments. TMAG5170 High-Precision 3D Linear Hall-Effect Sensor With SPI, data sheet SBASAF4 (September 2021).", year="2021",
             doi_or_url="https://www.ti.com/lit/ds/symlink/tmag5170.pdf", source_type="datasheet", evidence_class="manufacturer statement", access_level="full text",
             task_or_setup="Electrical characteristics tables", participants_or_bench=na, comparator="DRV5055 (AMF-70), TMR2615 (AMF-71)",
             key_quantitative_findings="A1: +/-25/50/100 mT; A2: +/-75/150/300 mT; 12-bit ADC; 20 ksps single axis; conversion 50 us single channel at CONV_AVG 000 (+25 us per extra channel), 825 us at 32x averaging; 10 MHz SPI with CRC; RMS noise A2 X/Y 160 uT (fast) and 28 uT (32x), Z 72 and 13 uT; A1 X/Y 140 and 24 uT, Z 61 and 11 uT; total linear error +/-2.6 % max at 25 C; sensitivity drift +/-2.8 % max; active current 3.4 mA; 2.3-5.5 V; VSSOP-8 3 x 3 mm; -40 to 150 C.",
             units_and_conditions="25 C unless stated", locator="Section 6 Electrical characteristics (pp. 5-9)",
             limitations="Noise at intermediate averaging inferred (square-root rule, CALC); gain error must be calibrated in the system.",
             relevance_to_design="Pen localisation precision and loop rate", transferability="high", transferability_reason="Catalogue part",
             design_implication="8 x TMAG5170A2 at 22 mm radius, 8x averaging, 1 kHz frame; one-time calibration per unit and Z height",
             search_query="WebSearch TMAG5170 datasheet; WebFetch PDF (saved, pdftotext)", stream="AMF"),
        _row(id="AMF-96", topic="Z-lift actuator for the board head: ROBOTIS DYNAMIXEL XL330-M288-T",
             citation="ROBOTIS. XL330-M288-T e-Manual (specifications).", year="n.d.",
             doi_or_url="https://emanual.robotis.com/docs/en/dxl/x/xl330-m288/", source_type="manufacturer", evidence_class="manufacturer statement", access_level="full text",
             task_or_setup="Specification table", participants_or_bench=na, comparator="",
             key_quantitative_findings="Cortex-M0+ 64 MHz; contactless absolute encoder 12 bit (4096 pulse/rev); 3.7-6.0 V (5 V recommended); stall torque 0.52 N m at 5 V and 1.47 A; no-load 103 rev/min at 5 V; 18 g; 20 x 34 x 26 mm; gear ratio 288.4:1; current, velocity, position, extended position, current-based position and PWM modes; TTL multidrop bus 9600 bps-4 Mbps.",
             units_and_conditions="Manufacturer values", locator="Specifications section", limitations="Holding power and unpowered back-drive behaviour not stated.",
             relevance_to_design="Sets the guidance level (head height) and the off state", transferability="high", transferability_reason="Catalogue part",
             design_implication="Use current-based position mode (a force-limited lift); check that it back-drives under the retraction spring when unpowered (EXP-G06)",
             search_query="WebFetch ROBOTIS e-manual XL330-M288", stream="AMF"),
        _row(id="AMF-97", topic="External 24 V power supply for the board: MEAN WELL GST60A24-P1J",
             citation="MEAN WELL. GST60A series specification, file GST60A-SPEC 2026-04-03.", year="2026",
             doi_or_url="https://www.meanwell.com/Upload/PDF/GST60A/GST60A-SPEC.PDF", source_type="datasheet", evidence_class="manufacturer statement", access_level="full text",
             task_or_setup="Specification table", participants_or_bench=na, comparator="",
             key_quantitative_findings="GST60A24-P1J: 24 V, 2.5 A (0-2.5 A), 60 W, ripple and noise 150 mVp-p max, efficiency 90.5 % typ; safety approvals UL62368-1, CSA C22.2 No. 62368-1, TUV BS EN/EN62368-1 and others; EMC class B conducted and radiated emission.",
             units_and_conditions="Manufacturer values", locator="Specification table (ORDER NO. GST60A24-P1J column); safety standards row",
             limitations="Standby power figure (0.075 W) seen only in a search summary, not read in the PDF.",
             relevance_to_design="Keeps mains out of the board (SELV 24 V)", transferability="high", transferability_reason="Certified catalogue adaptor",
             design_implication="Board budget ~8 W average, 18 W peak (CALC) against 60 W", search_query="WebSearch GST60A24 datasheet; curl PDF", stream="AMF"),
        _row(id="AMF-98", topic="EMR digitiser availability and construction (for the sensing choice)",
             citation="Wacom Co., Ltd. EMR Pen Technology (components catalogue, current as of April 2010); Wacom. 'After 5 Years: The New IC Enables The Best Pen Experience' (web article, undated); Hanvon Ugee. 'EMR Pen Touch/Handwriting Module (with Screen)' business product page.", year="2010; n.d.",
             doi_or_url="http://www.wacom.jp/jp/customercare/download/catalogue/pdf/0507_EMR_Pen_Technology_E.pdf ; https://www.wacom.com/en-us/discover/pride-of-wacom/article-5 ; https://business.hanvonugee.com/en/screen/135",
             source_type="manufacturer", evidence_class="manufacturer statement", access_level="full text",
             task_or_setup="Component catalogue and product pages", participants_or_bench=na, comparator="Carriage Hall ring (board.sensing)",
             key_quantitative_findings="Wacom (2010): battery-free resonant pens (5.5-14 mm dia.), sensor boards 6.0-14.0 inch (e.g. SU5E-13W01AS-00X, active area 288.1 x 180.8 mm, total thickness 2.7 mm incl. controller, 42 g, UART/USB), resolution 0.01 mm, accuracy +/-0.4 mm, reading height 5-14 mm, 133 points/s; controller ICs W8001-W8006 offered to OEMs. Wacom article: 'we refer to the combination of sensor boards ... and magnetic sheets, as a digitizer'. Hanvon Ugee: EMR modules for integration, accuracy +/-0.254 mm, up to 200 points/s, battery-free pen, USB.",
             units_and_conditions="Manufacturer statements", locator="Wacom catalogue: 'Sensor board' and 'General specification' tables; Wacom article paragraph on digitizer composition; Hanvon page specification list",
             limitations="2010 catalogue: current availability to a small company must be confirmed with Wacom; pen-coil spare parts not verified.",
             relevance_to_design="EMR modules can be bought, but the digitiser includes a magnetic sheet that would sit between the head and the pen magnet", transferability="medium",
             transferability_reason="Availability shown; compatibility with a moving magnet under it is not",
             design_implication="Do not use EMR under a magnetic head; the board senses the pen magnet with its own Hall ring",
             search_query="WebSearch EMR digitizer module OEM; Wacom EMR magnetic sheet; WebFetch pages", stream="AMF"),
        _row(id="AMF-99", topic="Diametric head magnet for the rotating-head variant: K&J D8X0DIA",
             citation="K&J Magnetics. D8X0DIA product page (1/2 x 1 inch diametric cylinder, N42).", year="n.d.",
             doi_or_url="https://www.kjmagnetics.com/d8x0dia-neodymium-diametric-cylinder-magnet", source_type="manufacturer", evidence_class="manufacturer statement", access_level="full text",
             task_or_setup="Product specification", participants_or_bench=na, comparator="D88-N52 axial (AMF-90)",
             key_quantitative_findings="12.7 x 25.4 mm (+/-0.1 mm); N42; diametrically magnetised; Ni-Cu-Ni; 24.14 g; pull 10.13 kg (case 1), 13.31 kg (case 2); surface field 7157 G; Br max 13 200 G; 80 C max; USD 8.05 each (2026-09-28).",
             units_and_conditions="Vendor values", locator="Product page", limitations="N42 only in this size at this vendor.",
             relevance_to_design="Variant i-c (force direction by rotating the magnet)", transferability="high", transferability_reason="Catalogue part",
             design_implication="Keep as the upgrade path if the normal pull of the axial head is disliked in EXP-G05",
             search_query="WebSearch K&J diametric 1/2 inch; WebFetch product page", stream="AMF"),
        _row(id="HAP-51", topic="3 drawing guidance: KATIB hardware (permanent magnet on a 2-DOF parallel robot under the writing surface)",
             citation="Korres G, Eid M (2020) KATIB: Haptic-Visual Guidance for Handwriting. In: Haptics: Science, Technology, Applications (EuroHaptics 2020), Springer LNCS, chapter 10.1007/978-3-030-58147-3_31 (author copy read; page numbers not checked)", year="2020",
             doi_or_url="https://doi.org/10.1007/978-3-030-58147-3_31 ; https://static1.squarespace.com/static/6107a7d096fb9b6abeaed5e8/t/611265e9c387a702e789fd36/1628595699033/KATIB+Haptic-visual+Guidance+for+Handwriting.pdf",
             source_type="conference", evidence_class="physical bench study", access_level="full text",
             task_or_setup="Stylus with stacked NdFeB N42 magnets (5 x 5 mm and 2 x 2 mm) over a 4 mm resistive touchscreen; N42 5 x 5 mm magnet on the end effector of a 2-DOF parallel manipulator (two NEMA17 steppers with 5:1 planetary gearboxes, uStepper: ATmega328 + Trinamic TMC5130 + Broadcom AEAT8800-Q24 encoder, 1800 Hz); the end-effector magnet is rotated 180 deg by a geared micro DC motor to switch the force on or off; ANSYS magnetostatics",
             participants_or_bench="bench demonstrations; no participants in this paper", comparator="dePENd, Langerak (related work)",
             key_quantitative_findings="Workspace 80 x 60 mm (arms 100 mm, +/-45 deg per motor); peak tangential force 0.43 N at 2-5 mm displacement (maximum around 3.5 mm) through 4 mm glass (ANSYS); stylus tilt up to 40 deg from the normal 'would result in a negligible tangential force' (as written); full-guidance playback RMS error 2.73 mm; guidance rendered at 1800 Hz.",
             units_and_conditions="N, mm, Hz; simulation for forces", locator="Sections 3.2 (hardware), 4.1 (workspace), 4.2 (magnetostatics, Fig. 4), 4.2.2 (friction, Fig. 5)",
             limitations="Forces simulated, not measured; small workspace; the meaning of the tilt statement is ambiguous in the text.",
             relevance_to_design="Closest prior build of a permanent-magnet carriage under a writing surface; stepper-driven, quiet drivers", transferability="high",
             transferability_reason="Same physical principle and part classes", design_implication="A permanent-magnet head on a stepper stage is buildable and gives ~0.4 N through 4 mm; our heel magnet and thinner cover give more (CALC)",
             search_query="WebSearch Korres Eid KATIB patent contactless magnetic haptic handwriting; WebFetch author PDF", stream="HAP"),
        _row(id="HAP-52", topic="Commercial desktop haptic device for option (iii) and for bench studies: 3D Systems Touch",
             citation="3D Systems. Phantom Touch haptic device product page (specifications).", year="n.d.",
             doi_or_url="https://www.3dsystems.com/haptics-devices/touch", source_type="manufacturer", evidence_class="manufacturer statement", access_level="full text",
             task_or_setup="Product specification", participants_or_bench=na, comparator="Pantograph Mk-II (HAP-53)",
             key_quantitative_findings="Force feedback workspace '~17 W x 13.7 H x 6.5 D in' (as displayed; earlier user-guide values differ); footprint ~168 x 203 mm; ~1.42 kg; nominal position resolution > 450 dpi (~0.055 mm); backdrive friction 0.26 N; maximum exertable force 3.3 N (nominal orthogonal arm position); continuous exertable force (24 h) > 0.88 N; stiffness X > 1.26, Y > 2.31, Z > 1.02 N/mm; apparent mass at tip ~45 g; force feedback x, y, z; digital encoders; USB, 1 kHz.",
             units_and_conditions="Manufacturer values", locator="Specifications section",
             limitations="Workspace value on the current page conflicts with older documents; price not seen.",
             relevance_to_design="A ready research rig for guidance-law studies with a pen adapter (EXP-G05 phase A)", transferability="medium",
             transferability_reason="Stylus device, not paper writing; forces and feel differ from the board",
             design_implication="Use a Touch with a Rev H pen adapter to test partial/full guidance on people before the board exists",
             search_query="WebSearch 3D Systems Touch specifications; WebFetch product page", stream="HAP"),
        _row(id="HAP-53", topic="Research planar haptic device (five-bar): Pantograph Mk-II",
             citation="Campion G, Wang Q, Hayward V (2005) The Pantograph Mk-II: a haptic instrument. Proc. IEEE/RSJ IROS 2005, pp. 723-728", year="2005",
             doi_or_url="https://cim.mcgill.ca/~haptic/pub/GC-QW-VH-IROS-05.pdf", source_type="conference", evidence_class="physical bench study", access_level="full text",
             task_or_setup="Two-DOF five-bar parallel mechanism, link lengths [63 75 75 63 25] mm, two Maxon RE-25 coreless DC motors (graphite brushes), optical encoders (65 536 CPR class), Quanser Q4 card; frequency response with an accelerometer",
             participants_or_bench="bench", comparator="",
             key_quantitative_findings="Workspace about 66 x 104 mm (figure); accurate tactile signals DC-400 Hz; flat response 40-300 Hz; resolves displacements of the order of 10 um (5-6 encoder ticks per 50 um); structural resonance 400-500 Hz; bearing backlash of several ticks when unloaded.",
             units_and_conditions="Hz, um", locator="Abstract; Sections II (components), III (kinematics), IV (Figs. 7-8), V",
             limitations="Small finger-pad device; no force values extracted; not tied to a pen.",
             relevance_to_design="Shows the bandwidth and resolution a direct-drive five-bar reaches (option iii)", transferability="medium",
             transferability_reason="Linkage class matches; our workspace is 2-4x larger", design_implication="A pen-scale pantograph can be stiff and fast; the cost is tethering and a linkage beside the hand",
             search_query="WebSearch Campion Wang Hayward Pantograph Mk-II; WebFetch PDF", stream="HAP"),
        _row(id="HAP-54", topic="Electromagnet array under a tabletop acting on a magnet on the hand (option ii): FingerFlux",
             citation="Weiss M, Wacharamanotham C, Voelker S, Borchers J (2011) FingerFlux: near-surface haptic feedback on tabletops. Proc. UIST '11 (Santa Barbara), ACM", year="2011",
             doi_or_url="https://doi.org/10.1145/2047196.2047277 ; https://hci.rwth-aachen.de/publications/weiss2011b.pdf", source_type="conference", evidence_class="physical human study", access_level="full text",
             task_or_setup="Madgets table: 19 x 12 grid of electromagnets (19.5 mm dia x 34.5 mm, 3500 turns on iron cores) driven at 40 V DC and 255 mA, individually controllable polarity and strength, under an LCD; permanent magnets (10 mm dia x 2 mm) taped to the fingertip",
             participants_or_bench="user studies (numbers not extracted here)", comparator="no haptic feedback",
             key_quantitative_findings="Users felt vibration patterns up to 35 mm above the table; haptic feedback significantly reduced drifting when operating buttons without looking; electrical input per magnet 40 V x 0.255 A = 10.2 W (CALC from the paper's values).",
             units_and_conditions="mm; V; mA", locator="Abstract; Prototype design section; Discussion",
             limitations="Forces not reported in the text read; finger magnet, not a pen; iron-core grid is heavy and hot.",
             relevance_to_design="Evidence that a coil grid can be felt, and of its power cost (option ii)", transferability="low",
             transferability_reason="Different effector and purpose; no force data", design_implication="A no-moving-parts coil grid would need ~165 channels at ~10 W each for A4: not chosen",
             search_query="WebSearch FingerFlux Weiss 2011; curl RWTH PDF", stream="HAP"),
        _row(id="PAT-26", topic="Electromagnetic attraction of a stylus tip that varies with position (Microsoft)",
             citation="Microsoft Technology Licensing LLC (inventors Autio H. A., Majander K. M.). Haptic interaction via magnetic force. US 11,036,326 B2, granted 2021-06-15; filed 2019-07-02. Status: Active, expires 2039-07-10 (as displayed on Google Patents on 2026-09-28; not verified in official register).", year="2021",
             doi_or_url="https://patents.google.com/patent/US11036326B2/en", source_type="patent", evidence_class="patent disclosure", access_level="full text",
             task_or_setup="Touch-screen device with a position sensor for a magnetically attractable stylus tip, an electromagnetic circuit whose attraction force is proportional to its current, and a drive circuit that varies the current with a haptic-force signal (e.g. variable friction/resistance); permanent-magnet tip and reversed current (repulsion) in embodiments",
             participants_or_bench="n/a", comparator="PAT-11",
             key_quantitative_findings="Claim 1 (as displayed): position sensor for the tip; electromagnetic circuit carrying a current and forming, in proportion to it, a magnetic force attracting the tip to the sensory surface; drive circuit varying the force by varying the current in dependence on a haptic-force signal.",
             units_and_conditions="n/a", locator="Claim 1; description (Google Patents text)", limitations="Claims read from Google Patents text, not the USPTO image; not legal advice.",
             relevance_to_design="Close to the electromagnet options (i-b, ii); our recommended head uses a permanent magnet moved by a stage, not a current-proportional electromagnetic force", transferability="medium",
             transferability_reason="Touch-screen framing; attorney to assess scope", design_implication="Freedom-to-operate review before any electromagnet head; the permanent-magnet head is a design-around candidate",
             search_query="WebSearch patent electromagnet array under touchscreen stylus magnet haptic; WebFetch Google Patents", stream="PAT"),
        _row(id="PAT-27", topic="Passive guidance by steerable nonholonomic transmissions (cobots)",
             citation="Northwestern University (inventors Colgate J. E., Peshkin M. A.). Cobots. US 5,952,796 A, granted 1999-09-14; filed 1997-10-28. Status: Expired - Lifetime (as displayed on Google Patents on 2026-09-28).", year="1999",
             doi_or_url="https://patents.google.com/patent/US5952796A/en", source_type="patent", evidence_class="patent disclosure", access_level="full text",
             task_or_setup="Manipulator whose joints are coupled by variable (steerable) transmissions adjusted by small steering motors from a force sensor, implementing software virtual surfaces passively",
             participants_or_bench="n/a", comparator="",
             key_quantitative_findings="Claim 1 (as summarised on Google Patents): manipulator with joints, variable transmission elements coupling the joint motions, small steering motors adjusting the ratios under computer control, a force sensor for operator intent, and a control computer implementing virtual surfaces; cobots are intrinsically passive (they steer motion that the person supplies).",
             units_and_conditions="n/a", locator="Claim 1 and abstract (Google Patents)", limitations="Claim text from a summary display; expired.",
             relevance_to_design="Prior art (free to use) for a passive guidance principle: a steered wheel at the pen could guide using the paper as ground, without a board", transferability="low",
             transferability_reason="Industrial manipulators; no pen embodiment", design_implication="Future handheld idea only; not studied",
             search_query="WebSearch Colgate Peshkin cobot patent US5952796; WebFetch Google Patents", stream="PAT"),
    ]


def write_evidence_rows(path: str) -> int:
    rows = evidence_rows()
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=HEADER)
        w.writeheader()
        for r in rows:
            w.writerow(r)
    return len(rows)
