/*
 * tcn_int8.c - plain C99 int8 reference kernels for the TCN disturbance predictor.
 * EVIDENCE STATUS: model trained on SIMULATION / synthetic data only.
 *
 * Bit-exact with the Python integer reference ml/quantize.py::run_int8
 * (checked by ml/export_c.py with test_host.c on host and, optionally, on an
 * emulated Cortex-M33).  CMSIS-NN mapping: tcn_fc_s8() == arm_fully_connected_s8()
 * with input_dims.n = batch, filter_offset = 0, per-tensor quantisation.
 */
#include <math.h>
#include <stddef.h>

#include "tcn_int8.h"
#include "tcn_weights.h"   /* generated by ml/export_c.py */

/* ---- CMSIS-NN compatible fixed-point helpers (arm_nnsupportfunctions.h) ---- */
static inline int32_t tcn_doubling_high_mult(int32_t m1, int32_t m2)
{
    /* rounding offset for a right shift of 31; (int64) product, arithmetic shift */
    const int64_t prod = (int64_t)m1 * (int64_t)m2 + ((int64_t)1 << 30);
    return (int32_t)(prod >> 31);
}

static inline int32_t tcn_divide_by_power_of_two(int32_t dividend, int32_t exponent)
{
    const int32_t remainder_mask = (int32_t)((1u << exponent) - 1u);
    const int32_t remainder = remainder_mask & dividend;
    int32_t result = dividend >> exponent;
    int32_t threshold = remainder_mask >> 1;
    if (result < 0) {
        threshold++;
    }
    if (remainder > threshold) {
        result++;
    }
    return result;
}

int32_t tcn_requantize(int32_t val, int32_t mult, int32_t shift)
{
    const int32_t left = shift > 0 ? shift : 0;
    const int32_t right = shift > 0 ? 0 : -shift;
    return tcn_divide_by_power_of_two(tcn_doubling_high_mult(val * (1 << left), mult), right);
}

/* ---- kernels ---- */
/* batch rows of n_in int8 inputs -> batch rows of c_out int8 outputs */
static void tcn_fc_s8(const int8_t *in, int32_t batch, const tcn_fc_params_t *p, int8_t *out)
{
    for (int32_t b = 0; b < batch; ++b) {
        const int8_t *x = in + (size_t)b * (size_t)p->n_in;
        for (int32_t o = 0; o < p->c_out; ++o) {
            const int8_t *w = p->w + (size_t)o * (size_t)p->n_in;
            /* bias_folded = bias + in_offset * sum(w): identical integer result, one MLA per MAC */
            int32_t acc = p->bias_folded[o];
            for (int32_t i = 0; i < p->n_in; ++i) {
                acc += (int32_t)w[i] * (int32_t)x[i];
            }
            acc = tcn_requantize(acc, p->mult, p->shift) + p->out_offset;
            if (acc < p->act_min) {
                acc = p->act_min;
            }
            if (acc > p->act_max) {
                acc = p->act_max;
            }
            out[(size_t)b * (size_t)p->c_out + (size_t)o] = (int8_t)acc;
        }
    }
}

/* last layer: int8 inputs -> int16 output in 0.1 um (no activation) */
static void tcn_out_s16(const int8_t *in, int16_t out[2])
{
    for (int32_t o = 0; o < 2; ++o) {
        const int8_t *w = TCN_OUT_W + (size_t)o * (size_t)TCN_OUT_N_IN;
        int32_t acc = TCN_OUT_BF[o];
        for (int32_t i = 0; i < TCN_OUT_N_IN; ++i) {
            acc += (int32_t)w[i] * (int32_t)in[i];
        }
        acc = tcn_requantize(acc, TCN_OUT_MULT, TCN_OUT_SHIFT);
        if (acc > 32767) {
            acc = 32767;
        }
        if (acc < -32767) {
            acc = -32767;
        }
        out[o] = (int16_t)acc;
    }
}

uint32_t tcn_scratch_bytes(void)
{
    return (uint32_t)(TCN_SCRATCH_A + TCN_SCRATCH_B);
}

void tcn_run_q(const int8_t in[TCN_W][TCN_CIN], int16_t out_q[2], int8_t *scratch)
{
    int8_t *buf[2] = {scratch, scratch + TCN_SCRATCH_A};
    const int8_t *src = &in[0][0];
    int32_t len = TCN_W;
    int32_t k = 0;
    for (int32_t l = 0; l < TCN_NLEVELS; ++l) {
        len /= 2;                                   /* one output per (older, newer) pair */
        tcn_fc_s8(src, len, &TCN_LEVELS[l], buf[k]);
        src = buf[k];
        k ^= 1;
    }
    tcn_fc_s8(src, 1, &TCN_HEAD, buf[k]);           /* hidden FC + ReLU */
    tcn_out_s16(buf[k], out_q);
}

static inline int8_t tcn_q8(float v, uint32_t *st)
{
    if (!(v == v) || v > 3.0e38f || v < -3.0e38f) {  /* NaN / Inf */
        *st |= TCN_ST_INPUT_NAN;
        return 0;
    }
    float t = floorf(v + 0.5f);
    if (t > 127.0f) {
        t = 127.0f;
        *st |= TCN_ST_INPUT_CLIPPED;
    }
    if (t < -127.0f) {
        t = -127.0f;
        *st |= TCN_ST_INPUT_CLIPPED;
    }
    return (int8_t)t;
}

uint32_t tcn_quantize_window(const float dp_um[TCN_W][2], float f_est_hz, int8_t q[TCN_W][TCN_CIN])
{
    uint32_t st = 0u;
    uint32_t stf = 0u;
    const int8_t qf = tcn_q8((f_est_hz - TCN_F_REF_HZ) * TCN_F_INV_SCALE, &stf);
    for (int32_t k = 0; k < TCN_W; ++k) {
        q[k][0] = tcn_q8(dp_um[k][0] * TCN_IN_INV_SCALE, &st);
        q[k][1] = tcn_q8(dp_um[k][1] * TCN_IN_INV_SCALE, &st);
        q[k][2] = qf;
    }
    return st | (stf & TCN_ST_INPUT_NAN);
}

uint32_t tcn_predict(const float dp_um[TCN_W][2], float f_est_hz, float dhat_um[2], int8_t *scratch)
{
    int8_t q[TCN_W][TCN_CIN];
    int16_t o[2];
    uint32_t st = tcn_quantize_window(dp_um, f_est_hz, q);
    tcn_run_q((const int8_t (*)[TCN_CIN])q, o, scratch);
    if (o[0] == 32767 || o[0] == -32767 || o[1] == 32767 || o[1] == -32767) {
        st |= TCN_ST_OUTPUT_SAT;
    }
    dhat_um[0] = (float)o[0] * TCN_OUT_LSB_UM;
    dhat_um[1] = (float)o[1] * TCN_OUT_LSB_UM;
    return st;
}

uint32_t tcn_model_hash_low32(void)
{
    return TCN_MODEL_HASH_LOW32;
}
