/*
 * tcn_int8.h - int8 inference of the causal TCN disturbance predictor
 * (docs/icd.md section 5).  Plain C99 reference kernels.
 *
 * EVIDENCE STATUS: the model is trained on SIMULATION / synthetic data only.
 * It has never seen a human recording; see ml/model_card.md before use.
 *
 * Contract: input = the last 64 housing page-displacement increments dp (x, y)
 * in um at 250 Hz (oldest first); output = predicted disturbance d_hat (x, y)
 * at t + 6 ms, int16 in 0.1 um (the research-log unit of dhat_x/dhat_y,
 * docs/icd.md s4.2), or float um from tcn_predict().
 *
 * Input channels per sample, TCN_CIN, come from the generated tcn_model.h:
 *   TCN_CIN == 2: dp_x, dp_y         ICD s5 v1.1 and later (no f_est).  This is
 *                                    the exported model, tcn_s_nofest.
 *   TCN_CIN == 3: dp_x, dp_y, f_est  ICD s5 v1.0: the Kalman phase-rate estimate
 *                                    in Hz, broadcast over the window
 *                                    (tcn_s; python3 -m ml.export_c --model tcn_s).
 * The API below is the same for both.  f_est_hz is used only when TCN_CIN == 3.
 * When TCN_CIN == 2 it is ignored: it is neither read into the window nor
 * checked for NaN/Inf, so pass 0.0f.
 *
 * Confidence: the ICD s5 v1.2 output struct carries a confidence byte (u8), and
 * guard rule (5) scales the ML authority by min(1, confidence / c_full) and
 * rejects confidence < c_min.  This model has no confidence output, so no
 * calibrated confidence exists.  Its model card sets c_min = 0 and c_full = 1
 * until a confidence is calibrated on held-out writers (EXP-E01).  An adapter
 * that fills the byte must report TCN_CONFIDENCE_UNCALIBRATED (255) for every
 * inference.  Rule (5) then has no effect whether c_full is read in byte or in
 * normalised units, whereas a byte of 0 would remove all ML authority.
 * Rejections are signalled by the TCN_ST_* status bits, not by the confidence.
 *
 * Structure: 6 tree levels (a causal dilated TCN, kernel 2, dilations 1..32,
 * evaluated at the newest sample), a hidden FC head and an int16 output layer.
 * Every level is one fully connected layer over contiguous (older, newer)
 * channel pairs (NHWC), so each call of tcn_fc_s8() can be replaced by
 * arm_fully_connected_s8() of CMSIS-NN with the same parameters (per-tensor
 * multiplier/shift, filter_offset 0, input_offset = -zero_point_in).
 * Requantisation is bit-identical to CMSIS-NN arm_nn_requantize().
 *
 * Files: tcn_model.h (generated; TCN_CIN, model name and hash, scratch size) is
 * included here; tcn_weights.h (generated parameters) is included by tcn_int8.c
 * only.  Both are written by ml/export_c.py from the same quantised model and
 * check each other at compile time.
 *
 * Build notes: compile with -ffp-contract=off so the float -> int8 input
 * quantiser rounds exactly like the Python reference (ml/quantize.py).
 * The functions are reentrant: all state lives in caller-provided buffers.
 */
#ifndef TCN_INT8_H
#define TCN_INT8_H

#include <stdint.h>

#include "tcn_model.h"   /* GENERATED by ml/export_c.py */

#ifdef __cplusplus
extern "C" {
#endif

#define TCN_W 64          /* samples per window (256 ms at 250 Hz) */
#define TCN_NLEVELS 6

#if !defined(TCN_CIN) || (TCN_CIN != 2 && TCN_CIN != 3)
#error "tcn_model.h must define TCN_CIN as 2 (dp_x, dp_y) or 3 (dp_x, dp_y, f_est)"
#endif

/* Confidence byte an adapter reports for this uncalibrated model (see above). */
#define TCN_CONFIDENCE_UNCALIBRATED 255u

/* One fully connected int8 layer (CMSIS-NN arm_fully_connected_s8 semantics). */
typedef struct {
    const int8_t *w;      /* [c_out][n_in], symmetric int8 (zero point 0) */
    const int32_t *bias;  /* [c_out], scale = s_in * s_w (the bias CMSIS-NN expects) */
    const int32_t *bias_folded; /* bias + in_offset * sum(w row): exact, used by the plain-C loop */
    int32_t n_in;         /* inputs per output row (2 * channels for tree levels) */
    int32_t c_out;
    int32_t in_offset;    /* = -input zero point */
    int32_t out_offset;   /* = output zero point */
    int32_t mult;         /* Q31 requantisation multiplier (per tensor) */
    int32_t shift;        /* TFLite convention: > 0 left shift, < 0 right shift */
    int32_t act_min;      /* ReLU folded in: act_min = output zero point */
    int32_t act_max;
} tcn_fc_params_t;

/* Status bits returned by tcn_quantize_window() and tcn_predict() (inputs for the ML guard). */
#define TCN_ST_INPUT_NAN      0x01u  /* a NaN/Inf input (dp; f_est only if TCN_CIN == 3) was replaced by 0 */
#define TCN_ST_INPUT_CLIPPED  0x02u  /* |dp| > 400 um per sample (normal during fast strokes) */
#define TCN_ST_OUTPUT_SAT     0x04u  /* |d_hat| reached the int16 limit (3.2767 mm) */

/* Scratch bytes needed by tcn_run_q() (ping-pong activation buffers); = TCN_SCRATCH_BYTES. */
uint32_t tcn_scratch_bytes(void);

/* Integer core: in = int8 window [64][TCN_CIN] (oldest first), out = int16 [2] in 0.1 um.
 * scratch must hold tcn_scratch_bytes() bytes. */
void tcn_run_q(const int8_t in[TCN_W][TCN_CIN], int16_t out_q[2], int8_t *scratch);

/* float -> int8 input quantiser (same float32 arithmetic as ml/quantize.py).
 * f_est_hz: used only when TCN_CIN == 3; ignored (not read, not checked) when TCN_CIN == 2. */
uint32_t tcn_quantize_window(const float dp_um[TCN_W][2], float f_est_hz, int8_t q[TCN_W][TCN_CIN]);

/* Convenience: quantise, run, dequantise.  dhat_um[2] in um.  Returns status bits.
 * f_est_hz as for tcn_quantize_window(): pass 0.0f when TCN_CIN == 2. */
uint32_t tcn_predict(const float dp_um[TCN_W][2], float f_est_hz, float dhat_um[2], int8_t *scratch);

/* Low 32 bits of the SHA-256 of the quantised parameters (event 0x0005 argument). */
uint32_t tcn_model_hash_low32(void);

/* Exposed for unit tests: CMSIS-NN compatible requantisation. */
int32_t tcn_requantize(int32_t val, int32_t mult, int32_t shift);

#ifdef __cplusplus
}
#endif
#endif /* TCN_INT8_H */
