/*
 * tcn_model.h - GENERATED by ml/export_c.py; do not edit.
 * EVIDENCE STATUS: SIMULATION / synthetic data.  Trained only on synthetic handwriting and
 * synthetic tremor; never validated on a person.  See ml/model_card.md.
 * model: tcn_s_nofest  inputs per sample: dp_x, dp_y  (docs/icd.md s5 contract v1.1: no f_est input)
 * sha256(quantised parameters) = eebeafdddf00ec305404846e7953b2cad20af625996e2c12407f4d02a57d81f6
 * Included by tcn_int8.h.  The parameters are in tcn_weights.h (included by tcn_int8.c only).
 */
#ifndef TCN_MODEL_H
#define TCN_MODEL_H

#define TCN_MODEL_NAME "tcn_s_nofest"
#define TCN_CIN 2   /* input channels per sample: dp_x, dp_y */
#define TCN_MODEL_HASH_LOW32 0xa57d81f6u   /* event 0x0005 argument */
#define TCN_SCRATCH_BYTES 448   /* = tcn_scratch_bytes() */

#endif /* TCN_MODEL_H */
