/*
 * test_host.c - compares the C int8 TCN with the Python integer reference
 * (ml/quantize.py::run_int8) on generated test vectors.  Built and run by
 * ml/export_c.py; also compiles for the Cortex-M33 QEMU harness (TCN_BAREMETAL).
 * EVIDENCE STATUS: vectors come from SIMULATION / synthetic data.
 *
 * Exit code 0 when every output is bit-exact.
 */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#include "tcn_int8.h"
#include "test_vectors.h"   /* generated by ml/export_c.py */

static int8_t g_scratch[2048];

static int32_t absdiff(int32_t a, int32_t b) { return a > b ? a - b : b - a; }

#ifdef TCN_BAREMETAL
extern uint32_t tcn_bench_ticks(void (*fn)(void), uint32_t reps);
extern uint32_t tcn_bench_loop_ticks(uint32_t n);
static const int8_t (*g_bench_in)[TCN_CIN];
static int16_t g_bench_out[2];
static void bench_once(void) { tcn_run_q(g_bench_in, g_bench_out, g_scratch); }
#endif

int main(int argc, char **argv)
{
    int32_t n_bad = 0, max_d = 0, n = 0;
    if (tcn_scratch_bytes() > sizeof g_scratch) {
        printf("scratch too small\n");
        return 2;
    }
    /* 1. integer path on embedded vectors */
    for (int32_t i = 0; i < TV_N_INT; ++i) {
        int16_t o[2];
        tcn_run_q(tv_int_in[i], o, g_scratch);
        for (int32_t j = 0; j < 2; ++j) {
            const int32_t d = absdiff(o[j], tv_int_out[i][j]);
            if (d > max_d) max_d = d;
            if (d != 0) n_bad++;
            n++;
        }
    }
    printf("int_vectors n=%ld mismatches=%ld max_abs_diff_lsb=%ld\n", (long)n, (long)n_bad, (long)max_d);
    /* 2. float API: quantiser + core + dequantiser */
    int32_t n_bad_f = 0, max_df = 0, nf = 0;
    for (int32_t i = 0; i < TV_N_F; ++i) {
        int8_t q[TCN_W][TCN_CIN];
        int16_t o[2];
        float dh[2];
        (void)tcn_quantize_window(tv_f_dp[i], tv_f_fest[i], q);
        tcn_run_q((const int8_t (*)[TCN_CIN])q, o, g_scratch);
        (void)tcn_predict(tv_f_dp[i], tv_f_fest[i], dh, g_scratch);
        for (int32_t j = 0; j < 2; ++j) {
            const int32_t d = absdiff(o[j], tv_f_out[i][j]);
            const float back = (float)o[j] * 0.1f;
            if (d > max_df) max_df = d;
            if (d != 0 || back != dh[j]) n_bad_f++;
            nf++;
        }
    }
    printf("float_vectors n=%ld mismatches=%ld max_abs_diff_lsb=%ld\n", (long)nf, (long)n_bad_f, (long)max_df);
    /* 3. requantisation unit cases */
    int32_t n_bad_r = 0;
    for (int32_t i = 0; i < TV_N_RQ; ++i) {
        if (tcn_requantize(tv_rq[i][0], tv_rq[i][1], tv_rq[i][2]) != tv_rq[i][3]) n_bad_r++;
    }
    printf("requantize_cases n=%ld mismatches=%ld\n", (long)TV_N_RQ, (long)n_bad_r);
    /* 4. optional large binary file: "TCNV", u32 N, N x (int8[64*3], int16[2]) little-endian */
    int32_t n_bad_b = 0, max_db = 0, nb = 0;
#ifndef TCN_BAREMETAL
    if (argc > 1) {
        FILE *f = fopen(argv[1], "rb");
        char magic[4];
        uint32_t cnt = 0;
        if (!f || fread(magic, 1, 4, f) != 4 || fread(&cnt, 4, 1, f) != 1) {
            printf("cannot read %s\n", argv[1]);
            return 3;
        }
        for (uint32_t i = 0; i < cnt; ++i) {
            int8_t in[TCN_W][TCN_CIN];
            int16_t ref[2], o[2];
            if (fread(in, 1, sizeof in, f) != sizeof in || fread(ref, 2, 2, f) != 2) {
                printf("short file\n");
                return 3;
            }
            tcn_run_q((const int8_t (*)[TCN_CIN])in, o, g_scratch);
            for (int32_t j = 0; j < 2; ++j) {
                const int32_t d = absdiff(o[j], ref[j]);
                if (d > max_db) max_db = d;
                if (d != 0) n_bad_b++;
                nb++;
            }
        }
        fclose(f);
        printf("file_vectors n=%ld mismatches=%ld max_abs_diff_lsb=%ld\n", (long)nb, (long)n_bad_b, (long)max_db);
    }
#else
    (void)argc;
    (void)argv;
    g_bench_in = tv_int_in[0];
    const uint32_t reps = 16u;
    const uint32_t ticks = tcn_bench_ticks(bench_once, reps);
    printf("bench reps=%lu systick_ticks=%lu\n", (unsigned long)reps, (unsigned long)ticks);
    const uint32_t cal_n = 100000u;
    printf("calib loop_instructions=%lu systick_ticks=%lu\n", (unsigned long)(2u * cal_n),
           (unsigned long)tcn_bench_loop_ticks(cal_n));
#endif
    printf("model_hash_low32=0x%08lx scratch_bytes=%lu\n", (unsigned long)tcn_model_hash_low32(),
           (unsigned long)tcn_scratch_bytes());
    const int32_t total = n_bad + n_bad_f + n_bad_r + n_bad_b;
    printf("RESULT %s\n", total == 0 ? "PASS" : "FAIL");
    return total == 0 ? 0 : 1;
}
